### ISSUE TITLE
onBeaconServiceConnect() not being called

### ISSUE THREAD

**Issue by icerfish** [AltBeacon/android-beacon-library#10]
Hi David,

I'm trying to implement a basic iBeacon monitor based off your [iBeaconReferenceAndroid](https://github.com/RadiusNetworks/ibeacon-reference-android/blob/master/src/org/altbeacon/beaconreference/MonitoringActivity.java) example application.

However either the BeaconManager doesn't manage to bind the implemented BeaconConsumer, or the Overrided onBeaconServiceConnect() is never being called.

However when I destroy the activity I get the following LOG, but other than that, nothing:
`08-05 12:58:28.260: D/BeaconManager(19022): Unbinding`

I've included my code below, just in case I've done something silly, but I think it should be all correct.

Using Eclipse as my IDE, and created the library project using the src, and the files found inside scripts/eclipse-support. Phone is Galaxy S4 running KitKat.

``` java
import org.altbeacon.beacon.BeaconConsumer;
import org.altbeacon.beacon.BeaconManager;
import org.altbeacon.beacon.BeaconParser;
import org.altbeacon.beacon.MonitorNotifier;
import org.altbeacon.beacon.Region;

import android.app.Activity;
import android.os.Bundle;
import android.os.RemoteException;
import android.util.Log;

public class BeaconActivity extends Activity implements BeaconConsumer {
    public static String TAG = "BeaconActivity";

    private BeaconManager beaconManager;
    private Region region = new Region("myMonitoringUniqueId", null, null, null);

    @Override
    protected void onCreate(Bundle savedInstanceState){
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_beacon);

        beaconManager = org.altbeacon.beacon.BeaconManager.getInstanceForApplication(this);
        beaconManager.getBeaconParsers().add(new BeaconParser().
                setBeaconLayout("m:2-3=0215,i:4-19,i:20-21,i:22-23,d:25-25"));
        beaconManager.bind(this);
    }

    @Override
    public void onBeaconServiceConnect() {
        Log.i(TAG, "Beacon Service Connected");

        beaconManager.setMonitorNotifier(new MonitorNotifier() {
            @Override
            public void didEnterRegion(Region region) {
                Log.i(TAG, "I just saw a beacon named "+ region.getUniqueId() +" for the first time!" );
            }

            @Override
            public void didExitRegion(Region region) {
                Log.i(TAG, "I no longer see a beacon named "+ region.getUniqueId());
            }

            @Override
            public void didDetermineStateForRegion(int state, Region region) {
                Log.i(TAG, "I have just switched from seeing/not seeing beacons: "+state);
            }

        });

        try {
            beaconManager.startMonitoringBeaconsInRegion(region);

        } catch (RemoteException e) {
            Log.e(TAG, "Remote Exception Error: ");
            e.printStackTrace();
        }
    }

    @Override
    public void onDestroy(){
        super.onDestroy();
        beaconManager.unbind(this);
    }

}
```

EDIT:
I set debugging to true inside BeaconManager.java, and it appears to be binding fine.

```
08-05 13:16:16.802: D/BeaconManager(1494): This consumer is not bound.  binding: co.makelight.BeaconActivity@429b8778
08-05 13:16:16.802: D/BeaconManager(1494): consumer count is now:1
```

**Comment by EtherBit** [comment]
I do not know if you have already solved the issue, but I was having the same issue (in eclipse). Solved it by including this in the manifest:
```
 <service
            android:name="org.altbeacon.beacon.service.BeaconService"
            android:enabled="true"
            android:exported="false"
            android:isolatedProcess="false"
            android:label="beacon" />
        <service
            android:name="org.altbeacon.beacon.BeaconIntentProcessor"
            android:enabled="true"
            android:exported="false" />
```

**Comment by mateuspaduan** [comment]
I'm having the same problem in Android Studio using an Asus device (API 22). When I'm pressing a button to bind it just doesn't do anything. Can it be a permission problem? I'm new in Android development so I just don't know what to do.

Here's my code:

package com.sobag.beaconplayground.Activity;

import android.content.Intent;
import android.os.Bundle;
import android.os.RemoteException;
import android.support.design.widget.FloatingActionButton;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;
import android.view.View;
import android.widget.Toast;

import com.sobag.beaconplayground.Controller.SharedPreferencesController;
import com.sobag.beaconplayground.R;

import org.altbeacon.beacon.Beacon;
import org.altbeacon.beacon.BeaconConsumer;
import org.altbeacon.beacon.BeaconManager;
import org.altbeacon.beacon.BeaconParser;
import org.altbeacon.beacon.Identifier;
import org.altbeacon.beacon.RangeNotifier;
import org.altbeacon.beacon.Region;

import java.util.Collection;


public class BlankActivity extends AppCompatActivity implements BeaconConsumer{

    private FloatingActionButton exit;
    private FloatingActionButton scanBeacons;

    private BeaconManager beaconManager;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_blank);

        beaconManager = BeaconManager.getInstanceForApplication(this);
        beaconManager.getBeaconParsers().add(new BeaconParser().setBeaconLayout("m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24"));

        exit = (FloatingActionButton) findViewById(R.id.exit);
        scanBeacons = (FloatingActionButton) findViewById(R.id.scanBeaconsButton);

        final BeaconConsumer beaconConsumer = this;

        exit.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                SharedPreferencesController.putString(BlankActivity.this, "username", "-1");
                SharedPreferencesController.putString(BlankActivity.this, "password", "-1");

                Intent i = new Intent(BlankActivity.this, LoginActivity.class);
                startActivity(i);
                finish();
            }
        });

        scanBeacons.setOnClickListener(new View.OnClickListener(){
            @Override
            public void onClick(View v){

                beaconManager.bind(beaconConsumer);
            }
        });
    }

    @Override
    public void onBeaconServiceConnect() {

        beaconManager.addRangeNotifier(new RangeNotifier() {
            @Override
            public void didRangeBeaconsInRegion(Collection<Beacon> beacons, Region region) {

                if(beacons.size() > 0){

                    Beacon beaconsFound = beacons.iterator().next();
                    Log.i("DETECTING", "UUID: " + beaconsFound.getId1().toString() + " Major: " + beaconsFound.getId2().toString() +
                            " Minor: " + beaconsFound.getId3().toString());

                    try{

                        Identifier regionToScan = Identifier.parse("e2c56db5-dffb-48d2-b060-d0f5a71096E0");
                        beaconManager.startRangingBeaconsInRegion(new Region("Region", regionToScan, null, null));
                    } catch (RemoteException e) {}
                }
                else Toast.makeText(BlankActivity.this, "No beacon found", Toast.LENGTH_SHORT).show();
            }
        });
    }
}
