### ISSUE TITLE
AoA and AoD

### ISSUE THREAD

**Issue by cece95** [AltBeacon/android-beacon-library#1000]
### Android Beacon Library version

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

Hi,
I was wondering, is it possible to obtain the Angle of Arrival and/or the Angle of Departure for Bluetooth 5.1 devices using this library?

Best
Cesare

**Comment by davidgyoung** [comment]
Sorry, there is no support for AoA in this library.   Android 11 does not support any bindings to such functionality in the bluetooth hardware, so as of now it is not possible.
