### ISSUE TITLE
Access Advertising Flags (such as, BR/EDR) using AltBeacon Lib?

### ISSUE THREAD

**Issue by yong3liu2** [AltBeacon/android-beacon-library#1003]
Hello,

Using Altbeacon lib, I can see the beacons that I am looking for in public void didEnterRegion(Region region) { ...}

But I also would like to read AD Flags such as following, for example: 
02 # Number of bytes that follow in first AD structure 
01 # Flags AD type 
1A # Flags value 0x1A = 000011010 
bit 0 (OFF) LE Limited Discoverable Mode 
bit 1 (ON) LE General Discoverable Mode 
bit 2 (OFF) BR/EDR Not Supported 
bit 3 (ON) Simultaneous LE and BR/EDR to Same Device Capable (controller) 
bit 4 (ON) Simultaneous LE and BR/EDR to Same Device Capable (Host)

Is there an API in Altbeacon lib to read the Flags?  I do see Android has something like: https://developer.android.com/reference/android/bluetooth/le/ScanRecord#getAdvertiseFlags()

Just not finding anything like it in Altbeacon lib yet.  It would be nice to have it.

Thanks, 
Yong

**Comment by davidgyoung** [comment]
The library currently ignores flags AD types, so this is currently not possible.    It would be possible to add support for parsing this information.  If you are interested in contributing to the library, I could give you some tips on how to add such a feature.

**Comment by davidgyoung** [comment]
Upon further review, this is not supported by Android APIs.
