### ISSUE TITLE
 ANR observed

### ISSUE THREAD

**Issue by PrashantMishra-Zebra** [AltBeacon/android-beacon-library#1012]
### Expected behavior 
ANR should not be observed

### Actual behavior
 ANR is observed

### Steps to reproduce this behavior
Start beacon scanning and stop beacon scanning repeatedly for 3 days.

### Mobile device model and OS version
Device: Zebra TC72
OS: Android Oreo

### Android Beacon Library version
2.15.4
[trace_00.txt](https://github.com/AltBeacon/android-beacon-library/files/5583100/trace_00.txt)
[Main0.txt](https://github.com/AltBeacon/android-beacon-library/files/5583104/Main0.txt)

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment]
@PrashantMishra-Zebra, why do you think the library caused this ANR?  I do see from the crash log in trace_00.txt that the library was in use and that there are at least two threads performing library operations when the crash happens.  However, there are several other threads running that are not executing code from this library, including UI rendering threads, a Firebase thread.  Can you please point to something that suggests this library caused the crash?
