### ISSUE TITLE
AltBeacon spamming the log

### ISSUE THREAD

**Issue by SorenKonekt** [AltBeacon/android-beacon-library#1013]
### Expected behavior
No duplicates of logs

### Actual behavior
The library will report an endless amount of repeating message like for example:

11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:19:38.886  9574  9574 I BeaconService: stop ranging received
11-30 12:19:38.902  9574  9574 I BeaconService: start ranging received
11-30 12:24:29.228  9574  9574 I BeaconService: stop ranging received
11-30 12:24:29.228  9574  9574 I BeaconService: stop ranging received
11-30 12:24:29.231  9574  9574 I BeaconService: stop ranging received
11-30 12:24:29.231  9574  9574 I BeaconService: stop ranging received
11-30 12:24:29.234  9574  9574 I BeaconService: start ranging received
11-30 12:24:29.234  9574  9574 I BeaconService: start ranging received
11-30 12:24:29.228  9574  9574 I BeaconService: stop ranging received
11-30 12:24:29.228  9574  9574 I BeaconService: stop ranging received
11-30 12:24:29.231  9574  9574 I BeaconService: stop ranging received
11-30 12:24:29.231  9574  9574 I BeaconService: stop ranging received
11-30 12:24:29.234  9574  9574 I BeaconService: start ranging received
11-30 12:24:29.234  9574  9574 I BeaconService: start ranging received
11-30 12:24:29.228  9574  9574 I BeaconService: stop ranging received
11-30 12:24:29.228  9574  9574 I BeaconService: stop ranging received
11-30 12:24:29.231  9574  9574 I BeaconService: stop ranging received
11-30 12:24:29.231  9574  9574 I BeaconService: stop ranging received
11-30 12:24:29.234  9574  9574 I BeaconService: start ranging received
11-30 12:24:29.234  9574  9574 I BeaconService: start ranging received
11-30 12:24:29.228  9574  9574 I BeaconService: stop ranging received
11-30 12:24:29.228  9574  9574 I BeaconService: stop ranging received
11-30 12:24:29.231  9574  9574 I BeaconService: stop ranging received

and this can go on for like 20 minutes.

### Steps to reproduce this behavior
Not sure

### Mobile device model and OS version
Android phones

### Android Beacon Library version
2.17.1

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment]
This is clearly indicative of a problem with your app.  What is going on such that it is starting and stopping ranging many times a sec?  Suppressing these logs would merely mask the problem, so so do not think doing so is a wise approach.

 Suggest you investigate why it is starting and stopping ranging so often.
