### ISSUE TITLE
RegionBootstrap: How to prevent any running ScanJob while app is in foreground ?

### ISSUE THREAD

**Issue by matdev** [AltBeacon/android-beacon-library#1017]
I've an app that uses to the android-beacon-library to detect when the smartphone enters in range of some Beacons. After opening the app for the first time and initializing the RegionBootstrap, I noticed that org.altbeacon.beacon.service.ScanJob are run by the lib. This seems to cause delays with the app's main Bluetooth scanner, which runs only when the app is in foreground.

Therefore, I'd like the Beacon lib to scan for beacons only when the app is in background, or closed.

What is the best way for implementing this behavior please ?

### Android Beacon Library version
2.17.2

**Comment by davidgyoung** [comment]
The simple solution is to not use RegionBootstrap.  Instead, in your activity or fragment, call beaconManager.bind(...) then when you get a callback to onBeaconServiceConnected start ranging or monitoring.  When your app goes to the background, stop ranging/monitoring and call beaconManager.unbind(...)
