### ISSUE TITLE
Sometime Beaconscanning is have error and restart 

### ISSUE THREAD

**Issue by usy1473** [AltBeacon/android-beacon-library#1054]
### Expected behavior
background service is search beacons continuously in foreground

### Actual behavior
this scanning is stop and restarting sometimes and can`t find beacons before restart app

### Steps to reproduce this behavior
See the Expected behavior.

### Mobile device model and OS version
Galaxy s21u
android 11

### Android Beacon Library version
2+

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment]
@usy1473 thank you for this report. but it is way too vague to be actionable.  This library has been well tested with Samsung devices on Android 11, so I do not believe this is a general problem.

What do you mean by this description: "background service is search beacons continuously in foreground".  Are you using a foreground service?  What are the *specific* steps used to reproduce a failure? How you know it has failed?  

A few tips to help:

* Please use the official [reference app](https://github.com/davidgyoung/android-beacon-library-reference-kotlin).  To do your testing to reproduce the problem.  If you need to make modifications to reproduce (e.g. by enabling the foreground service), please say specifically how you did so.

* Please turn on debug logging in the library with `beaconManager.setDebug(true)`

* Please provide specific steps to reproduce the problem along with details about the conditions of the test (e.g. what beacon you are using, what specific time you turn it on, turn it off, etc.)

* Please provide a LogCat excerpt with timestamps to help show details of any failure condition.

I am going to close this ticket for now as it is too vague to her actionable.  I encourage you to perform the steps above and submit a new issue if you can collect the requested information.
