### ISSUE TITLE
Library always detect Estimote White Beacon model to a distance lower than one meter

### ISSUE THREAD

**Issue by fwermus** [AltBeacon/android-beacon-library#1057]
### Expected behavior
Estimote white models beacons distance should reflect the actual distance of the Estimote beacon from the android cell phone.

### Actual behavior
Estimote white models beacons distance are tested below a meter no matter where the beacon is.

### Steps to reproduce this behavior

Take a Estimote White model beacon to 25 mts and got a distance below a meter.

### Mobile device model and OS version

Moto G8 on Android 11.

### Android Beacon Library version

org.altbeacon:android-beacon-library:2+

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment]
@fwermus, can you please use the Beacon Scope app (based on this library) to take a screen shot of what you see for both a distance estimate and Rssi at one meter for your phone and beacon?

https://play.google.com/store/apps/details?id=com.davidgyoungtech.beaconscanner&hl=en_US&gl=US

**Comment by fwermus** [comment]
![scanning100mts](https://user-images.githubusercontent.com/140713/132739516-f708095a-bb33-4f27-8bd0-c78987bdd6fa.jpeg)
![scanning50mts](https://user-images.githubusercontent.com/140713/132739520-cde6ac8a-96ac-4220-a47a-df97135bda7f.jpeg)
![scanning25mts](https://user-images.githubusercontent.com/140713/132739522-6c8ef97e-9c9e-49e7-a3cc-bae7a308a5ba.jpeg)

Next comment, at 1mts of distance

**Comment by davidgyoung** [comment]
So I see several different beacon identifiers scanned.  Which one is the beacon at 1 meter away?  One other request, can you please tap on the specific row of the beacon that is one meter away and take a screen shot of the detail screen.

**Comment by fwermus** [comment]
It shows two beacons but actually is one. For some reason, I don't know this estimote physical beacon shows two beacons. Some extra info about these beacons are that can emit iBeacon protocol as well as Estimote protocol at same time. I have sense this beacon at a distance of 1 mt.

![example-1mt](https://user-images.githubusercontent.com/140713/132953633-4af2a356-4679-47b5-89a8-5f814919de9b.jpeg)

**Comment by davidgyoung** [comment]
The screenshot shows two beacon transmissions with a distance estimate well below 1 meter and a RSSI of -52 (which is typical at one meter).  This suggests to me that whatever is transmitting is improperly calibrated.  You will need to address this with Estimote so that the measured power configuration of the beacon is set properly.  This forum answer describes how it is supposed to work:  https://forums.estimote.com/t/broadcasting-power-rssi-and-measured-power-explained/1047
