### ISSUE TITLE
Unable to Identity all the beacons in the Surrounding  

### ISSUE THREAD

**Issue by Mukund2900** [AltBeacon/android-beacon-library#1068]
I am running the code in my local and have build a basic app to get the output of this beacon but sometimes it identifies the beacon sometimes it does not , Can someone help me figure out a way to use this library properly to get desired output. Can i increase the rate at which its looking out for the beacons?

**Comment by davidgyoung** [comment]
For help with your project please open a new question on Stackoverflow.com showing your code and describing your test steps and beacon transmitter
