### ISSUE TITLE
Android 12 beacon not Scanning didRangeBeaconsInRegion beacon not detected with RxAndroidBle Gradle Add

### ISSUE THREAD

**Issue by mjkimloan** [AltBeacon/android-beacon-library#1070]
**Expected behavior**

Add RxandroidBle to Gradle and beacon scan working

**Actual behavior**

but Add RxandroidBle to Gradle and beacon scan not working
RxandroidBle All Version Same

    override fun didRangeBeaconsInRegion(beacons: MutableCollection<Beacon>, region: Region) {
        Log.e(TAG, "Ranged: ${beacons.count()} beacons")
        Log.e(TAG, "Ranged: 0 beacons")
    }

**Mobile device model and OS version**
Galaxy S21 Android 12

**Android Beacon Library version**
2.19.3

**Notice** : RxAndroidBle version is 1.13.1 and Android 12 and lower versions scan beacons normally. 
Remove Rxandroidble from Gradle and beacons will scan normally. How can I solve this problem?

**Comment by SergeyLaukhin** [comment]
@mjkimloan Did you fix it? The same behavior, I really need your help.
Thank you.

**Comment by zahichemaly** [comment]
I am facing the same issue. Were you able to solve this?

**Comment by davidgyoung** [comment]
On Android 12, your app needs to obtain BLUETOOTH_SCAN permission or it will get the result described.  See [here](https://developer.android.com/guide/topics/connectivity/bluetooth/permissions#declare-android12-or-higher)

**Comment by zahichemaly** [comment]
I already gave it that permission, and it is still not working. Only when I removed the Rxandroidble it worked again.

**Comment by davidgyoung** [comment]
You might try looking at your merged manifest when RxAndridBle is added to see if it makes changes that break your permissions setup.  You can see instructions on inspecting manifest merging problems here https://developer.android.com/studio/build/manage-manifests

**Comment by zahichemaly** [comment]
Thanks a bunch. I found the issue. RxAndroidBle was using `android:usesPermissionFlags="neverForLocation"` which filters beacon discovery in the scan.

I added the following permission and explicitly removed the flag:

```
    <uses-permission
        android:name="android.permission.BLUETOOTH_SCAN"
        tools:remove="android:usesPermissionFlags"
        tools:targetApi="s" /> 
```

**Comment by davidgyoung** [comment]
Hey, Great, @zahichemaly.  Glad to hear you found it.
