### ISSUE TITLE
power consumption tests

### ISSUE THREAD

**Issue by mherrm** [AltBeacon/android-beacon-library#111]
hello guys,

i am doing some test regarding the power consumption of the libary with different sets of parameters.
i found out that it is not important how often you scan but rather how long you scanned in total. Can you confirm this?

backgroung scanning: 10s scan, 10m pause same consumption as with 5s, 5m pause

**Comment by davidgyoung** [comment]
This is consistent with my tests, yes. Generally, you want to scan for 2x-5x the beacon transmission frequency, because some transmissions get missed and you want to be 99% + sure you get detections if you are only scanning periodically.
