### ISSUE TITLE
How to calculate the Beacon Uptime from the eddy stone packet. I am using Confidex beacon for my project. Do we have any library function to extract this information.

### ISSUE THREAD

**Issue by rakathal** [AltBeacon/android-beacon-library#1112]
### Android Beacon Library version

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment]
No, the Eddystone frames, including Eddystone-TLM to not include any information about uptime.

**Comment by rakathal** [comment]
This is the information that Confidex Team has provided 
![image](https://user-images.githubusercontent.com/29569593/202226344-c6d0603a-2c54-4641-af48-0f30a0cfbeed.png)

**Comment by davidgyoung** [comment]
Yes, it seems that is correct -- the Eddystone-TLM Frame does have an uptime field.  I had not worked with this format in years, so I had forgotten.

So yes, you can use the library to read that field.  How to do so is fully documented in the **Getting Ranging Updates from Nearby Beacons With Telemetry** section [here](Getting Ranging Updates from Nearby Beacons With Telemetry)
