### ISSUE TITLE
Unresolved reference: getRegionViewModel

### ISSUE THREAD

**Issue by niravtopsy** [AltBeacon/android-beacon-library#1118]
All libs and project are setup properly but when i tried to run the project, I am getting following error.

        Unresolved reference: getRegionViewModel

On line number :

        beaconManager.getRegionViewModel(region).regionState.observe(this@MainActivity, monitoringObserver)
        beaconManager.startMonitoring(region)
        
 Please let me know how to fix it.

**Comment by davidgyoung** [comment]
Troubleshooting specific build enviornment issues can be tricky.  The library builds successfully on CircleCI servers using this configuration: https://github.com/AltBeacon/android-beacon-library/blob/master/.circleci/config.yml

You may wish to compare you build environment with the CircleCI setup and try to match what they have as closely as possible to see if you can get it to work.
