### ISSUE TITLE
Any suggestions to filter and get proper rssi ? 

### ISSUE THREAD

**Issue by gptshubham595** [AltBeacon/android-beacon-library#1119]
### Expected behavior
 There should not be much variation in the rssi value even if phone is kept very near

### Actual behavior
The rssi value even after kalman filter we are getting very much varying like -70,-65,-72,-68,-31,-69

### Steps to reproduce this behavior
Just run the beacon reference app on mobile

### Mobile device model and OS version
Device: Oppo, OnePlus, Motorola

### Android Beacon Library version
2.19.4

**Comment by davidgyoung** [comment]
This forum is reserved for feature requests and bug reports with the library itself. For help with using the library, please open a question on StackOverflow.com.   If you see specific problems with the built in RunningAverageRssi filter, please file a bug report with specifics.  But understand that the library is limited about what it can do given widely varying RSSI inputs from the Android Bluetooth stack on specific devices
