### ISSUE TITLE
How to connect, disconnect and read, write to beacon

### ISSUE THREAD

**Issue by niravtopsy** [AltBeacon/android-beacon-library#1120]
I am getting list of all the beacons, now i want to click on specific beacon and after that i want to connect it and disconnect it by clicking on it, and want to read and write data. Please can you inform how to do or achieve it?

**Comment by davidgyoung** [comment]
This forum is reserved for feature requests and bug reports with the library itself. For help with using the library, please open a question on StackOverflow.com.  Please note that this library is designed to detect beacons which are one way transmitters.  This library is not designed to assist  with establishing GATT connections or reading data.
