### ISSUE TITLE
High latency of detecting beacons on Android 11 when internet is Off

### ISSUE THREAD

**Issue by Giluna1** [AltBeacon/android-beacon-library#1122]
Since it's known that scanning beacons shouldn't require an internet connection, we were expecting [Android Beacon Library](https://github.com/AltBeacon/android-beacon-library) by AltBeacon to detect beacons the same when the device is with or without an internet connection. Unfortunately, this is not the case in Android 11.

We've recently implemented the [Android Beacon Library](https://github.com/AltBeacon/android-beacon-library) in our app and noticed a significant latency on Android 11 when the device is not connected to the internet (tested on Xiaomi 11). In contrast, on an Android 12 device the beacon detection works fast with or without an internet connection (tested on Xiaomi 12).

The latency seems to be caused by the call of the rangingObserver declared in:

beaconManager.getRegionViewModel(region).rangedBeacons.observe(this, rangingObserver)
It might be worth mentioning that we've also noticed a similar issue in the [Beacon Scanner App](https://play.google.com/store/apps/details?id=com.bridou_n.beaconscanner&hl=en&gl=US) which also implemented with the Android Beacon Library. Again, without an internet connection, the scanner has a significant latency in rendering the scanning list on an Android 11 device.

Has anyone encountered this issue or has any idea how this can be solved?
Please advise.

[See a screenshot of Beacon Scanner App with and without Internet](https://i.stack.imgur.com/FIIcS.jpg)

Replication guidelines:

1. Use an Android 11 device.
2. Download the [Beacon Scanner App](https://play.google.com/store/apps/details?id=com.bridou_n.beaconscanner&hl=en&gl=US).
3. Turn off any internet connection on your device (including Mobile Data and Wi-Fi).
4. Put several beacons in the region.
5. Launch the Beacon Scanner app and start scanning (important: make sure to kill the app if it was open before).
6. You should notice that the app is scanning but presents empty results for about a minute or more.
7. Try to launch the app with an active internet connection (via Mobile Data or Wi-Fi) and you will notice the detection happens instantly.

This issue has also been published in StackOverflow [here](https://stackoverflow.com/questions/75103489/android-beacon-scanner-altbeacon-has-high-latency-of-detecting-beacons-on-andr).

**Comment by davidgyoung** [comment]
Closed in favor of discussion here https://stackoverflow.com/questions/75103489/android-beacon-scanner-altbeacon-has-high-latency-of-detecting-beacons-on-andr
