### ISSUE TITLE
One plus background not detecting beacons

### ISSUE THREAD

**Issue by Spectra6170** [AltBeacon/android-beacon-library#1124]
One Plus devices not detecting any beacon device with ble when application is in background mode or closed.

**Comment by davidgyoung** [comment]
For background detections on OnePlus devices **you must have the user disable battery optimization for your app as described here**:

https://dontkillmyapp.com/oneplus

The recommended approach for apps is to detect a OnePlus device and instruct the user to perform those steps in order for the app for perform the background functions.

If you still have trouble after disabling battery optimization as described above, please test with the official reference app here: https://github.com/davidgyoung/android-beacon-library-reference-kotlin and attach a LogCat excerpt showing all system-level logs (not filtered for your application for a 60 second + period where you:

1. Ensure no beacons are transmitting and your app is not running
2. Start a logical capture
3. Launch your app
4. Put your app to the background
5. Turn on a beacon
6. Wait 30 seconds
