### ISSUE TITLE
ScanHelper: Beacon simulator not enabled

### ISSUE THREAD

**Issue by TyagiAnkit-100** [AltBeacon/android-beacon-library#1127]
### Expected behavior

It should continue scanning beacons  

### Actual behavior

Throwing "ScanHelper: Beacon simulator not enabled" when screen turned off in Samsung A23 OS 13 device. Not scanning even after unlocking again

### Steps to reproduce this behavior

Simply lock the screen

### Mobile device model and OS version

Samsung A23 OS 13 device.

### Android Beacon Library version
Latest: 2.19.5

**Comment by davidgyoung** [comment]
The log line about “Beacon simulator not enabled” is expected and does not indicate a problem. See the code here:

https://github.com/AltBeacon/android-beacon-library/blob/master/lib/src/main/java/org/altbeacon/beacon/service/ScanHelper.java#L309

if you believe the library is not detecting beacons in some cases where it should, please first test with the official reference app then  open a new issue that describes the specific conditions where this happens with steps needed to reproduce.  Please also include a log excerpt that shows detections working then stopping.

If you never detect beacons at all, please first use this troubleshooting guide:

https://altbeacon.github.io/android-beacon-library/detection-trouble.html
