### ISSUE TITLE
Feature request: Id4 support

### ISSUE THREAD

**Issue by LucaAtWork** [AltBeacon/android-beacon-library#1133]
Hello,
I'm using this library to simulate a Beacon on one of my Android devices.
The library allows you to set id1, id2 and id3 parameters, but not id4.
The client that is going to communicate with my simulator heavily relies on this parameter (id4).
Can you implement the ability to set id4? Is there any technical limitations that prevent this feature?
Thanks a lot.

**Comment by davidgyoung** [comment]
While standard iBeacon and AltBeacon formats don't support a fourth identifier, this library already allows you to define your own beacon format with any number of identifiers that you want (so long as they fit into the ~20 bytes available in a BLE advertisement).  See here for info for setting up your own BeaconParser:  https://altbeacon.github.io/android-beacon-library/javadoc/org/altbeacon/beacon/BeaconParser.html#setBeaconLayout(String)

If you need help doing that with the library, please open a question on StackOverflow.com and tag it with ibeacon.
