### ISSUE TITLE
Is it possible to edit the ID1 of a beacon using this library?

### ISSUE THREAD

**Issue by egeres** [AltBeacon/android-beacon-library#1137]
I hope I'm not mistaken, but as far as I know all BLE beacons come with a default ID1 equal to `fda50693-a4e2-4fb1-afcf-c6eb07647825`. The [cheap ones from a brand named holyiot](https://es.aliexpress.com/item/1005003211033416.html) allow for modification of their ID1 as well as other parameters via [an app](https://play.google.com/store/apps/details?id=com.jx.bledemo). Is this something implemented in AltBeacon? So far I haven't  found any issues referencing this or information in the docs!

**Comment by davidgyoung** [comment]
This library does not support configuring beacons to change their identifiers. There is no standard way to do this -- every beacon manufacturer has a different mechanism for configuring identifiers.  Some support this only with a proprietary app, some have a proprietary SDK, and some don't allow this at all.
