### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by KashifAhmad** [AltBeacon/android-beacon-library#1143]
### Expected behavior
To connect with beacon
### Actual behavior
crashing when connecting to beacon:

Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

org.altbeacon.beacon.service.scanner.CycledLeScanner.getWakeUpOperation

### Steps to reproduce this behavior
Whenever my app get's open, it crashes and give the above error. 

### Mobile device model and OS version
OS 31-33

### Android Beacon Library version
Latest

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment]
Please confirm the exact version of the library you are using  as "latest" may not be what you think it is.

The latest code already sets the PendingIntent flag to IMMUTABLE as seen here:
https://github.com/AltBeacon/android-beacon-library/blob/master/lib/src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanner.java#L529

The above change was made two years go and is in release 2.19 and all subsequent releases.

Please reopen this issue if you can confirm it exists with the latest [2.19.5](https://mvnrepository.com/artifact/org.altbeacon/android-beacon-library/2.19.5)
