### ISSUE TITLE
Maven Publishing Issue

### ISSUE THREAD

**Issue by pieces029** [AltBeacon/android-beacon-library#115]
Hey @davidgyoung,

Just realized `publish = true` needs to be added to the bintray.gradle under publications. That will solve the issue of the maven central sync not happening.

**Comment by davidgyoung** [comment]
like this?

    bintray {
        user = bintrayUsername
        key = bintrayKey
        publications = ['dist', 'publish = true']
    ...

**Comment by pieces029** [comment]
Sorry for the confusion that wasn't worded very well. It just needs to be on the top level bintray object.

Like here https://github.com/pieces029/android-spock/blob/master/gradle/bintray.gradle

I just happen to have it directly below publications.

**Comment by davidgyoung** [comment]
that makes more sense.  thanks!

**Comment by davidgyoung** [comment]
Fixed in 401bd8064f4892f925fd55f109664126fb1c7546
