### ISSUE TITLE
xamarin-android-altbeacon-library v2.19 not available to download from nuget packages

### ISSUE THREAD

**Issue by flameira** [AltBeacon/android-beacon-library#1154]
### Expected behavior
The application should be able to update the package to the latest version 2.19, but it is not available to download this version using nuget package source

### Actual behavior
Publishing app targeting Android 13 is failing because we must add the **android:exported **  attribute to the<receiver> tag for the StartupBroadcastReceiver.

### Steps to reproduce this behavior
Deployment xamarin forms application using android-beacon-library using 2.17 for Android , 

### Mobile device model and OS version
Android 13

### Android Beacon Library version
Last library available: Friday, July 31, 2020  (2.17.1) 

**Google Play Console Requires "App must target Android 13 (API level 33)." **

**Comment by davidgyoung** [comment]
@flameira please open this issue on the Xamarin repo here: https://github.com/pavlata2/xamarin-android-altbeacon-library

Understand that this is a different open source project, so the folks here probably won't see your request.
