### ISSUE TITLE
BLE Beacon scanning when app is killed

### ISSUE THREAD

**Issue by AlexIach** [AltBeacon/android-beacon-library#1161]
I have the following use-case. 
My app is installed on user device and I want a notification to be shown when user enters into beacon proximity zone for all thescenarios:
- App is in foreground;
- App in in background;
- App in killed.

I have a very SDK simple set up in my MainActivity
```
private lateinit var beaconManager: BeaconManager
beaconManager = BeaconManager.getInstanceForApplication(this)
```

```
private fun prepareBeaconConfigurations() {
        BeaconManager.getInstanceForApplication(this).setIntentScanningStrategyEnabled(true)
        beaconManager.beaconParsers.clear()
        val iBeaconLayout = "m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24"
        val altBeaconLayout = "m:2-3=beac,i:4-19,i:20-21,i:22-23,p:24-24,d:25-25"
        val iBeaconParser = BeaconParser().setBeaconLayout(iBeaconLayout)
        val altBeaconParser = BeaconParser().setBeaconLayout(altBeaconLayout)
        iBeaconParser.setHardwareAssistManufacturerCodes(arrayOf(0x004c).toIntArray())
        beaconManager.beaconParsers.add(iBeaconParser)
        beaconManager.beaconParsers.add(altBeaconParser)
}
```

Here is my code for Observers:
```
    private val centralRangingObserver = Observer<Collection<Beacon>> { beacons ->
        val rangeAgeMillis =
            System.currentTimeMillis() - (beacons.firstOrNull()?.lastCycleDetectionTimestamp ?: 0)
        if (rangeAgeMillis < 10000) {
            logger.logD(TAG, "Ranged: ${beacons.count()} beacons")
            for (beacon: Beacon in beacons) {
                logger.logD(TAG, "$beacon about ${beacon.distance} meters away")
            }
        } else {
            logger.logD(TAG, "Ignoring stale ranged beacons from $rangeAgeMillis millis ago")
        }
    }

    private val centralMonitoringObserver = Observer<Int> { state ->
        if (state == MonitorNotifier.OUTSIDE) {
            logger.logD(TAG, "Outside beacon region: $region")
            sendNotification("A beacon connection is left.")
            Toast.makeText(this, "A beacon connection is left.", Toast.LENGTH_SHORT).show()
        } else {
            logger.logD(TAG, "Inside beacon region: $region")
            sendNotification("A beacon is nearby.")
            Toast.makeText(this, "A beacon is nearby.", Toast.LENGTH_SHORT).show()

        }
    }
```

And here is the code I call when all necessary requirements are met (Permissions, BL e.t.s)
   ```
 private fun initBeaconObserver() {
        beaconManager.startMonitoring(region)
        beaconManager.startRangingBeacons(region)

        val regionViewModel =
            BeaconManager.getInstanceForApplication(this).getRegionViewModel(region)

        regionViewModel.regionState.observeForever(centralMonitoringObserver)
        regionViewModel.rangedBeacons.observeForever(centralRangingObserver)
    }
```

I face no problems when app is in foreground or in background. The problem is when app is killed. 
Having this config helped me to achieve desired behaviour but it's not working all the time.
`BeaconManager.getInstanceForApplication(this).setIntentScanningStrategyEnabled(true)`

What is the proper way to set up the library for my use-case?

### Mobile device model and OS version
Android 14

### Android Beacon Library version
2.20-beta1

**Comment by davidgyoung** [comment]
Your setup looks fine.  (However, getting all the time detections has become increasingly difficult do to the proliferation of OEM-specific Android customizations that kill apps or block Bluetooth scans in various app states.)

The specifics of your question depend on your device model and the details of the cases where you are making it fail. I'd suggest you open a question on StackOverflow (the proper forum for troubleshooting custom apps) and share snippets of your setup code and cases where the results are not what you expect.
