### ISSUE TITLE
Beacon library scanning issue

### ISSUE THREAD

**Issue by sanikaj** [AltBeacon/android-beacon-library#119]
Beacon library not consistently scanning for the right number of beacons . We tried setting the scan period from 4100 to 8000 and the delay from 5000 to 8000 however this did not change the number of beacons we saw. We were missing 2 beacons sometimes in the setRangeNotifier which picked up the other 4 signal.

**Comment by davidgyoung** [comment]
Hi. @sanikaj, sorry to hear you are having trouble.  

This forum is reserved for feature requests and reports of reproducible bugs that can be specifically documented.

Please post support requests to stackoverflow.com.  You will need to include more info including the beacon device models you are testing and whether you have trued the refence app or any other beacon detection apps.
