### ISSUE TITLE
model-distance json for One plus device 

### ISSUE THREAD

**Issue by sanikaj** [AltBeacon/android-beacon-library#121]
We would kindly like a distance measurement for the one plus device in this library.

**Comment by davidgyoung** [comment]
Unfortunately, we do not have a model to test with.  If you have one and can go through the procedure linked below, please open a new issue with the info.

http://altbeacon.github.io/android-beacon-library/distance-calculations.html

**Comment by sanikaj** [comment]
Sounds great. I will get it done and send you the details for sure.

On Fri, Feb 13, 2015 at 10:05 PM, David G. Young <notifications@github.com>
wrote:

> Unfortunately, we do not have a model to test with. If you have one and
> can go through the procedure linked below, please open a new issue with the
> info.
>
>
> http://altbeacon.github.io/android-beacon-library/distance-calculations.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AltBeacon/android-beacon-library/issues/121#issuecomment-74358861>
> .
>



-- 
Regards,
Sanika Joshi.
