### ISSUE TITLE
BeaconParser for iBeacon

### ISSUE THREAD

**Issue by mrtree1** [AltBeacon/android-beacon-library#13]
Quick and obvious question: What's the parsing string for iBeacons? 

I'd like to use this library, but I need to support iBeacons as well, and I'm currently using the previous iBeacon library.

**Comment by mreverter** [comment]
Hi, I'm making a library using yours, in which both Eddystone and iBeacon beacons can be detected.
I add both parsers with the respective layouts:
For Eddystone, the one given in your example, and for iBeacon the one in the stackoverflows's post commented up here.
My issue is that when an Eddystone beacon appears, it's detected as both kind of beacons. That does not happen when an iBeacon appears, so I think the Eddystone layout works fine (it just parses compatible beacons), but not the iBeacon one.

The thing is, in your beaconparser specs it says:
"m - matching byte sequence for this beacon type to parse"

And I set for iBeacon: m:2-3=0215.
For Eddystone, it is: m:2-2=00

So, how can it be, being the matching sequences different and exclusive (2-2 is different), that when an Eddystone beacon appears, it's not excluded by the parser of iBeacons and treats it as one?

By the way, I'm using Radius Network beacons. I get an Eddystone one as follows in my library:

Namespace: 0x2f234454f4911ba9ffa6  Instance: 0x000000000001
And (same beacon),
Uuid: 2f234454-cf6d-4a0f-adf2-f4911ba9ffa6  Major: 0 Minor: 1.

Hope you can help me out!
