### ISSUE TITLE
Unable to view beacons signal even if beacon is in range except the first time. 

### ISSUE THREAD

**Issue by sanikaj** [AltBeacon/android-beacon-library#133]
I have posted the issue to the forum on stackoverflow http://stackoverflow.com/questions/28734888/altbeacon-library-shows-beacons-only-once-and-then-stops-showing-them
Thank you.
Cheers,
Sanika.

**Comment by davidgyoung** [comment]
See answer here: http://stackoverflow.com/a/28997946/1461050
