### ISSUE TITLE
How to set the Advertising Flags when simulating a Beacon

### ISSUE THREAD

**Issue by michael-customlbs** [AltBeacon/android-beacon-library#141]
I got my test application to send out iBeacon packets. Most Apps recognize them, but some don't.

I saw that the packets are missing some flags (3 bytes in the beginning to be exact).
https://developer.mbed.org/blog/entry/BLE-Beacons-URIBeacon-AltBeacons-iBeacon/

Most iBeacons I know of send out 0x020106 or 0x02011A (see example below) as the first 3 bytes.

	02 # Number of bytes that follow in first AD structure
	01 # Flags AD type
	1A # Flags value 0x1A = 000011010  
	   bit 0 (OFF) LE Limited Discoverable Mode
	   bit 1 (ON) LE General Discoverable Mode
	   bit 2 (OFF) BR/EDR Not Supported
	   bit 3 (ON) Simultaneous LE and BR/EDR to Same Device Capable (controller)
	   bit 4 (ON) Simultaneous LE and BR/EDR to Same Device Capable (Host)
	1A # Number of bytes that follow in second (and last) AD structure
	FF # Manufacturer specific data AD type
	4C 00 # Company identifier code (0x004C == Apple)
	02 # Byte 0 of iBeacon advertisement indicator
	15 # Byte 1 of iBeacon advertisement indicator
	e2 c5 6d b5 df fb 48 d2 b0 60 d0 f5 a7 10 96 e0 # iBeacon proximity uuid
	00 00 # major 
	00 00 # minor 
	c5 # The 2's complement of the calibrated Tx Power

Is it possible to do that with the Android Beacon Library?

**Comment by davidgyoung** [comment]
Unfortunately, this is not currently allowed by the Android BLE APIs, so the library cannot this.
