### ISSUE TITLE
getInstanceForApplication should be renamed & is prone to context leaks

### ISSUE THREAD

**Issue by samskiter** [AltBeacon/android-beacon-library#143]
getInstanceForApplication or the BeaconManager class should probably call getApplicationContext on the application context to prevent leaks.

The suggested use for the BeaconManager is from an activity, like so:

`private BeaconManager beaconManager = BeaconManager.getInstanceForApplication(this);`

To prevent the activity being leaked, the beaconmanager should really make sure it calls `getApplicationContext` on the passed context.

Secondly `getInstanceForApplication` implies you should be passing an application to the method, simply `getInstance` might be better

**Comment by davidgyoung** [comment]
Fair point.  I think the simplest solution is to change this line:

`client = new BeaconManager(context);`

To:

`client = new BeaconManager(context.getApplicationContext());`

**Comment by samskiter** [comment]
Lgtm. Or put the getApplicationContext() into the constructor.

**Comment by cupakromer** [comment]
Can this be closed now that #381 has been merged?

**Comment by davidgyoung** [comment]
Fixed in #381
