### ISSUE TITLE
BeaconService never sets scanningEnabled true

### ISSUE THREAD

**Issue by samskiter** [AltBeacon/android-beacon-library#144]
scanningEnabled is never set to true, meaning after stopping ranging or monitoring, the service continues to scan

**Comment by davidgyoung** [comment]
Good catch.  This bug was apparently introduced in the migration to Android L scanning APIs.

**Comment by samskiter** [comment]
Is this now fixed?

**Comment by davidgyoung** [comment]
Apologies, I have not looked at this ticket in awhile so I'm trying to refresh my memory.  I remember the issue, but looking at the CycledLeSanner.java code, I see that mScanningEnabled is set to true here:

https://github.com/AltBeacon/android-beacon-library/blob/master/src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanner.java#L131

And that code dates back to 2014-10-06.  Is this where you saw the issue?

**Comment by samskiter** [comment]
No, i think it was here: https://github.com/AltBeacon/android-beacon-library/blob/2.1.4/src/main/java/org/altbeacon/beacon/service/BeaconService.java#L76

**Comment by samskiter** [comment]
Ah, looks like you fixed here: https://github.com/AltBeacon/android-beacon-library/commit/49db318d501bca901341303e5162166a51c68310

**Comment by davidgyoung** [comment]
Indeed!  It's been a busy few months.  Thanks for jogging my memory.
