### ISSUE TITLE
Identifier: Convenient use of java.util.UUID

### ISSUE THREAD

**Issue by flowlo** [AltBeacon/android-beacon-library#150]
I just started using this library today and had a look at the implementation of `org.altbeacon.beacon.Identifier`. I'm curious why there's no compatibility with `java.util.UUID`. I see that `Identifier` supports identfication in form of arbitrarily long `byte[]` arrays, but still you have `String toUuidString`, so `UUID toUuid()` and `Identifier fromUuid(UUID)` do not seem too far fetched. What gives?

**Comment by davidgyoung** [comment]
@flowlo, no disrespect to `java.util.UUID` intended.  This could easily be added.  If you'd like to create a pull request for this, I'd be glad to put this in.
