### ISSUE TITLE
Code goes spaghetti if viewed with tab width != 4

### ISSUE THREAD

**Issue by flowlo** [AltBeacon/android-beacon-library#155]
I just attempted to read `Beacon.java` and `Region.java` but totally went nuts as soon as I encountered that mess of whitespace.

*Tabs vs. Spaces* is an endless discussion. TBH I don't want to bring it up. This issue is about consistency and valid for both models: I see that most code uses 4 spaces as one level of indentation, but every now and then tabs kick in, which is suboptimal.

I personally choose tab width dependent on the language I read, and using a tab width of 2 here (really anything else than 4) will freak the reader out.

![Screenshot of Beacon.java with tab with of 2](https://cloud.githubusercontent.com/assets/542154/6997869/be0f61dc-dbcd-11e4-8305-704ee4de6a47.png)

This should be normalised throughout the whole codebase and have tests to cover future work. I'm happy to do this in case you want it to be done.

**Comment by davidgyoung** [comment]
Yes, we should be standardized on a tab length of four and use spaces instead of the tab character.  This is following the Android code style guidelines.

**Comment by samskiter** [comment]
+1

**Comment by flowlo** [comment]
@samskiter Feel free to have a look at #167

**Comment by davidgyoung** [comment]
Fixed in #167
