### ISSUE TITLE
Unbinding and rebinding does not trigger an `onBeaconServiceConnect`

### ISSUE THREAD

**Issue by samskiter** [AltBeacon/android-beacon-library#160]
My understanding of the api was that `onBeaconServiceConnect` is called when the beaconmanager is ready to use. Should it therefore be called if i unbind and rebind?

I currently unbind when my activity pauses and attempt to bind again when it starts, but then i get no callback. Does 'isBound' give me the same information as `onBeaconServiceConnect` ?

**Comment by jcady92** [comment]
Did you solve this? I'm seeing the same behavior and was wondering if there's a solution.

**Comment by samskiter** [comment]
I was mistaken, the onBeaconServiceConnect is called but no ranging is performed. See: https://github.com/AltBeacon/android-beacon-library/issues/161
