### ISSUE TITLE
Cannot scan for beacons

### ISSUE THREAD

**Issue by IgorGanapolsky** [AltBeacon/android-beacon-library#162]
Hello,
why is my Logcat being clobbered by this error:
"W/CycledLeScanner﹕ Bluetooth is disabled.  Cannot scan for beacons."?  It happens every 2 seconds, and my Logcat becomes unusable!

Please help,
Igor

**Comment by davidgyoung** [comment]
Sorry, @IgorGanapolsky.  This has been fixed in #142, and is available on master, but is not in a versioned release yet.

**Comment by IgorGanapolsky** [comment]
Will this be a versioned release in the near future?

**Comment by davidgyoung** [comment]
There is no hard date planned for the next versioned release, but it will certainly be in the next 30 days.
