### ISSUE TITLE
Why do you don't create a JAr for the eclipse users ?

### ISSUE THREAD

**Issue by CesarSantosDavid** [AltBeacon/android-beacon-library#169]
The user have to use the library like a library project. This is because you have to import other jars to your lib?

**Comment by davidgyoung** [comment]
The library project is used to supply default manifest entries needed for the library to work.    If you don't want to use a library project with eclipse, you can extract the jar and configure the manifest entries yourself according to these instructions:

http://altbeacon.github.io/android-beacon-library/alternate-configuration.html
