### ISSUE TITLE
Multiple Monitoring, Ranging Notifiers

### ISSUE THREAD

**Issue by Maxeee09** [AltBeacon/android-beacon-library#170]
Hi, 
I am working on a project which needs to monitor two distinct Regions. Considering the project architecture, I need to use two different Monitoring Notifiers to monitor these Regions. As I read in the BeaconManager class, it's not possible to set/register multiple Notifiers (monitoring or ranging). Only one Notifier instance is allowed. I think it is possible to replace single notifier instance (into BeaconManager) by a list of Notifiers. And then, change BeaconIntentProcessor behavior to loop over a Notifier list (for ranging and monitoring). 
Am I totally wrong to consider this kind of improvement (because it's already possible right now) or are you planning to add this capability ?

**Comment by davidgyoung** [comment]
We have considered adding multiple notifiers, yes, although there is no timeline for this change, and if it happens it would be in the next major release at least a few months away.

That said, there has not been any thought to making the notifiers *specific to a Region*, as this is the first time I have heard any such request.  If you want Region-specific notifiers, you can do so in custom code even with the single notifier supplied by the library.  Just write custom code in your notifier to maintain a map of regions to other notifiers, and forward the notification call to the notifier registered for the region.
