### ISSUE TITLE
Library as Dependecie of Library 

### ISSUE THREAD

**Issue by jmtt89** [AltBeacon/android-beacon-library#175]
Using this library like Dependency of my library, when include like module, no problem, all work ok 

But if want export my plugin like aar file and include like dependency in others proyects show me this error

```
error: cannot access BeaconConsumer
class file for org.altbeacon.beacon.BeaconConsumer not found
```

when i build it

i using Android Studio

**Comment by davidgyoung** [comment]
@jmtt89, Please open this as a support question on StackOverflow.com.  This is really a question on how to make a library project use a second library project as a dependency in Android Studio.  

This forum is reserved for bug reports and feature requests inside this library itself.
