### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by RenniePet** [AltBeacon/android-beacon-library#181]
Thanks for creating this code and making it available.

On this page http://altbeacon.github.io/android-beacon-library/configure.html there's a spelling mistake or typo, it says "follwoing" instead of "following". I was going to try to submit a pull request (despite my poor GitHub skills), but I can't find the source document.

Incidentally, are you interested in pull requests based on cosmetic improvements to the code - spelling mistakes, etc.? I have noted a few of those, although I'm generally very impressed by the quality of the code.

**Comment by davidgyoung** [comment]
Good catch, @RenniePet.  The documentation is in the following gh-pages branch.  Please feel free to submit PRs for against the docs or the code in general.

https://github.com/AltBeacon/android-beacon-library/tree/gh-pages
