### ISSUE TITLE
How to identify particular beacon

### ISSUE THREAD

**Issue by pollux-** [AltBeacon/android-beacon-library#193]
Suppose if I had created Beacon like below,

 Beacon beacon = new Beacon.Builder()
                .setId1("2f234454-cf6d-4a0f-adf2-f4911ba9ffa6")
                .setId2("1")
                .setId3("2")
                .setManufacturer(0x0118)
                .setTxPower(-59)
                .setDataFields(Arrays.asList(new Long[]{0l}))
                .setBluetoothName("YML")
                .build();
        BeaconParser beaconParser = new BeaconParser()
                .setBeaconLayout("m:2-3=beac,i:4-19,i:20-21,i:22-23,p:24-24,d:25-25");

How can I monitor/check the specific Beacon using mBeaconManager.startMonitoringBeaconsInRegion()
method ??

**Comment by davidgyoung** [comment]
@pollux- please post questions on how to use the library on StackOverflow.com, as this forum is reserved for feature requests and known bugs with the library.  For the sake of time, I will note that you should construct a `Region` object with your desired identifiers and not the `Beacon` object to set up monitoring.
