### ISSUE TITLE
Can this library can make android 5.0 and above mimic as iBeacon/beacon?

### ISSUE THREAD

**Issue by datomnurdin** [AltBeacon/android-beacon-library#201]
As per subject, is it possible? How accurate is it to calculate distance between two android devices?

**Comment by davidgyoung** [comment]
This is possible, but you need to provide you own BeaconParser expression for the proprietary iBeacon format.  Search Google for this, it's easy to find.

Answers to both of these questions can be found in the documentation links below.  If you have follow up questions, please open a new question on Stackoverflow.com as this forum is reserved for feature requests and bug reports with the library itself. 

http://altbeacon.github.io/android-beacon-library/beacon-transmitter.html

http://altbeacon.github.io/android-beacon-library/distance-calculations.html
