### ISSUE TITLE
Allow all kind of beacons 

### ISSUE THREAD

**Issue by woutergoossens** [AltBeacon/android-beacon-library#204]
Hi,

For a client I am developing an Android application with iBeacons support.
For now we support Kontact.io and Gumball beacons. I have to add the beacon layout to the BeaconParser but I want to know if it is possible to support all kind of beacons without adding the layout.

Otherwise if the client will use some other beacons, we need to be able to get the beacon layout and update the app..

Thanks in advance,

Wouter

**Comment by davidgyoung** [comment]
You must tell the library the layout of the beacons you want to detect.  It would not be possible to anticipate future beacon formats.

If you want to support new beacon formats with your app in the future, your choices are:

1. Add a new layout to your app and release an update.

2. Build a web service that your app checks periodically to download the lists of layouts to be used.  The app would then configure these layouts when it starts up.
