### ISSUE TITLE
How I can locate all beacons that exist around me?

### ISSUE THREAD

**Issue by datomnurdin** [AltBeacon/android-beacon-library#206]
As per subject, I didn't found any sample codes regarding to this issue here (Ranging and Monitoring) , http://altbeacon.github.io/android-beacon-library/samples.html. Can you guide me how to develop it? I'm clueless here.

![screen shot 2015-06-09 at 12 50 26 pm](https://cloud.githubusercontent.com/assets/5416242/8050760/655abe78-0ea5-11e5-9957-511dc7db8c43.png)

Please advice, thank you.

**Comment by davidgyoung** [comment]
If you need help with using the library, please open a question on StackOverflow.com.  This forum is reserved for feature requests and reporting reproducible bugs in the library itself.

For the sake of expedience, note that there is a reference app available here:  https://github.com/AltBeacon/android-beacon-library-reference  If you need more help, please open a question on StackOverflow.com
