### ISSUE TITLE
Misspell variable beaconManger on github.io 

### ISSUE THREAD

**Issue by datomnurdin** [AltBeacon/android-beacon-library#207]
You misspell variable beaconManger on github.io  for Ranging Example Code, http://altbeacon.github.io/android-beacon-library/samples.html.

```
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_ranging);
        beaconManger = BeaconManager.getInstanceForApplication(this); //here
        beaconManager.bind(this);
    }
```

![screen shot 2015-06-09 at 2 52 57 pm](https://cloud.githubusercontent.com/assets/5416242/8052116/8da86338-0eb6-11e5-9335-057d0672fc2f.png)

**Comment by davidgyoung** [comment]
Thanks!  Fixed here:  c4ab8670bbf1ab47f18865e8f3272be3136aa312
