### ISSUE TITLE
Background scanning in deep sleep

### ISSUE THREAD

**Issue by TeunVR** [AltBeacon/android-beacon-library#21]
Currently the BeaconService scans every 5 minutes in the background. It "waits" by doing a handler.postDelayed() every second. This mechanism stops when the device enters deep sleep, so it will not detect beacons in that case.
Maybe it is an idea to use the AlarmManager to schedule background-scans in deep sleep?

**Comment by eyeled** [comment]
@davidgyoung Could you please elaborate a bit how this is supposed to work?
When the AlarmManager wakes up the device it only will execute onReceive method of StartupBroadcastReceiver before going to deep sleep again.
From testing on 4.4.2 I can say that it in fact doesn't work with this approach.

**Comment by davidgyoung** [comment]
@eyeled, when the `StartupBroadcastReceiver` is triggered, if the app was not running prior, it triggers the regular app startup lifecycle.  That means that if your app has a custom `Application` class, its `onCreate` method will be fired, which is the recommended place for initializing the library's `RegionBootstrap` class.  If this is done, this will start scanning.

**Comment by eyeled** [comment]
@davidgyoung The case I'm talking about is when the app already is running in background (mBackgroundFlag is set to true) and the device wakes up from deep sleep due to the AlarmManager callback registered in CycledLeScanner.setWakeUpAlarm().
This is what the original issue is all about and the current implementation doesn't seem to have fixed the original bug.

**Comment by davidgyoung** [comment]
The library uses a combination of a Handler and and Alarm.  The Handler is the normal way of cycling scanning.  The Alarm is just used as a backup.   In deep sleep, the Handler firing will be delayed and will not fire while the app is in deep sleep.  When the Alarm goes off in deep sleep, it releases the hold on the Handler and it will fire shortly after the Alarm brings the app from deep sleep.

**Comment by eyeled** [comment]
What makes you assume that the operating system will execute anything other than the onReceive method when an alarm goes off?
Quote from the AlarmManager docs: "The Alarm Manager holds a CPU wake lock as long as the alarm receiver's onReceive() method is executing. This guarantees that the phone will not sleep until you have finished handling the broadcast. Once onReceive() returns, the Alarm Manager releases this wake lock. This means that the phone will in some cases sleep as soon as your onReceive() method completes."
From my logs I can only say that it doesn't work.
And even if it worked then the scanning interval in background would effectively go down to every 5 minutes which is not very useful. Cf. https://github.com/AltBeacon/android-beacon-library/issues/179

**Comment by sa0l** [comment]
for every one that will read this, use:
        beaconManager.setBackgroundScanPeriod(1000l);
            beaconManager.setBackgroundBetweenScanPeriod(5000l);

            beaconManager.updateScanPeriods();

that will scan for one second every 5 seconds.
