### ISSUE TITLE
Samsung S5 Can't Monitor Any Beacon

### ISSUE THREAD

**Issue by anindilla** [AltBeacon/android-beacon-library#216]
I have followed the tutorials from MobileFirst as follows:
1. https://developer.ibm.com/mobilefirstplatform/documentation/getting-started-7-0/advanced-topics/working-with-beacons/#registeringbeacons
2. https://developer.ibm.com/mobilefirstplatform/documentation/getting-started-7-0/advanced-topics/working-with-beacons/beacons-in-android/
using my Samsung Galaxy S5 phone in Android Lollipop

And I have issues as follows:
1. I have MPact Beacons with specifications that fulfill the requirements but my Samsung Galaxy S5 phone can't read the Beacon at all
2. The Beacon can be read using the Presence Insights Demo that IBM provides for me with my Samsung Galaxy S5 phone

Please answer it soon, I really appreciate it.

Best Regards,
Dilla Anindita
anindilla@gmail.com / 8adilla@id.ibm.com

**Comment by davidgyoung** [comment]
Please note that this forum is reserved for feature requests and reproducible bugs found with the library itself.  For help with developing applications with the library, please open a new question on StackOverflow.com.  

To save you time, I believe it is likely that you have not set up a BeaconParser as described in the "What kinds of beacons can be detected?" section of the document you referenced: https://developer.ibm.com/mobilefirstplatform/documentation/getting-started-7-0/advanced-topics/working-with-beacons/beacons-in-android/  Please see here for more info on how to resolve this:  https://github.com/AltBeacon/android-beacon-library/issues/13

If you have further questions please post them on StackOverflow.com.
