### ISSUE TITLE
Beacon library does not scale for multiple apps

### ISSUE THREAD

**Issue by TeunVR** [AltBeacon/android-beacon-library#22]
If multiple apps are using this library for beacon-detection in the background they will interfere with each others 5 minute schedule.
Worst case the device will continuously scan for beacons. 
A possible "solution" might be to have only one BeaconService running that all the apps will use (using a remote service with aidl?). However in this case the service must be deployed in a separate Beacon-app that the other apps depend on.
What are your thoughts about this?

**Comment by davidgyoung** [comment]
A change has been put into 2.1-beta2 to start scans at the same time across all apps using the library on a device by synchronizing on the system clock.

See here:  https://github.com/AltBeacon/android-beacon-library/blob/7570b33f2cbb081cef079c8189e17109f44e41fc/src/main/java/org/altbeacon/beacon/service/scanner/CycledLeScanner.java#L310-L329
