### ISSUE TITLE
Unable to detect Beacons on Micromax A190

### ISSUE THREAD

**Issue by kiledar2006** [AltBeacon/android-beacon-library#222]
Hello I am using AltBeacon library sample app, when i start ranging, it's not showing any beacon on Micromax A190 model, but it's working fine on Samsung, HTC, Lava & Motorola devices.

when i searched on google for this issue than i found only this link, according to this answer, Micromax have incomplete bluetooth stack that's why they are unable to detect beacons.

https://forums.estimote.com/t/estimote-does-not-detect-beacon-in-micromax-a106-any-advise/1170/5

can u please tell me why it's not working on Micromax. it's a Micromox issue aur it's a issue in your library???

**Comment by davidgyoung** [comment]
On the Micromax, please ensure BLE is enabled, set `beaconMangager.setDebug(true)` and collect a LogCat excerpt for 10 seconds where the app is not detecting beacons.   Please put a link to that LogCat excerpt as a Gist in this issue.

**Comment by joginder89** [comment]
I have the same issue and this is link 
https://gist.github.com/joginder89/f641567b64a3da1ea4e5

**Comment by davidhelms** [comment]
This model does not appear to come equipped with Bluetooth 4.0 support, which is a prerequisite

http://www.micromaxinfo.com/mobiles/smartphones/canvas/Canvas-HD-Plus-A190

**Comment by davidgyoung** [comment]
I agree, it looks like the specs for the Micromax A190 says it only has Bluetooth 3.0.  This is unusual for a modern phone, but means that this won't work with the library.
