### ISSUE TITLE
Beacon Exact Range for all Android Devices

### ISSUE THREAD

**Issue by kiledar2006** [AltBeacon/android-beacon-library#223]
Hello,

i am facing issues in Beacon Ranging, when i start ranging than it  gives range between 0 to 3.

but i want exact range in meters, can you pls tell me how to calculate the exact range in meters???

**Comment by davidgyoung** [comment]
You cannot get exact distance estimates due to radio noise.  See here for details: 

http://altbeacon.github.io/android-beacon-library/distance-calculations.html
