### ISSUE TITLE
Project Website is down for some reason

### ISSUE THREAD

**Issue by kbenja** [AltBeacon/android-beacon-library#225]
I am looking for some sort of tutorial on how to implement this in Android Studio. Thanks!

**Comment by davidgyoung** [comment]
Please note that this forum is reserved for feature requests and reproducible bugs with the library itself.  For help in using the library please post questions on StackOverflow.com

For the sake of expediency, I will note that you can find Android Studio quick start instructions here: http://altbeacon.github.io/android-beacon-library/configure.html  And a full reference application here:  https://github.com/AltBeacon/android-beacon-library-reference
