### ISSUE TITLE
how to find Near Beacons?

### ISSUE THREAD

**Issue by kiledar2006** [AltBeacon/android-beacon-library#227]
Hello,

i am using your library, & it's working fine, but in Ranging it's giving distance always between 0 to 3.

now my requirement is that i need only those beacons which is in 2 meter range. i tried to filter the beacons on basis of distance, but that distance is not exact distance. so i can't use this approach.

please suggest me a way to get the list of only those beacons which are in 2 meter range.

**Comment by davidgyoung** [comment]
Sorry, but ranging just isn't accurate enough to give you precise measurements.  Please read below for more info:

http://altbeacon.github.io/android-beacon-library/distance-calculations.html

http://developer.radiusnetworks.com/2014/12/04/fundamentals-of-beacon-ranging.html

If you have additional questions, please ask on StackOverflow.com
