### ISSUE TITLE
Unused parameter in BackgroundPowerSaver constructor

### ISSUE THREAD

**Issue by j1nj1** [AltBeacon/android-beacon-library#228]
BackgroundPowerSaver.java contains a constructor that accepts boolean parameter 'countActiveActivityStrategy', which is not used.

```
public BackgroundPowerSaver(Context context, boolean countActiveActivityStrategy) {
```

Is the intention to leave this here because there will be another strategy to determine if power saver mode should be entered? Otherwise, currently the flag has no effect.

**Comment by davidgyoung** [comment]
@j1nj1, you are correct that the parameter is unused.  It is a holdover from the merge of the Pro Android iBeacon Library 1.x codebase into the Android Beacon Library 2.0 codebase.  I have marked that constructor as deprecated in 73e4ede93d83cb687360f4d7cf6a50cf533600f7
