### ISSUE TITLE
update 2.3.1 seems to detect empty beacon list

### ISSUE THREAD

**Issue by Onheiron** [AltBeacon/android-beacon-library#231]
When synced gradle in my project to v2.3.1 I could no longer detect beacons in my office.

didRangeBeaconsInRegion is called, but beacons list is empty.

**Comment by davidgyoung** [comment]
OK ase try with the 2.3.2 release.  If you still have problems, please include any custom beacon parser expression with the issue, add the line beaconManager.setDebug(true) and attach a LogCat excerpt.  That will help find the problem.

**Comment by davidgyoung** [comment]
@Onheiron, this may be related to the issue described in #235 

Can you please answer the following:

* What type of beacons you are using?  Are they iBeacon transmitters or AltBeacon transmitters?  Who is the manufacturer?
* What type of mobile device are you using?

**Comment by davidgyoung** [comment]
Resolved in 2.3.3 
https://github.com/AltBeacon/android-beacon-library/releases/tag/2.3.3

**Comment by andretietz** [comment]
Happens to me on 2.9.1:
<img width="1320" alt="screen shot 2016-11-23 at 15 51 56" src="https://cloud.githubusercontent.com/assets/2174386/20566330/eba204bc-b194-11e6-91c7-b379c271917a.png">

**Comment by ealvaradogsg** [comment]
Hi Team, I have the same problem, i work with Estimote and we have the location proximity beacons. I use the 2+ version in my gradle. 

![image](https://user-images.githubusercontent.com/29046037/26908184-0c156f78-4bc7-11e7-89f3-3c2ea83baa53.png)

![image](https://user-images.githubusercontent.com/29046037/26908196-1b6074d2-4bc7-11e7-9e50-80e6bce0d828.png)

This issue have any solve in this community? 

My device: Huaweii p8 LTE: Android 5.1

Regards, thanks for all
