### ISSUE TITLE
How to create Eddystone beacon like AltBeacon in andorid  

### ISSUE THREAD

**Issue by Himanshu4003** [AltBeacon/android-beacon-library#246]
In Andorid i can create Beacon object like below 

````
Beacon beacon4 = new AltBeacon.Builder().setId1("DF7E1C79-43E9-44FF-886F-1D1F7DA6997A")
                    .setId2("1").setId3("4").setRssi(-55).setTxPower(-55).build();
````

How i can create Beacon object for Eddystone for 0x2f234454f4911ba9ffa6 as a namespace and 0BDB87539B67 as (6 bytes) Instance and set Eddystone url to this .

As idea how to set this all in Beacon of AltBeacon builder.

**Comment by davidgyoung** [comment]
@Himanshu4003, please post questions on how to use the library on StackOverflow.com, as this forum is reserved for feature requests and reports of bugs within the library itself.

To save you time, below is a working example.  If you have followup questions, please post on StackOverflow.com

    Beacon.Builder().setId1("0x2F234454F4911BA9FFA6").setId2("0x0BDB87539B67").setTxPower(-55).build();
