### ISSUE TITLE
Ranging for a specific beacon by Bluetooth address

### ISSUE THREAD

**Issue by mharper** [AltBeacon/android-beacon-library#253]
It'd be abundantly convenient to be able to create a `Region` given a Bluetooth hardware address.  Then when `startRangingBeaconsInRegion` is called, it only makes callbacks for a beacon with the given Bluetooth address.  This would be useful for ranging a beacon that is connectable and broadcasting multiple frame types since you'll get only a single scan result per scan per device and you don't know for certain which frame type you'll get!

**Comment by davidgyoung** [comment]
See #254
