### ISSUE TITLE
didExitRegion() called when device is in range of beacon. 

### ISSUE THREAD

**Issue by joginder89** [AltBeacon/android-beacon-library#255]
Library working almost good. Some time it called didDetermineStateForRegion() and give state 0, followed by didExitRegion() even when device is in range to beacon. These method called in both condition when application is in foreground as well as in background. After few (2-3) seconds didDetermineStateForRegion() again called and give state 1, followed by didEnterRegion() .

I am testing in Application class and have config

        backgroundPowerSaver = new BackgroundPowerSaver(this);
        beaconManager.setBackgroundScanPeriod(1100l);
        beaconManager.setBackgroundBetweenScanPeriod(5000l);
        beaconManager.setForegroundScanPeriod(1100l);
        beaconManager.setForegroundBetweenScanPeriod(5000l);
        beaconManager.setAndroidLScanningDisabled(true);

Can anybody tell me when didDetermineStateForRegion() method called ?

**Comment by davidgyoung** [comment]
Hi, @joginder89.  The didDetermineStateForRegion() gets called with 0 (outside region) whenever the library determines that the beacon is no longer visible (after a 10 second timeout.)  If you then see it get called with 1 (inside region) after 2-3 seconds, that indicates that the Android bluetooth scanner only saw two beacon packets separated by 12 -13 seconds.

This is most likely an issue with the beacon or the Android device.  Make sure the beacon is transmitting packets more than once every 10 seconds (preferably once per second or more).  Also check that your Android device can reliably detect bluetooth packets.  Some devices like the Nexus 7 2012 edition, Nexus 4, Moto G and Moto X do not reliably detect bluetooth signals when WiFi is turned on.

If you need more help, please open a new question on StackOverlflow.com, as this forum is reserved for feature requests and reproducible bugs with the library itself.
