### ISSUE TITLE
onBeaconServiceConnect not called after binding.

### ISSUE THREAD

**Issue by jcyu0208** [AltBeacon/android-beacon-library#259]
I am trying to monitor and range in the background using the Application class. I first use RegionBootstrap then once a region is entered, I bind the Application class as a consumer. However, the onBeaconServiceConnect is not called even though BeaconManager shows that I have been bound already.

If I repeat the same process inside an activity, it works.

Is there a way I can monitor and range in the background?

**Comment by davidgyoung** [comment]
Hi, @jcyu0208, I have just answered a very similar question [here](http://stackoverflow.com/a/31906180/1461050).   Please comment on that question on StackOverflow.com if that does not answer your question.
