### ISSUE TITLE
Cannot start transmitting but it used to work before

### ISSUE THREAD

**Issue by s4050883** [AltBeacon/android-beacon-library#261]
i got a problem with beacon transmitting but i used to make it work 2 days ago i didn't change anything in code but why it's not working here is my code for transmitting

public class MainActivity extends ActionBarActivity {
    private Button test, bleButton;
    private BluetoothAdapter mBTAdapter;
    private final String TAG = "MainActivity";
    private final static int REQUEST_ENABLE_BT = 1;
    private BeaconTransmitter mBeaconTransmitter;
    private BeaconParser mBeaconParser;
    private Beacon mBeacon;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        initElement();
        test.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startTransmit();
                Toast.makeText(MainActivity.this, "Broadcasted as 2f234454-cf6d-4a0f-adf2-f4911ba9ffa6", Toast.LENGTH_LONG).show();
            }
        });
    }

    private void initElement() {
        test = (Button) findViewById(R.id.button);
    }

    private void startTransmit() {
        Beacon beacon = new Beacon.Builder()
                .setId1("2f234454-cf6d-4a0f-adf2-f4911ba9ffa6")
                .setId2("1")
                .setId3("2")
                .setManufacturer(0x0118)
                .setTxPower(-59)
                .setDataFields(Arrays.asList(new Long[]{0l}))
                .build();
        BeaconParser beaconParser = new BeaconParser()
                .setBeaconLayout("m:2-3=beac,i:4-19,i:20-21,i:22-23,p:24-24,d:25-25");
        BeaconTransmitter beaconTransmitter = new BeaconTransmitter(getApplicationContext(), beaconParser);
        beaconTransmitter.startAdvertising(beacon);
    }
}

thanks in advance

**Comment by davidgyoung** [comment]
@s4050883, for help with using this library, please create a new question on StackOverflow.com.  This forum is reserved for feature requests and reproducible bugs with the library itself.

Before you open a question, please add a line to your code that calls ` beaconTransmitter.checkTransmissionSupported` and logs the result code it returns.  Please include that result code in your question.
