### ISSUE TITLE
App crashing when converting eddystone-identifier to int

### ISSUE THREAD

**Issue by stefansgit** [AltBeacon/android-beacon-library#273]
When trying to get the identifier as an int the app crashes.

The following code is used:

if (beacon.getServiceUuid() == 0xfeaa && beacon.getBeaconTypeCode() == 0x00) {
     Identifier instanceId = beacon.getId2();
      int id = instanceId.toInt()
}

**Comment by davidgyoung** [comment]
The code you mention is working as designed.  Per the method docs "throws java.lang.UnsupportedOperationException when value length is longer than 2".  

Although Java's int data type supports 32 bits, it is a signed number.  It therefore cannot hold a 6 byte eddystone instance identifier.
