### ISSUE TITLE
Customized beacons Background scan

### ISSUE THREAD

**Issue by acfield** [AltBeacon/android-beacon-library#278]
Hi, 
I would like my app uses monitoring to scan for customized beacons in background.
I followed all suggestion provided by AltBeacon, but it seems do not properly work.
I mean, didEnterRegion is called only when I install the app on my Nexus 7 and, quite rarely, after more than 6-7 minutes, even if I stress the app to scan in background with the same scan interval and scan window that it uses in foreground scan.

On the other hand, everything works if I use ranging in background.
It could solve my problem, but I would like to set wider scan interval and scan window, when the app runs in background, to save battery.
Is it possible to do that using ranging?

Thanks 
Andrea

**Comment by davidgyoung** [comment]
Understand that when you monitor for beacons, `didEnterRegion` is only supposed to be called once, the first time a beacon matching the region definition enters the range of the mobile device.  It is not supposed to be called a second time until all beacons matching the region disappear then one reappears.  If you want more updates, then ranging is the way to go.  You can adjust the scan intervals as needed to trade off responsiveness vs. battery savings.
