### ISSUE TITLE
Can you give any example to implement Region for multiple uuid,major and minor values

### ISSUE THREAD

**Issue by mstfchelik** [AltBeacon/android-beacon-library#279]
Hello guys, 

Im trying to implement multiple beacons with Region(String unique, List<Identifier>) code in Android app. But I could not understand how to create List<Identifier> variables by using uuid, major and minor. Can you please give me any sample code for it? 

Best Regards,

**Comment by davidgyoung** [comment]
@mstfchelik, for help on how to use rhis library, please open a question on StackOverflow.com.  This forum is reserved for feature requests and reproducible bug reports with the library itself.  

Happy to answer your question there.
