### ISSUE TITLE
It would be great to have opportunity to change the exit time

### ISSUE THREAD

**Issue by contrudar** [AltBeacon/android-beacon-library#281]
Right now we faced the problem that 10 seconds for exit time is low in real life. If a beacon is next to a phone, everything works well. But when you start walking around the exit happens very often, even though you are in the region. I would like to have possibility to chage exit time to 30 seconds like in iOS (or any other constant). Thanks in advance.

**Comment by davidgyoung** [comment]
I agree it is a good idea to make this configurable.  Would love a pull request if you or someone you know would like to put in the change

 (On iOS, however, the exit happens only 3 seconds after the beacon is last detected.  See http://developer.radiusnetworks.com/2014/03/12/ios7-1-background-detection-times.html )
