### ISSUE TITLE
Ranging callbacks always gives a collection of 1 beacon

### ISSUE THREAD

**Issue by jbarmanet** [AltBeacon/android-beacon-library#287]
Hi,

I posted [a stackoverflow question](http://stackoverflow.com/q/32636327/1720332) without much success, because with AltBeacon 2.5.1 the Ranging callbacks always give me a collection size of 1 beacon, even if I have let's say 4 beacons around, this collections returns me one of them randomly... is there an issue about this ? Or am I doing something wrong in my service ?

    public class MonitorService extends Service implements BeaconConsumer 
    {

    private BeaconManager beaconManager;

    @Override
    public void onCreate() 
    {
        super.onCreate();

        beaconManager = BeaconManager.getInstanceForApplication(this);
        beaconManager.getBeaconParsers().add(new BeaconParser().
                setBeaconLayout("m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24"));

        beaconManager.setForegroundScanPeriod(5000l);
        beaconManager.setBackgroundScanPeriod(5000l);
        beaconManager.setForegroundBetweenScanPeriod(1100l);
        beaconManager.setBackgroundBetweenScanPeriod(1100l);

        setupBeaconManager();
    }

    private void setupBeaconManager()
    {
        if (!beaconManager.isBound(this))
            beaconManager.bind(this);
    }

    private void unsetBeaconManager()
    {
        if (beaconManager.isBound(this))
        {
            beaconManager.unbind(this);

            try 
            {
                beaconManager.stopRangingBeaconsInRegion(new Region("apr", null, null, null));
            } 
            catch (RemoteException e) 
            {  
                Log.i(TAG, "RemoteException = "+e.toString());
            }
        }
    }

    @Override
    public void onBeaconServiceConnect() 
    {
        beaconManager.setRangeNotifier(new RangeNotifier() {
            @Override 
            public void didRangeBeaconsInRegion(Collection<Beacon> beacons, Region region) 
            {
                Log.i(TAG,"didRangeBeaconsInRegion, number of beacons detected = "+beacons.size());
                // HERE IT IS : the size is Always 1, but the beacon (UUID etc. can be different)
            }
        });

        try 
        {
            beaconManager.startRangingBeaconsInRegion(new Region("apr", null, null, null));
        } 
        catch (RemoteException e) 
        {  
            Log.i(TAG, "RemoteException = "+e.toString());
        }

    }

    @Override
    public void onDestroy() 
    {
        unsetBeaconManager();

        super.onDestroy();
    }

    }

**Comment by davidgyoung** [comment]
Thanks for posting your support question on StackOverflow.  I have replied there.
