### ISSUE TITLE
RegionBootstrap not working with Region(uniqueId, id1, null null)

### ISSUE THREAD

**Issue by axierjhtjz** [AltBeacon/android-beacon-library#292]
I´m trying to receive region notifications on the Application class for some regions defined by an unique id and id1 like this.
```java

public class DaoApplication extends Application implements BootstrapNotifier {

@Override
    public void onCreate() {
        super.onCreate();

        Boolean isBTAvailable = BluethootUtils.verifyBluetooth(this);

        if (isBTAvailable) {
            beaconManager = BeaconManager.getInstanceForApplication(this);

            beaconManager.getBeaconParsers().add(new BeaconParser().
                    setBeaconLayout("m:2-3=aabb,i:4-19,i:20-21,i:22-23,p:24-24,d:25-25"));
            beaconManager.getBeaconParsers().add(new BeaconParser().
                    setBeaconLayout("m:0-3=4c000215,i:4-19,i:20-21,i:22-23,p:24-24"));
            beaconManager.getBeaconParsers().add(new BeaconParser().
                    setBeaconLayout("m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24"));

            region  = new Region("backgroundRegion", Identifier.parse("61687109-905f-4436-91f8-e602f514c96d"), null, null);
            regionBootstrap = new RegionBootstrap(this, region);
            backgroundPowerSaver = new BackgroundPowerSaver(this);
        }
    }
}
```

This way I'm not getting updates on 
```java
@Override
    public void didEnterRegion(Region arg0)
```

But if I chage the region to ```new Region("backgroundRegion", null, null, null);``` I do.

Is there something I´m missing?

Thanks!

**Comment by davidgyoung** [comment]
@axierjhtjz, the preferred forum for assistance with using the library is to open a question StackOverflow.com.  This forum is reserved for feature requests and reproducible bugs with the library itself.  Please open a question there, (and include a log or screenshot of a scanning app that shows the actual UUID of your beacon as detected -- perhaps it is as simple as a single character being wrong in 61687109-905f-4436-91f8-e602f514c96d.)  I'll be happy to help in that forum.
