### ISSUE TITLE
Please update the device list

### ISSUE THREAD

**Issue by Aeyoun** [AltBeacon/android-beacon-library#302]
https://altbeacon.github.io/android-beacon-library/beacon-transmitter-devices.html

**Comment by jvadillo** [comment]
I am interested also in the devices list, are you going to upload any update?
Thankyou very much!

**Comment by davidgyoung** [comment]
Updated on October 13

**Comment by Aeyoun** [comment]
Much appreciated. :+1:

I believe people will be really interested in the Nexs 5X/6P which should start showing up in your data very soon. Would be nice with a monthly update.
