### ISSUE TITLE
Library unable to detect beacons of custom parsers after Marshmallow update

### ISSUE THREAD

**Issue by ankitgupta100** [AltBeacon/android-beacon-library#303]
My app uses altbeacon lib and is unable to detect custom parsers since I updated the OS to Marshmallow. There is no error in logcat too. I tried detecting them from Locate app too from a couple of Nexus 5 devices, but still not detecting. Are there any changes required ?

**Comment by evansgelist** [comment]
Perhaps the same problem
https://github.com/AltBeacon/android-beacon-library/issues/301

**Comment by ankitgupta100** [comment]
Looks so. Have tried out the same methods mentioned in that post. Same observations here too.

**Comment by ankitgupta100** [comment]
Devices are shown in Settings -> Bluetooth, but not detected in my app and Locate app. My app has FINE_LOCATION PERMISSION and all required Bluetooth permissions.

**Comment by davidgyoung** [comment]
@ankitgupta100,  I wonder if this problem is caused by an upgrade to 6.0 with apps that were already  installed for Android 5.0.  Can you try uninstalling the Locate app and re-installing it, to see if it starts detecting?

**Comment by davidgyoung** [comment]
This is a duplicate issue to #301.  Please add subsequent comments there.
