### ISSUE TITLE
The library is making my app freeze on Android 6.0 (Marshmallow)

### ISSUE THREAD

**Issue by FrancoSabadini** [AltBeacon/android-beacon-library#313]
When I start the app without starting the service that uses the beacons library it works well, but when I start the service the app has a lot of lag. This is only happening on Android 6.0 running on a Nexus 6. For other devices running Android 5.x it works well. Any idea what this could be?

**Comment by davidgyoung** [comment]
Can you try an unmodified copy of the reference app or the [Locate app](https://play.google.com/store/apps/details?id=com.radiusnetworks.locate&hl=en) and see if you see the same thing?

**Comment by fvink** [comment]
I've also experienced lag after denying location permission from the app. On Android Marshmallow, ACCESS_COARSE_LOCATION and ACCESS_FINE_LOCATION are needed for Bluetooth scanning in the background. If the permission is denied the app starts lagging and SecurityException will keep getting thrown.

**Comment by davidgyoung** [comment]
See here for instructions on adding the permissions check needed for Android 6 to your app.

    http://altbeacon.github.io/android-beacon-library/requesting_permission.html

**Comment by FrancoSabadini** [comment]
Thanks @davidgyoung and @fvink, adding the permission check made it work fine :).

**Comment by eckoj433** [comment]
I am having the same issue, however it persists despite asking for permissions. Is there some other permission that might be missing that is causing this lagg, except coarse_location?
