### ISSUE TITLE
Passing additional info via beacon

### ISSUE THREAD

**Issue by mkucherenko** [AltBeacon/android-beacon-library#319]
Is there a way to pass additional info(like string, or some kind of Map) when I host beacon using your lib? I tried to beacon.requestData(new BeaconDataNotifier()), but in Beacon.class:36 I see hadrcoded dataFactory:
protected static BeaconDataFactory beaconDataFactory = new NullBeaconDataFactory();

Is there a way to pass my custom data, when hosting beacon?

**Comment by davidgyoung** [comment]
Apologies for the tardy response.  Yes, it is possible to attach additional data to a beacon (stored on a server) using these extensions.  You can see an example service at http://proximitykit.radiusnetworks.com.
