### ISSUE TITLE
Use Android L BLE APIs when available

### ISSUE THREAD

**Issue by petedoyle** [AltBeacon/android-beacon-library#32]
We've been playing with iBeacons on iOS and Android and notice that iBeacons wake iOS devices pretty quickly (a couple seconds), even after long periods of inactivity/sleep, and without a huge battery life hit. 
I think Apple may have pushed iBeacon scanning into another chip such that the CPU could sleep while another chip constantly watches for iBeacons/BLE devices.

It _sounds_ like Android L might've added this (or something similar) as well, from this video:
https://www.google.com/events/io/io14videos/0b3fe228-89c5-e311-b297-00155d5066d7

And not just for iBeacons, but all BLE scanning.  It looks like the new APIs are in the `android.bluetooth.le` package, especially `BluetoothLeScanner#startScan (List<ScanFilter> filters, ScanSettings settings, ScanCallback callback)`.  `ScanSettings` supports a `ScanMode` property which can be set to one of:
- `SCAN_MODE_BALANCED`: Perform Bluetooth LE scan in balanced power mode.
- `SCAN_MODE_LOW_LATENCY`: Scan using highest duty cycle. It's recommended only using this mode when the application is running in foreground.
- `SCAN_MODE_LOW_POWER`: Perform Bluetooth LE scan in low power mode. This is the default scan mode as it consumes the least power.

Here's the API of ScanFilter.Builder():

![screenshot 2014-09-17 10 56 51](https://cloud.githubusercontent.com/assets/68218/4308570/131e6132-3e94-11e4-90c7-fdb60e61e634.png)

**Comment by morenocruzf** [comment]
Hello guys, 

Does it work with WearOS?? Looks like exactly what I need.
I am having a hard time searching if WearOS is able of scanning BLE broadcast (or beacon) packets without a mobile nearby. 

Thanks in advance!
BR
Fernando

**Comment by davidgyoung** [comment]
Sorry.  WearOS does not support BLE scanning in the watch itself.  The watch’s BLE function is limited to advertising itself for connection by a paired phone.  This means no onboard scanning.

**Comment by morenocruzf** [comment]
> Sorry. WearOS does not support BLE scanning in the watch itself. The watch’s BLE function is limited to advertising itself for connection by a paired phone. This means no onboard scanning.

Thank you David for you fast response!
What about receiving simple broadcast BLE packets? I mean, not exactly referring to beacons (terminology here might be confusing sometimes). 
I have read that the first versions of WearOS didn't support it but nowadays it's possible.
