### ISSUE TITLE
didRangeBeaconsInRegion called more then

### ISSUE THREAD

**Issue by Gehlot** [AltBeacon/android-beacon-library#321]
i have problem of beacon repeatedly called.i have call didRangeBeaconsInRegion(Collection<IBeacon> iBeacons,Region region).in this method is dynamically change by iBeacons.size() sometime showing 1 somtetime 0.then in case of 1 i am check-in working fine.but in few moment it showing size =0 means beacon is not detected ,i am doing check out functionality on this.getting called . whenever i am very close to beacon.why it is not showing stable count.how to overcome this.

**Comment by davidgyoung** [comment]
@Gehlot , for help with using this Library, please post a new question on Stackoverflow.com.  this forum is reserved for feature requests and reproducible bug reports with the library itself.

In your question on StackOverflow.com, please include the following:
1. Android device model you are using
2. OS version
3. Beacon model
4. Beacon advertising rate, if known
