### ISSUE TITLE
D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=7

### ISSUE THREAD

**Issue by iDuke** [AltBeacon/android-beacon-library#322]
Dont scan beacons. For some reason. 

D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=7

setBeaconLayout("**REDACTED**"));

**Comment by davidgyoung** [comment]
Sorry, I had to redact this question because it contained proprietary beacon layout information.    If you still need help getting the library to detect your beacons, please post a question on Stackoverflow.com.
