### ISSUE TITLE
XT1115

### ISSUE THREAD

**Issue by lvwanjun** [AltBeacon/android-beacon-library#325]
Meters  RSSI
0.25    -41
0.5     -43
1       -49
2       -65
3       -58
4       -57
5       -67
6       -67
7       -77
8       -70
9       -69
10      -75
12      -72
14      -72
16      -78
18      -83
20      -81
25      -81
30      -75
40      -83

Android device:
version: 5.0.2
build_number: LXG22.67-7.1
model: Moto X Pro
manufacturer: XT1115

Beacon Info:
RadBeacon Tag
Advertisements per second: 10
Transmit Power: Max

IPhone 5s Average RSSI @1m: -51

**Comment by davidgyoung** [comment]
Implemented in #330
