### ISSUE TITLE
How to load a Maven dependency

### ISSUE THREAD

**Issue by ftp27** [AltBeacon/android-beacon-library#33]
It would be nice if I could include your library through maven

**Comment by davidgyoung** [comment]
A 2.1-beta snapshot build is now on bintray, thanks to @pieces029: https://bintray.com/altbeacon/android/android-beacon-library/

Once 2.1 is out of beta this will be the preferred means of distribution

**Comment by aat-antoine** [comment]
If you can publish 2.0 stable, you'll be a lord :)

**Comment by davidgyoung** [comment]
2.1.1 is now available on Maven, thanks @pieces029
