### ISSUE TITLE
How to transfer data between two Android devices using Beacon?

### ISSUE THREAD

**Issue by Deeptiman** [AltBeacon/android-beacon-library#350]
I asked one question few days back in Stackoverflow. So , i want to know can i solve my issue using android-beacon-library.

Link  : http://stackoverflow.com/questions/35937529/how-to-transfer-data-between-two-android-devices-using-beacon/

Please let me know.

**Comment by zakjut** [comment]
Beacons do not really work this way. They are largely one way. Transmitting a specific frame over and over again, which receivers can pick up and perform some action depending on what they see. If you want to transmit data from device A, to device B using a bluetooth "relay" as you show in your image, beacons are not what you are looking for.

**Comment by Deeptiman** [comment]
@zakjut Thank you so much , it's clear my confusion about BLE devices.

**Comment by Francagir** [comment]
So, if you need to "get" data from a Beacon (connected to a API REST), located in a specific place(the Beacon), how could I? The moment it connects to do the query?

**Comment by davidgyoung** [comment]
Simply call the API to fetch the data for the detected beacon identifier as soon as the beacon is detected

**Comment by Francagir** [comment]
Thnx! And could I assign a specific location in a big place such a full city?

**Comment by Francagir** [comment]
Thnx @davidgyoung!
