### ISSUE TITLE
Not able to find c2540 and c2541 with android-beacon-library

### ISSUE THREAD

**Issue by rkInfotech** [AltBeacon/android-beacon-library#359]
protected void onCreate(Bundle savedInstanceState) {
    private BeaconManager beaconManager = BeaconManager.getInstanceForApplication(this);

        beaconManager.getBeaconParsers().clear();
    beaconManager.getBeaconParsers().add(new BeaconParser().
                setBeaconLayout("m:0-3=4c000215,i:4-19,i:20-21,i:22-23,p:24-24"));
        beaconManager.getBeaconParsers().add(new BeaconParser().
                setBeaconLayout("x,s:0-1=feaa,m:2-2=20,d:3-3,d:4-5,d:6-7,d:8-11,d:12-15"));
        beaconManager.getBeaconParsers().add(new BeaconParser().
                setBeaconLayout("s:0-1=feaa,m:2-2=00,p:3-3:-41,i:4-13,i:14-19"));
        beaconManager.getBeaconParsers().add(new BeaconParser().
                setBeaconLayout("s:0-1=feaa,m:2-2=10,p:3-3:-41,i:4-20v"));
        beaconManager.getBeaconParsers().add(new BeaconParser().
                setBeaconLayout("s:0-1=fed8,m:2-2=00,p:3-3:-41,i:4-21v"));

        beaconManager.bind(this);
    }

Here Only HM-10 Device show. Beacon device and any other device can not able see.

**Comment by davidgyoung** [comment]
For assistance with getting specific beacon devices detected using the library, please open a new question on StackOverflow.com.  This forum is reserved for feature requests and reproducible bug reports with the library itself.  

In advance of creating a question on StackOverflow.com, it may be helpful to test detecting the beacons with an off-the-shelf detector app based on this library like [Locate](https://play.google.com/store/apps/details?id=com.radiusnetworks.locate&hl=en)  If you are trying to detect custom hardware, it may be useful to record the bytes they are transmitting using a BLE packet sniffer.  Results of these tests can be included in the question on StackOverflow.com.
