### ISSUE TITLE
How to add UUID in android-beacon-library.

### ISSUE THREAD

**Issue by rkInfotech** [AltBeacon/android-beacon-library#360]
Here are snippet code to try add UUID with Region.

     @Override
        public void onBeaconServiceConnect() {
            beaconManager.setRangeNotifier(new RangeNotifier() {
                @Override
                public void didRangeBeaconsInRegion(Collection<Beacon> beacons, Region region) {
                   if (beacons.size() > 0) {
                        //EditText editText = (EditText)RangingActivity.this.findViewById(R.id.rangingText);
                       Beacon firstBeacon = beacons.iterator().next();
                       //logToDisplay("The first beacon " + firstBeacon.toString() + " is about " +     firstBeacon.getDistance() + " meters away.");

                    logToDisplay("Name : " + firstBeacon.getBluetoothName() + "\nAddress : " + firstBeacon.getBluetoothAddress() + "\nRssi : " + firstBeacon.getRssi() + "\nDistance :  " + firstBeacon.getDistance() + " \n\n");
                    //Toast.makeText(RangingActivity.this, "The first beacon " + firstBeacon.toString() + " is about " + firstBeacon.getDistance() + " meters away.", Toast.LENGTH_SHORT).show();
                }
            }

        });

        beaconManager.setMonitorNotifier(new MonitorNotifier() {
            @Override
            public void didEnterRegion(Region region) {
                Log.d("TAG", "I just saw an beacon for the first time!");
                Log.d("TAG", "Region id - " + region.getUniqueId());

            }

            @Override
            public void didExitRegion(Region region) {

                Log.d("TAG", "I no longer see a beacon");
                Log.d("TAG", "Region id - " + region.getUniqueId());
            }

            @Override
            public void didDetermineStateForRegion(int state, Region region) {
            }
        });

        try {
            Identifier identifier = Identifier.parse("E2C56DB5-DFFB-48D2-B060-D0F5A71096E0"); //beacon 1
            Identifier identifier2 = Identifier.parse("F7826DA6-4FA2-4E98-8024-BC5B71E0893E"); //beacon 2

            Identifier identifier3 = Identifier.parse("0000180d-0000-1000-8000-00805f9b34fb");
            Identifier identifier4 = Identifier.parse("0000180a-0000-1000-8000-00805f9b34fb");
            // Sample Characteristics.
            Identifier identifier5 = Identifier.parse("00002a29-0000-1000-8000-00805f9b34fb");

            Identifier identifier6 = Identifier.parse("0000ffe0-0000-1000-8000-00805f9b34fb");
            Identifier identifier7 = Identifier.parse("00002a37-0000-1000-8000-00805f9b34fb");

            beaconManager.startRangingBeaconsInRegion(new Region("myRangingUniqueId", null, null, null));
            beaconManager.startMonitoringBeaconsInRegion(new Region("identifier", identifier, null, null));
            beaconManager.startMonitoringBeaconsInRegion(new Region("identifier2", identifier2, null, null));
            beaconManager.startMonitoringBeaconsInRegion(new Region("identifier3", identifier3, null, null));
            beaconManager.startMonitoringBeaconsInRegion(new Region("identifier4", identifier4, null, null));
            beaconManager.startMonitoringBeaconsInRegion(new Region("identifier5", identifier5, null, null));
            beaconManager.startMonitoringBeaconsInRegion(new Region("identifier6", identifier6, null, null));
            beaconManager.startMonitoringBeaconsInRegion(new Region("identifier7", identifier7, null, null));

        } catch (RemoteException e) {
        }
    }

Is this is perfact method to add UUID ?
If not then let me know how to add UUID in beacon.

I am adding UUID because device not found with this library. So, i add manually add UUID.

**Comment by davidgyoung** [comment]
Hi, @rkInfotech.  For support questions like this, please open a new question on Stackoverflow.com as this forum is reserved for feature requests and reporting reproducible bugs with the library itself.  Make sure you have a [beacon layout set for your beacon](http://stackoverflow.com/a/26933713/1461050), and if that does not help, open a new question on StackOverflow.com.
