### ISSUE TITLE
add/remove regions from RegionBootstrap

### ISSUE THREAD

**Issue by aristide** [AltBeacon/android-beacon-library#366]
Hi @davidgyoung  !! is there any way of add or remove a monitored region from a running RegionBoostrap class. 

I saw your [answer](http://stackoverflow.com/a/30099289) where you suggested to use beaconManager. But  nn RegionBootstrap.java, i was looking for methods like
**addRegsion(Region region)/ removeRegion(Region region)** that can ease adding and removing operations.

thanks!!

**Comment by davidgyoung** [comment]
Understood.  I'll mark this as a feature request as it seems like a reasonable ask.  If you'd like to take a short at implementing it yourself, I'd welcome a pull request.

**Comment by aristide** [comment]
@davidgyoung 
my pull request #368

**Comment by davidgyoung** [comment]
Implemented in #368
