### ISSUE TITLE
Not able to transmit advertisement using beaconTransmitter ..

### ISSUE THREAD

**Issue by arpitjoshi08** [AltBeacon/android-beacon-library#367]
hello sir ,  i am using this code for transmitting beacon and use other device for detection but my code not working. Is there any issue in this code plzz check..  
       Beacon beacon = new Beacon.Builder()
                            .setId1("2f234454-cf6d-4a0f-adf2-f4911ba9ffa6") // UUID for beacon
                            .setId2("1") // Major for beacon
                            .setId3("5") // Minor for beacon
                            .setManufacturer(0x0118) // Radius Networks.0x0118  Change this for other beacon layouts//0x004C for iPhone
                            .setTxPower(-76) // Power in dB
                            .setDataFields(Arrays.asList(new Long[]{0l})) // Remove this for beacon layouts without d: fields
                            .build();

                    BeaconParser beaconParser = new BeaconParser()
                            .setBeaconLayout("m:2-3=beac,i:4-19,i:20-21,i:22-23,p:24-24,d:25-25");

                    beaconTransmitter = new BeaconTransmitter(getApplicationContext(), beaconParser);
                    beaconTransmitter.startAdvertising(beacon, new AdvertiseCallback() {

                        @Override
                        public void onStartFailure(int errorCode) {
                            Log.e("TAG", "Advertisement start failed with code: " + errorCode);
                            Toast.makeText(getApplicationContext(), "fail",Toast.LENGTH_LONG).show();
                        }

                        @Override
                        public void onStartSuccess(AdvertiseSettings settingsInEffect) {
                            Log.i("TAG", "Advertisement start succeeded.");
                            Toast.makeText(getApplicationContext(), "true",Toast.LENGTH_LONG).show();
                        }
                    });

**Comment by davidgyoung** [comment]
@arpitjoshi08, for help using this library, please open a question on StackOverflow.com, as this forum is reserved for feature request and reproducible bug reports with the library itself.  In your question, please describe what happens when you start transmitting (whether the success or failure callbacks get made) and describe what device model you are using and whether it is on this list:   http://altbeacon.github.io/android-beacon-library/beacon-transmitter-devices.html
