### ISSUE TITLE
getting ArrayoutofBound Exception when transmit advertisement.. 

### ISSUE THREAD

**Issue by arpitjoshi08** [AltBeacon/android-beacon-library#370]
hello sir , i am trying to transmit beacons but getting Arrayoutofbound Exception on this line plsss help.. beaconTransmitter.startAdvertising(beacon, new AdvertiseCallback() 
and tell me one more thing that, what is the use of     .setDataFields() and what type of value need to put in this field?

**Comment by davidgyoung** [comment]
@arpitjoshi08, for help using this library, please open a new question on StackOverflow.com.  This forum is reserved for feature requests and reproducible bug reports with the library itself.  In your question, please include the code you use to set up transmission and show the full stack trace of the error message.
