### ISSUE TITLE
2.8.1 causes app to freeze when adding Regions to monitor

### ISSUE THREAD

**Issue by marwfair** [AltBeacon/android-beacon-library#383]
When creating several hundred Regions and starting to monitor them, the app freezes for a minute, usually longer. This is happening every time and have tested this on several devices. This is happening with 2.8.1, but works fine with 2.7. When the app freezes, I see memory spikes in my memory monitor. When the app unfreezes, everything works fine. I didn't notice a problem when testing with 20 or so regions. When testing with 300 regions, there is definitely an issue.

**Comment by davidgyoung** [comment]
Thanks for this report, @marwfair.  I suspect the reason this is happening is that as of version 2.8, the library persists its monitored regions to a file to prevent spurious entry events across an app restart.  This probably is not performant for such a large number of regions.  

A few possible solutions:  (1) optimize the file persistence when starting to monitor a large number of regions.  (2) only persist a limited number of regions (3) allow disabling this persistence.    I want to add the third option for other reasons as well.

On a related note, aside from this issue, I am curious to hear how the library performs monitoring so many regions -- I have not tested it with this big of a number.

**Comment by marwfair** [comment]
@davidgyoung The library seems to perform pretty well with lots of beacons. I just had a few issues with 2.7 not wanting to scan, especially after the app is resumed. That issue seemed to had been fixed in 2.8.1, but because of the app freezing, I had to use 2.7.

**Comment by permutohedron** [comment]
Hi. The Monitoring status persistence can be disabled right now. Just call

`MonitoringStatus.getInstanceForApplication(applicationContext).stopStatusPreservationOnProcessDestruction();`

**Comment by davidgyoung** [comment]
Fixed in #405

**Comment by davidgyoung** [comment]
Released in 2.9
