### ISSUE TITLE
background scan configuration problems

### ISSUE THREAD

**Issue by parthrparekh93** [AltBeacon/android-beacon-library#391]
Hi, 

I am using Android beacon library version 2.8.1
I first set background scan period as 1.1 seconds and background between scan period was default 5 minutes. I used to get notification after 5 minutes for every scan or it missed rarely due to very low scan period of 1.1 seconds. Now, when I keep background scan period as 10 seconds and background between scan period as 60 seconds, I do not get a notification. From the logs, I can see that it scans every minute for a duration of 10 seconds but never gives me a notification. Any idea why I am facing such a problem?

Thanks

**Comment by davidgyoung** [comment]
There is no known issue that would cause this behavior unless the beacon is advertising at a rate less than once every 10 seconds such that its transmissions are always missed by the scan cycle.  A more likely explanation is that there is some other application or device-specific factor that is causing this.  To figure out which one might be the case, please open a question with any additional relevant details you can think of, as this forum is reserved for feature requests and reproducible bug reports with the library itself.  If investigation reveals a library-specific bug, we can open a new issue in this forum.
