### ISSUE TITLE
Implement didRangeBeaconsInRegion method in application class

### ISSUE THREAD

**Issue by arpitjoshi08** [AltBeacon/android-beacon-library#397]
` @Override
    public void didRangeBeaconsInRegion(Collection<Beacon> beacons, Region region) {
        if (beacons.size() > 0) {
            Beacon firstBeacon = beacons.iterator().next();
            if (BuildConfig.DEBUG) Log.d(TAG, "Beacon ranged: UUID: "
                    + firstBeacon.getId1().toString() + " Major: "
                    + firstBeacon.getId2().toString() + " Minor: "
                    + firstBeacon.getId3().toString());

            // Do something with the result

            // Stop ranging
            try {
                beaconManager.stopRangingBeaconsInRegion(region);
            } catch (RemoteException e) {
                e.printStackTrace();
            }
        }
    }`
i want to add this method in application class because i dont want to add other background services and also dont want to implement in activity class. because after destroy of activity it will not work so how is it possible in application class this code?
and is it possible to implement BeaconConsumer in application class?

**Comment by davidgyoung** [comment]
Please open this question on StackOverflow.com, as that is the preferred forum for help requests for how to use this library.  This forum is reserved for feature request and reproducible bug reports with the library itself.
