### ISSUE TITLE
Connect with iBeacons (write/read)

### ISSUE THREAD

**Issue by aserrin55** [AltBeacon/android-beacon-library#400]
I have read that it is possible to monitor iBeacons but, is there any way to connect with them and write data? (for example, change the uuid, major, minor..).
I've done scanning work properly and all the needed devices appear.
Thanks

**Comment by davidgyoung** [comment]
While many beacon vendors support BLE connections to configure their beacons, there is no universal standard -- each beacon manufacturer has a different way of configuring a beacon, and often it varies from one model to the next.  This library is not designed for beacon configuration.  Your best bet is to look for an app or SDK supplied by your beacon vendor.
