### ISSUE TITLE
getting null value in didEnter and didExitRegion 

### ISSUE THREAD

**Issue by arpitjoshi08** [AltBeacon/android-beacon-library#404]
`public class App extends Application implements BootstrapNotifier, BeaconConsumer {
    private static final String TAG = "BeaconReferenceApp";
    private RegionBootstrap regionBootstrap;
    private BackgroundPowerSaver backgroundPowerSaver;
    private boolean haveDetectedBeaconsSinceBoot = false;
    BeaconManager beaconManager;
    Region region;
    @Override
    public void onCreate() {
        super.onCreate();
       
        beaconManager = org.altbeacon.beacon.BeaconManager.getInstanceForApplication(this);
        beaconManager.getBeaconParsers().add(new BeaconParser().setBeaconLayout("m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24"));
        Log.d(TAG, "setting up background monitoring for beacons and power saving");
        region = new Region("backgroundRegion",
                null, null, null);
        regionBootstrap = new RegionBootstrap(this, region);
        backgroundPowerSaver = new BackgroundPowerSaver(this);
        beaconManager.setBackgroundScanPeriod(2000l);
        beaconManager.setBackgroundBetweenScanPeriod(2000l)
    }
    @Override
    public void didEnterRegion(Region arg0) {
        // In this example, this class sends a notification to the user whenever a Beacon
        // matching a Region (defined above) are first seen.
        try {
            beaconManager.startRangingBeaconsInRegion(arg0);

            Log.d("enter beacon", "" + arg0);

        } catch (RemoteException e) {
            if (BuildConfig.DEBUG)
                Log.d(TAG, "Can't start ranging");
        }
    }

    @Override
    public void didExitRegion(Region region) {
        Log.d( "didExitRegion", "" + region);

    }

    @Override
    public void didDetermineStateForRegion(int state, Region region) {

    }

  

    @Override
    public void onBeaconServiceConnect() {
        beaconManager.setMonitorNotifier(new MonitorNotifier() {
            @Override
            public void didEnterRegion(Region region) {
                try {
                    Log.d(TAG, "didEnterRegion");
                    beaconManager.startRangingBeaconsInRegion(region);
                } catch (RemoteException e) {
                    e.printStackTrace();
                }
            }
            @Override
            public void didExitRegion(Region region) {
                try {
                    Log.d(TAG, "didExitRegion");
                    beaconManager.stopRangingBeaconsInRegion(region);
                } catch (RemoteException e) {
                    e.printStackTrace();
                }
            }
            @Override
            public void didDetermineStateForRegion(int i, Region region) {
            }
        });
        beaconManager.setRangeNotifier(new RangeNotifier() {
            @Override
            public void didRangeBeaconsInRegion(final Collection<Beacon> beacons, Region region) {
                String valuesAll = "";
                for (Beacon oneBeacon : beacons) {
                    Log.d(TAG, "distance: " + oneBeacon.getDistance() + " id:" + oneBeacon.getId1() + "/" + oneBeacon.getId2() + "/" + oneBeacon.getId3() + "MAC :" +
                            oneBeacon.getBluetoothAddress() + "Bletooth name  ====" + oneBeacon.getBluetoothName());
                               }
            }
        });
        try {
            beaconManager.startMonitoringBeaconsInRegion(region);
        } catch (RemoteException e) {
            e.printStackTrace();
        }
    }`
i am using this but getting null id1 , id2, id3 and all on line public void didExitRegion(Region region)  and public void didEnterRegion(Region region) , what am i doing wrong please help

**Comment by davidgyoung** [comment]
This is as expected.  The identifiers are null in the callback because they are null in the monitored region: `region = new Region("backgroundRegion", null, null, null);`  You may wish to use ranging APIs to get the identifiers of the actual beacons detected.

If you need more help, please open a question on StackOverflow.com.  This forum is reserved for feature requests and reproducible bug reports with the library itself.
