### ISSUE TITLE
didEnter and didExit calling many times 

### ISSUE THREAD

**Issue by arpitjoshi08** [AltBeacon/android-beacon-library#406]
public class App extends Application implements BootstrapNotifier {

    private RequestQueue mRequestQueue;
    private ImageLoader mImageLoader;
    public static boolean ISFROM_SEARCH = false;

    public static boolean isActivityVisible() {
        return activityVisible;
    }

    public static void activityResumed() {
        activityVisible = true;
    }

    public static void activityPaused() {
        activityVisible = false;
    }

    private static boolean activityVisible;
    public static eApp instances;

    private static final String TAG = "BeaconReferenceApp";
    private RegionBootstrap regionBootstrap;
    private BackgroundPowerSaver backgroundPowerSaver;
    private boolean haveDetectedBeaconsSinceBoot = false;
    BeaconManager beaconManager;
    Region region;

    boolean checkValue = false;

    @Override
    public void onCreate() {

        super.onCreate();
        instances = this;
        beaconManager = org.altbeacon.beacon.BeaconManager.getInstanceForApplication(this);

        beaconManager.getBeaconParsers().add(new BeaconParser().setBeaconLayout("m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24"));

        Log.d(TAG, "setting up background monitoring for beacons and power saving");
        region = new Region("backgroundRegion",
                null, null, null);

        regionBootstrap = new RegionBootstrap(this, region);
        backgroundPowerSaver = new BackgroundPowerSaver(this);
        beaconManager.setBackgroundScanPeriod(1100l);
        beaconManager.setBackgroundBetweenScanPeriod(3000l);

        Fabric.with(this, new Crashlytics());
        // UNIVERSAL IMAGE LOADER SETUP

    }

    public static App getInstances(Context context) {
        if (instances == null) {
            instances = new App();
        }
        return instances;
    }

    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }

    @Override
    public void didEnterRegion(Region arg0) {
    
        Utils.notifyUser(getApplicationContext(), "Beacon in range");
    
        beaconManager.setRangeNotifier(new RangeNotifier() {
            @Override
            public void didRangeBeaconsInRegion(final Collection<Beacon> beacons, Region region) {
                String valuesAll = "";

                    for (Beacon oneBeacon : beacons) {

                        if (oneBeacon.getId2() != null && oneBeacon.getId3() != null) {
                }

                    }
          
                }

               /* }*/
            }
        });

        try {
           /* beaconManager.startMonitoringBeaconsInRegion(region);*/
            beaconManager.startRangingBeaconsInRegion(region);
        } catch (RemoteException e) {
            e.printStackTrace();
        }
    }

 
            @Override
            public void onError(byte methodName, Object obj) {
                Log.d("response message", "error");
                checkValue = false;
            }
        }, BeaconMessageBean.class, AppConstants.DIALOG_NOT_SHOW, AppConstants.IS_NOT_INSERTIN_DB, null);

    }

    @Override
    public void didExitRegion(Region arg) {

        try {
      
            beaconManager.stopRangingBeaconsInRegion(region);
        } catch (Exception e) {

        }
        Utils.notifyUser(getApplicationContext(), "Beacon out of range");
    }

    @Override
    public void didDetermineStateForRegion(int state, Region region) {

    }
  

}

`
I am using this application class for detect enter or exit in beacon and in enter region I am using ranging method for getting the detail of beacon but didEnter and didExit method calling many times when the beacon is not in range, what am I doing wrong ?Please help.
 i also opend this question on stackioverflow but dint get any answer till yet .

**Comment by davidgyoung** [comment]
Please open questions on how to use this library on StackOverflow.com.  This forum is reserved for feature requests and reproducible bug reports with the library itself.
