### ISSUE TITLE
Altbeacon not working properly

### ISSUE THREAD

**Issue by arpitjoshi08** [AltBeacon/android-beacon-library#408]
i am using this library for detect beacon but it scanning many times iam not understanding issue . i enter in region and then its continuous printing this log
07-28 12:20:59.280  20262-20980/com.example.hady.altbeacons10 D/BeaconsEverywhere﹕ didExitRegion
07-28 12:21:18.527  20262-21289/com.example.hady.altbeacons10 D/BeaconsEverywhere﹕ didEnterRegion
07-28 12:22:53.912  20262-22247/com.example.hady.altbeacons10 D/BeaconsEverywhere﹕ didExitRegion
07-28 12:23:21.007  20262-22548/com.example.hady.altbeacons10 D/BeaconsEverywhere﹕ didEnterRegion
07-28 12:23:48.213  20262-22768/com.example.hady.altbeacons10 D/BeaconsEverywhere﹕ didExitRegion
07-28 12:23:49.187  20262-22775/com.example.hady.altbeacons10 D/BeaconsEverywhere﹕ didEnterRegion
07-28 12:24:00.291  20262-22916/com.example.hady.altbeacons10 D/BeaconsEverywhere﹕ didExitRegion
07-28 12:24:02.247  20262-22929/com.example.hady.altbeacons10 D/BeaconsEverywhere﹕ didEnterRegion
07-28 12:24:24.439  20262-23143/com.example.hady.altbeacons10 D/BeaconsEverywhere﹕ didExitRegion
what should i do?
 i am using this beacon `https://www.alibaba.com/product-detail/16-bluetooth-beacon-eddystone-ti-cc2451_60321271979.html`

**Comment by davidgyoung** [comment]
Please open questions on how to use this library on StackOverflow.com.  This forum is reserved for feature requests and reproducible bug reports with the library itself.
