### ISSUE TITLE
In didEnterRegion() I cannot find beacon's UUID and MAC address ? I want UUID and Mac address only one time when it is entered into region.

### ISSUE THREAD

**Issue by ghost** [AltBeacon/android-beacon-library#439]

**Comment by davidgyoung** [comment]
Please ask general questions on how to use this library on StackOverflow.com, as this forum is reserved for feature requests and reporting bugs with the library itself.

Note also that there is an answer to this question here: http://stackoverflow.com/questions/39849297/how-can-i-get-beacons-data-uuid-major-minor-in-didenterregion-in-altbeacon/39862717#39862717
