### ISSUE TITLE
Beacon ranging stop when app killed from background

### ISSUE THREAD

**Issue by arpitjoshi08** [AltBeacon/android-beacon-library#442]
i am using
 1) Micromax Q427 Android 6.0
2) LYF LS-5010 Android 5.1.1
3) Micromax E311 Nitro Android 4.4.2 
device for beacon detect its working fine when app in foreground but when app killed from background ranging stop and not detecting beacon. i also used BootstrapNotifier for background detection.

**Comment by davidgyoung** [comment]
@arpitjoshi08, this is a common issue.  Please see this document that describes the limitations:  http://altbeacon.github.io/android-beacon-library/resume-after-terminate.html

If you still have trouble, please open a new question on StackOverflow.com and post a copy of your code that sets this up.  Note that that is the proper forum for support requests for using the library.
