### ISSUE TITLE
Parsing Estimote Sensors (Temperature, AmbientLight, etc) usinh AltBeacon Library

### ISSUE THREAD

**Issue by vaskanas** [AltBeacon/android-beacon-library#449]
Could you please any info how to parse estimote sensor values using the library?
For the temperature you can see here: 
http://stackoverflow.com/questions/33387603/android-beacon-library-eddystone-telemetry-temperature

**Comment by davidgyoung** [comment]
StackOverflow.com or an Estimote support forum is a better place for this question, as this forum is reserved for feature requests and bugs with the library itself.
