### ISSUE TITLE
didEnterRegion,  didExitRegion, didDetermineStateForRegion, didRangeBeaconsInRegion - are they called from the UI thread or from a background thread?

### ISSUE THREAD

**Issue by mmarshak** [AltBeacon/android-beacon-library#457]
I read the thread - https://github.com/AltBeacon/android-beacon-library/issues/148, and it is not clear are the call backs are called on the main/UI thread or some worker thread/background thread?
I plan to do a network access upon region detection and want to know if I should start a new Thread for that or I can do the network access from inside the callbacks?

**Comment by davidgyoung** [comment]
Callbacks are not guaranteed to be on the UI thread.  If modifying the UI, you need to wrap code in an appropriate block that guarantees running on the UI thread.

**Comment by mmarshak** [comment]
Thank you for the answer
