### ISSUE TITLE
Android 6.0 error

### ISSUE THREAD

**Issue by Omur100** [AltBeacon/android-beacon-library#465]
I have android 6.0 phone. Don't see beacon. I am getting the error "
I / BluetoothLeScanner: startRegisteration: mLeScanClients = {org.altbeacon.beacon.service.scanner.CycledLeScannerForLollipop $ 4 @ 5445b45 = android.bluetooth.le.BluetoothLeScanner $ BleScanCallbackWrapper @ d9ce5fa}."
Can you help me?

**Comment by davidgyoung** [comment]
This is not an error.   It is an informational message and is normal.  If you are having trouble getting the reference device to work, please ensure that your beacon is detectable using an off the shelf app like [Locate](https://play.google.com/store/apps/details?id=com.radiusnetworks.locate&hl=en), and ensure that you have BeaconParser instances registered for your type of beacon.  

If you need more help, please open a question on StackOverflow.com as this forum is reserved for reproducible bug reports and feature requests.
