### ISSUE TITLE
Is there any tool to calculate the coefficient A,B and C for formula 'd=A*(r/t)^B+C'? 

### ISSUE THREAD

**Issue by RichardFans** [AltBeacon/android-beacon-library#47]
we just have done RSSI measurements on Xiaomi3/2s/4, and want to know  how to calculate the coefficient, so that we can add the results to model-distance-calculations.json.

**Comment by Ancy1** [comment]
can sone one help how to do coeffient values for  Samsung Galaxy, Samsung Note,  LG to find the distance for ibeacons in android.appreciate your help?

**Comment by pierre-oord** [comment]
@RichardFans do you still have the original data of the phones you tested, including the iPhone 5s reference value at 1 meter? It would be great if you could send this to me, we are working on putting together a database.
