### ISSUE TITLE
I can't detect iBeacon with simple code

### ISSUE THREAD

**Issue by avatarr** [AltBeacon/android-beacon-library#474]
I have custom beacon and try to use simple code form official web site to detect it but not working.

I try this app [iBeacon Detector](https://play.google.com/store/apps/details?id=youten.redo.ble.ibeacondetector ) form google play store that create form this lib(in this app have ref to this lib), So I use this app to detect my beacon is it working then I try to implement follow by simple code it can't detect beacon

I added this code it still not working
``` java 
beaconManager.getBeaconParsers().add(new BeaconParser().
        setBeaconLayout("m:2-3=beac,i:4-19,i:20-21,i:22-23,p:24-24,d:25-25"));
```

In build.gradle I added 

``` java 
 compile 'org.altbeacon:android-beacon-library:2+' 
```

Test on Google Nexus6P , android 7.1

Thanks in advance

**Comment by davidgyoung** [comment]
I believe the beacon layout shown above is incorrect.  You may need the one for iBeacon.  We cannot publish here for intellectual property reasons.  Please search Google or ask this question on StackOverflow.com.  That is the proper forum for such questions anyway.
