### ISSUE TITLE
Ibeacon scanning enter/leave events firing all the time

### ISSUE THREAD

**Issue by pavel-kurnosov** [AltBeacon/android-beacon-library#497]
### Expected behavior
While I am in radius of beacon, should not have any leave events
### Actual behavior
Even if I am in range of beacon all the time I am getting leave enter events all the time.
### Steps to reproduce this behavior
If I specify:
```
beaconManager.setBackgroundBetweenScanPeriod(10000);
```
Then I am getting constantly leave enter events every check, even if I am still in beacon range.

### Mobile device model and OS version
Android Samsung s7 edge, android 7.0
### Android Beacon Library version
2.9.2

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment]
@pavel-kurnosov, I believe this is the same issue reported in #483.  Please take a look and comment there.
