### ISSUE TITLE
Eddystone UID + TLM how get temperature

### ISSUE THREAD

**Issue by tikorth** [AltBeacon/android-beacon-library#500]
![4863b1b6-e3c7-40d6-b596-171e6348f0a4](https://cloud.githubusercontent.com/assets/13150021/25446749/ea6f9e70-2a88-11e7-9338-b215dbabccc3.jpg)
At link above tell about temperature in topic "Eddystone-TLM"

https://altbeacon.github.io/android-beacon-library/eddystone-support.html

But look a sample at topic "Getting Ranging Updates from Nearby Beacons With Telemetry" there is not a sample how get the temperature.

sample
https://altbeacon.github.io/android-beacon-library/eddystone-how-to.html

well with AltBecon Library is possible get the temperature using beacon Eddystone UID + TLM

**Comment by davidgyoung** [comment]
Reading the temp requires a bit of code to convert a long value for the temperature data field and convert it to an signed double value that represents the temperature in Celsius.  Here's example code that does the conversion:


    long unsignedTemp = (beacon.getExtraDataFields().get(2) >> 8);
    double temperature = unsignedTemp > 128 ? unsignedTemp - 256 : unsignedTemp + (beacon.getExtraDataFields().get(2) & 0xff) / 256.0;

**Comment by tikorth** [comment]
Very thanks, works fine 🥇
