### ISSUE TITLE
Version 2.10 won't restart detecting beacon after Bluetooth turned off and on

### ISSUE THREAD

**Issue by paulbao** [AltBeacon/android-beacon-library#518]
### Steps to reproduce this behavior
1. Turn on bluetooth and start 'android-beacon-library-reference' app
2. Click 'start ranging' and see firstBeacon displayed
3. Turn off bluetooth from settings and there's no beacon displayed
4. Turn bluetooth on

### Expected behavior
Beacon should be detected after bluetooth is turned on again.

### Actual behavior
Cannot detect beacon any more

### Mobile device model and OS version
HTC One, Android 5.0.
### Android Beacon Library version
2.10(This works well on same device with V2.9)

**Comment by davidgyoung** [comment]
Thanks for this report, @paulbao.  This is fixed in #519
