### ISSUE TITLE
Getting beacon in range even bluetooth is off

### ISSUE THREAD

**Issue by arpitjoshi08** [AltBeacon/android-beacon-library#524]
i am using this device 
samsung edge 7 android 7.0
and getting beacon in range after bluetooth off  and ranging not stop.

**Comment by davidgyoung** [comment]
I have heard other reports of Samsung devices continuing to allow bluetooth operations even after the UI reports that bluetooth is off.  This appears to be an operating system settings UI issue.  

Unfortunately, I don't think this library can do much about this problem.  If the operating system leaves bluetooth on even when you turn it off in the UI, it is at the operating system level where it needs to be fixed.
