### ISSUE TITLE
Without Location permission foreground scanning does not work too

### ISSUE THREAD

**Issue by ali-bugdayci** [AltBeacon/android-beacon-library#525]
### Expected behavior

Expecting to find the devices while the app is in the foreground without ACCESS_COARSE_LOCATION permission
 
### Actual behavior

Not getting the permission ACCESS_COARSE_LOCATION on >= Build.VERSION_CODES.M devices results in not finding the devices in range

### Steps to reproduce this behavior

* Remove the ACCESS_COARSE_LOCATION from the manifest file
* Or have it in the manifest file but do not ask for the permission ACCESS_COARSE_LOCATION to the user
* Scan results with no devices while using the app

### Mobile device model and OS version

* Samsung SM-N910C
* Samsung SM-G532F

### Android Beacon Library version

Latest:
    compile 'org.altbeacon:android-beacon-library:2+'

android compile version:
    compileSdkVersion 25
    buildToolsVersion "25.0.3"

### Code

Tried setting background mode to false but with no prevail

```
        beaconManager.setBackgroundMode(false);

```

**Comment by davidgyoung** [comment]
This is expected behavior.  Android M introduced restrictions disallowing Bluetooth scans without the location permission.  See here: http://developer.radiusnetworks.com/2015/09/29/is-your-beacon-app-ready-for-android-6.html

Let me know if I misunderstand the issue.

**Comment by ali-bugdayci** [comment]
Ok. Thank you for the info
