### ISSUE TITLE
Public Beacon class method to retrieve the current average RSSI

### ISSUE THREAD

**Issue by peterdeka** [AltBeacon/android-beacon-library#535]
### Expected behavior
The method should return the current averaged RSSI for the beacon.
### Actual behavior
In the docs there is no method. In the latest release there is a `getRunningAverageRssi` method but the code is not clear: it gets a parameter RSSI?? and returns that same RSSI also assigning it to the class' property (nonsense for me).
### Steps to reproduce this behavior
Feature request
### Mobile device model and OS version
Any
### Android Beacon Library version
2.11

**Comment by davidgyoung** [comment]
Yes, that is obviously a mistake.  The definition should simply be:

```
public double getRunningAverageRssi() {
    return mRunningAverageRssi;
}
```

**Comment by peterdeka** [comment]
Thanks a lot @davidgyoung as the last release was a few days ago i suppose it will be a long wait?! :D any way i can help to speed things up?

**Comment by davidgyoung** [comment]
If you are OK with using a beta release I am planning one for the end of the week.

**Comment by peterdeka** [comment]
@davidgyoung if it can help i opened a PR #536

**Comment by davidgyoung** [comment]
#536 has been merged.
