### ISSUE TITLE
Can some one help me , I'm frustrated now and had no idea what is wrong with my playstore , would appreciate if anyone can teach me a easy way to solve my goole play store 

### ISSUE THREAD

**Issue by brandonwong87** [AltBeacon/android-beacon-library#537]
### Android Beacon Library version

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment]
@brandonwong87, I'd be happy to look at your issue with the Google Play Store if you can open a new question on StackOverflow.com and give it a tag of ibeacon-android
