### ISSUE TITLE
I want to trigger didEnterRegion method with bluetooth off (only using bluetooth scanning from location)

### ISSUE THREAD

**Issue by jimmyleonardo** [AltBeacon/android-beacon-library#549]
### Expected behavior
I want to trigger didEnterRegion method with bluetooth off (only using bluetooth scanning from location in setting)

### Actual behavior
Only can trigger didEnterRegion method with bluetooth on

### Steps to reproduce this behavior
1. Install App on Android phone
2. destroy the App
3. Enable Bluetooth
4. Wait didEnterRegion Trigger Intent Application

### Mobile device model and OS version
Nexus 6 with OS Marshmallow (6.1)

### Android Beacon Library version
version 2.11

Hi, I want to ask about this library. Can I trigger didEnterRegion with condition bluetooth off? I want trigger didEnterRegion with location bluetooth (https://www.androidheadlines.com/2015/05/android-ms-bluetooth-scanning-improves-location-finding.html)

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment]
Sorry, this is not possible.  Bluetooth must be on in all Android versions to detect Bluetooth beacons.  Android 6 simply added the restriction that location *also* be enabled to detect.

**Comment by jimmyleonardo** [comment]
Thanks
