### ISSUE TITLE
Beacon sent out cannot be detected by ios.

### ISSUE THREAD

**Issue by Hubertzzz** [AltBeacon/android-beacon-library#573]
###Expected behavior
The beacon signals sent out by android also can be detected by ios using locate.
### Actual behavior
Only the android version locate can detect the signal sent out by android, ios cannot.
### Steps to reproduce this behavior
Using the beacon layout with ibeacon "m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24", Manufacturer with estimote one "0x015D", others same as the sample code. Then send out but cannot be detected by ios, although using the ibeacon layouut.
### Mobile device model and OS version
Oneplus 3T, andorid 7.1.1
### Android Beacon Library version
2.9.2
IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment]
For detection on Apple devices the company code must be 0x004c

**Comment by Hubertzzz** [comment]
I have already changed to 0x004c, but also cannot be detected. idk why.

**Comment by Hubertzzz** [comment]
And here is my code.
![Uploading code1.png…]()

**Comment by Hubertzzz** [comment]
And here is my code.
![code1](https://user-images.githubusercontent.com/27936498/29852468-cfa4ed1a-8d6c-11e7-89fa-733d75a47b56.png)

**Comment by davidgyoung** [comment]
Code looks OK.  Two thoughts:

1. Is the UUID (Id1) you are using configured in Locate iOS?  As you may know iOS must be pre-configured for the beacon UUIDs to be detected or it will not be able to do so.

2. Are you sure the Android device supports transmission?  Not all do. Use the callback interface to make sure it starts OK:

```
     beaconTransmitter.startAdvertising(beacon, new AdvertiseCallback() {

            @Override
            public void onStartFailure(int errorCode) {
                Log.e(TAG, "Advertisement start failed with code: "+errorCode);
            }

            @Override
            public void onStartSuccess(AdvertiseSettings settingsInEffect) {
                Log.i(TAG, "Advertisement start succeeded.");
            }
        });
```

**Comment by Hubertzzz** [comment]
Thanks for your reply.
I forgot to add the UUID into the Locate iOS. After I added, it can be detected.
Thank you so much.

**Comment by davidgyoung** [comment]
Glad to hear that fixed it!
