### ISSUE TITLE
Can't find model-distance-calculations.json

### ISSUE THREAD

**Issue by davidgyoung** [AltBeacon/android-beacon-library#58]
As reported by @jessolo on #47:

![](https://cloud.githubusercontent.com/assets/5687717/5112726/cf6f431c-6ff7-11e4-8f0a-279f2ef671c7.png)

InputStream stream = ModelSpecificDistanceCalculator.class.getResourceAsStream("/"+path);
if (stream == null) {
this.getClass().getClassLoader().getResourceAsStream("/"+path);
}
if (stream == null) {
throw new RuntimeException("Cannot load resource at "+path);
}
Pls refer to the code snippet from ModelSpecificDistanceCalculator. It could be a probable miss here. The stream is not assigned when stream is from class loader.Even if the file is readable from classloader stream, it will still throw a RuntimeException.

But the above exception is definitely not because of this. It is possible to load from the web and the file is getting saved. But unable to read from the file.

**Comment by IgorGanapolsky** [comment]
@davidgyoung Can you repost the link to your proposed changes?  That link doesn't work anymore.
