### ISSUE TITLE
Used jobIds should be documented and configurable

### ISSUE THREAD

**Issue by strooooke** [AltBeacon/android-beacon-library#582]
See https://commonsware.com/blog/2017/06/07/jobscheduler-job-ids-libraries.html for a much better written explanation of why it matters.

It's up to the client app to make sure that their chosen jobIds will then be unique inside their uid, and stay fixed over process restarts, device reboots, updates etc... a use case for statics if I've ever seen one. But they need to be configurable to avoid clashes.

**Comment by davidgyoung** [comment]
Fair point.  Seems reasonable to make this configurable in the AndroidManifest.xml

**Comment by strooooke** [comment]
Manifest configuration would work - personally, as an app developer, I'd prefer the ability to configure in Java (because I like to keep such constants (like e.g. notification ids) in some constant collection class and reference from there whereever needed; Manifest configuration would force me to keep that collection as int resources - also works, but less comfortable to reference in the majority of the code).

**Comment by davidgyoung** [comment]
Resolved in #645
