### ISSUE TITLE
Can not scan only the first time, but Can be scanned when restarted. (Android M and Later)

### ISSUE THREAD

**Issue by tanakanatsuki** [AltBeacon/android-beacon-library#585]
Hi
I have Problem. 
Can not scan only the first time.
but , Can be scanned when restarted app. (Android M and Later)
I do not know why it will happen.

Old Android is no problem(Android 4.4.4 not showing dialog)
Is the timing of ”android.permission.ACCESS_COARSE_LOCATION” doubtful?

### Expected behavior
  Show dialog（android.permission.ACCESS_COARSE_LOCATION）
  Scan iBeacon UUID
### Actual behavior
  Show dialog（android.permission.ACCESS_COARSE_LOCATION）
  not Scan iBeacon (First Time only> not scan)
### Steps to reproduce this behavior

public class MainActivity extends AppCompatActivity implements BeaconConsumer {
    private static final String TAG = "MainActivity";
    private BeaconManager beaconManager;
    // iBeaconのデータを認識するためのParserフォーマット
    public static final String IBEACON_FORMAT = "m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24";
    private static final int PERMISSION_REQUEST_COARSE_LOCATION = 1;
    private Vibrator vib;
    private WebView webView;
    private boolean beaconFindFlg = false;
    private SettingBean settingBean;
    private boolean nowPassportShowing = false;
    private FirebaseAnalytics mFirebaseAnalytics;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        this.ble_boot1_permission_check();
    }

    private void ble_boot1_permission_check(){
        Log.d(TAG, "ble_boot1_permission_check");

        // Android M Permission check
        Log.d(TAG, "Android: " + android.os.Build.VERSION.SDK_INT);
        Log.d(TAG, "Android Beacon Library version: " + org.altbeacon.beacon.BuildConfig.VERSION_NAME);
        Log.d(TAG, "Android version M?: "+(android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.M));
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            if (this.checkSelfPermission(android.Manifest.permission.ACCESS_COARSE_LOCATION) != PackageManager.PERMISSION_GRANTED) {
                requestPermissions(new String[]{android.Manifest.permission.ACCESS_COARSE_LOCATION},PERMISSION_REQUEST_COARSE_LOCATION);
            }else {
                this.ble_boot2_request_on();
            }
        }else{
            this.ble_boot2_request_on();
        }
    }

    private void ble_boot2_request_on(){
        Log.d(TAG, "ble_boot2_request_on");
        BluetoothAdapter Bt = BluetoothAdapter.getDefaultAdapter();
        boolean btEnable = Bt.isEnabled();
        if(btEnable == true){
            this.ble_boot3_beaconBind();
        }else{
            Intent btOn = new Intent(BluetoothAdapter.ACTION_REQUEST_ENABLE);
            startActivityForResult(btOn, 1);
        }
    }

    private void ble_boot3_beaconBind(){
        Log.d(TAG, "ble_boot3_beaconBind");
        beaconManager = BeaconManager.getInstanceForApplication(this);
        beaconManager.getBeaconParsers().add(new BeaconParser().setBeaconLayout(IBEACON_FORMAT));
        beaconManager.applySettings();
        beaconManager.bind(this);
    }

    private void ble_stop(){
        beaconFindFlg = true;
        try {
            if (beaconManager != null){
                beaconManager.removeAllRangeNotifiers();
            }
            //beaconManager.unbind(this);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    protected void onStop() {
        super.onStop();
        Log.d(TAG, "onStop");
        ble_stop();
        this.finish();
    }

    @Override
    protected void onPause() {
        super.onPause();
        Log.d(TAG, "onPause");
        ble_stop();
        if(beaconManager != null) {
            if (beaconManager.isBound(this)) beaconManager.setBackgroundMode(true);
        }
    }

    @Override
    protected void onResume() {
        super.onResume();
        Log.d(TAG, "onResume");
        if(beaconManager != null) {
            if (beaconManager.isBound(this)) beaconManager.setBackgroundMode(false);
        }
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        Log.d(TAG, "onDestroy");
        if(beaconManager != null) {
            beaconManager.unbind(this);
        }
        if(webView != null){
            webView.stopLoading();
            webView.setWebChromeClient(null);
            webView.setWebViewClient(null);
            webView.destroy();
            webView = null;
        }
    }

    private double distance;
    long start;
    long end;

    @Override
    public void onBeaconServiceConnect() {

        beaconManager.setRangeNotifier(new RangeNotifier() {
            @Override
            public void didRangeBeaconsInRegion(Collection<Beacon> beacons, Region region) {

                //パスポート画面を表示している時だけ通知する。
                if(nowPassportShowing){
                    // 検出したビーコンの情報
                    for (Beacon beacon:beacons) {
                        //対象のビーコンであるかチェック
                        if(settingBean.beacon_uuids.contains(beacon.getId1().toString())) {
                            Log.d(TAG, "beacon発見: " + beacon.getId1());
                            Log.d(TAG, "beacon発見: " + beacon.getId2());
                            Log.d(TAG, "beacon発見: " + beacon.getId3());
                            Log.d(TAG, "beacon発見: " + beacon.getDistance());
                            //System.out.println("beacon発見: " + beacon.getDistance());
                            distance = beacon.getDistance();

                            //規定の範囲内にBeaconがあったら入店とする。
                            if (distance < Const.FIND_AREA) {
                                if (!beaconFindFlg) {
                                    beaconFindFlg = true;
                                    start = System.currentTimeMillis();
                                    findBeacon(beacon.getId2().toString());
                                }
                                end = System.currentTimeMillis();
                                if ((end - start) > InfoData.getSettingBean(getApplicationContext()).beacon_wait_sec * 1000) {
                                    beaconFindFlg = false;
                                }
                            }
                        }
                    }
                }
            }
        });

        try {
            // ビーコン情報の監視を開始
            Log.d(TAG, "ビーコン情報の監視を開始");
            beaconManager.startRangingBeaconsInRegion(new Region("myRangingUniqueId", null, null, null));
        } catch (RemoteException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        if(requestCode == PERMISSION_REQUEST_COARSE_LOCATION){
            if (grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
                Log.d(TAG, "Location許可OK");
                mFirebaseAnalytics.logEvent(Const.FBA_LOCATION_ALLOWED, InfoData.makeFBA_Param(getApplicationContext()));
                this.ble_boot2_request_on();
                return;
            } else {
                Log.d(TAG, "Location許可NG");
                mFirebaseAnalytics.logEvent(Const.FBA_LOCATION_NOT_ALLOWED, InfoData.makeFBA_Param(getApplicationContext()));
                return;
            }
        }
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if(requestCode == 1){
            if(resultCode == Activity.RESULT_OK){
                //BluetoothがONにされた場合の処理
                Log.d(TAG, "「BluetoothをONにする」＞許可");
                mFirebaseAnalytics.logEvent(Const.FBA_BLE_ALLOWED, InfoData.makeFBA_Param(getApplicationContext()));
                this.ble_boot3_beaconBind();
            }else{
                Log.d(TAG, "「BluetoothをONにする」＞許可しない");
                mFirebaseAnalytics.logEvent(Const.FBA_BLE_NOT_ALLOWED, InfoData.makeFBA_Param(getApplicationContext()));
                //finish();
            }
        }
    }
}

### Mobile device model and OS version
  Nexus6(Android7.0) NG (FirstBoot>no scan)
  Nexus5(Android4.4.4) OK (no problem)

### Android Beacon Library version
2.12.2

**Comment by davidgyoung** [comment]
@tanakanatsuki , you cannot get scan results until permission is granted from the user dialog on Android 6+.   If you need help with your code getting this granted, please post a question on StackOverflow.com.  If you suspect a bug in the library, please reproduce with the reference app (which does permission prompting) and reopen this issue.
