### ISSUE TITLE
Nexus 4 still needs scan restart

### ISSUE THREAD

**Issue by ma-rp** [AltBeacon/android-beacon-library#59]
I've been testing the android-l branch with my recently updated Nexus 4 and it appears that the scanning still needs to be restarted. After it reports seeing a beacon the first time, it doesn't report it again. 
Have you tested the library with this device? Is this something particular for me that I shouldn't be experiencing or is just that the new API is somehow incompatible with the Nexus 4?

Another matter is that I couldn't replicate the results described here http://developer.radiusnetworks.com/2014/10/28/android-5.0-scanning.html regarding the Typical time between detections in the low latency mode, as the detections were nowhere near 100ms for beacons transmitting at 20ms. In many cases, some of the beacons were reported more than a second after started ranging. 
Again, since you report different results, I don't know if this situation is particular for this device.

**Comment by davidgyoung** [comment]
I have verified this is true on a Nexus 4 with Android 5.  I incorrectly thought this behavior was specific to the operating system version, but apparently it is either hardware specific or hardware driver-specific.  Here is the Google Code issue on the subject:

https://code.google.com/p/android/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars&groupby=&sort=&id=65863

A fix for this has been merged into the 2.1-beta2 release, which simply restarts scanning under Android 5 across all devices -- there is no way to know which devices require it!
