### ISSUE TITLE
CycledLeScannerForLollipop: Scan failed: app cannot be registered

### ISSUE THREAD

**Issue by g4gaj** [AltBeacon/android-beacon-library#595]
### Android Beacon Library version 2.11

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment]
See here:  https://stackoverflow.com/questions/46376251/cycledlescannerforlollipop-scan-failed-app-cannot-be-registered-alt-beacon-li/46386224#46386224
