### ISSUE TITLE
Class not found 

### ISSUE THREAD

**Issue by JeromeDuban** [AltBeacon/android-beacon-library#60]
Hi,
I'm currently working on a project which requires the use of your library. I developped a service extending BeaconConsumer which runs the ranging process.

The app is running well if I compile it on linux but I don't know why, the app doesn't work anymore when the app is compiled whith Eclipse on Windows.

The logcat displayed is this one : 

```
11-28 18:14:20.909: I/dalvikvm(18349): Failed resolving Lcom/eirb/projets9/scanner/RangingService; interface 772 'Lorg/altbeacon/beacon/BeaconConsumer;'
11-28 18:14:20.909: W/dalvikvm(18349): Link of class 'Lcom/eirb/projets9/scanner/RangingService;' failed
11-28 18:14:20.909: E/dalvikvm(18349): Could not find class 'com.eirb.projets9.scanner.RangingService', referenced from method com.eirb.projets9.MainActivity.onCreate
11-28 18:14:20.909: W/dalvikvm(18349): VFY: unable to resolve const-class 673 (Lcom/eirb/projets9/scanner/RangingService;) in Lcom/eirb/projets9/MainActivity;
11-28 18:14:20.909: D/dalvikvm(18349): VFY: replacing opcode 0x1c at 0x000f
11-28 18:14:20.949: D/AndroidRuntime(18349): Shutting down VM
11-28 18:14:20.949: W/dalvikvm(18349): threadid=1: thread exiting with uncaught exception (group=0x41569ba8)
11-28 18:14:20.959: E/AndroidRuntime(18349): FATAL EXCEPTION: main
11-28 18:14:20.959: E/AndroidRuntime(18349): Process: com.eirb.projets9, PID: 18349
11-28 18:14:20.959: E/AndroidRuntime(18349): java.lang.NoClassDefFoundError: com.eirb.projets9.scanner.RangingService
11-28 18:14:20.959: E/AndroidRuntime(18349):    at com.eirb.projets9.MainActivity.onCreate(MainActivity.java:56)
11-28 18:14:20.959: E/AndroidRuntime(18349):    at android.app.Activity.performCreate(Activity.java:5231)
11-28 18:14:20.959: E/AndroidRuntime(18349):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
```

RangingService is my background service started from MainActivity. I have no idea why the app is working diffenrently according to the OS. 

Thanks in advance

Update : I can't launch the android-beacon-library-reference neither when I compile it from windows ( no problem with linux )

**Comment by Icar05** [comment]
The same trouble in project with kotlin. apis versions 28. Build -tools last versions

**Comment by davidgyoung** [comment]
@Icar 05, can you please try to reproduce locally with the library Reference App?  It is all Java, but you can add a Kotlin file as needed to see if that makes any difference.  Reproducing with the reference app is super important as build setup issues are almost always project-specifuc.  If you can reproduce this way, please simply open a new issue with the steps to reproduce and I will take a look.

**Comment by Icar05** [comment]
sorry, i can't find information about reference app library. Can you tell me exactly, what should i do?
I can show you my gradle files, if it needs. Main project based on kotlin,  i 'm trying to add this library.

**Comment by davidgyoung** [comment]
Here is the reference app:

https://github.com/AltBeacon/android-beacon-library-reference

Please close this git repo and verify it builds for you.  Add Kotlin files as needed to confirm if this is or is not the issue.

**Comment by Icar05** [comment]
ok, i get, i'll try it

**Comment by Icar05** [comment]
yes, no needs open issue. There is trouble only with using mapwize with this library, trouble not in altbeacon( Sorry and thanks. If it can help to someone, when appear Class Not Found, need to add 
altbeacon implementation in module app. No matter if this library used in inner module, anyway it should be
