### ISSUE TITLE
Regression in custom sample expiration for RunningAverageRssiFilter

### ISSUE THREAD

**Issue by cupakromer** [AltBeacon/android-beacon-library#627]
### Expected behavior

Setting a custom sample expiration using `RunningAverageRssiFilter. setSampleExpirationMilliseconds` changes the static expiration and thus running RSSI averages.

### Actual behavior

All distance calculations use the value from `RangedBeacon.sampleExpirationMilliseconds`.

This is a regression of AltBeacon/android-beacon-library#523 (AltBeacon/android-beacon-library-reference#30). It was introduced in commit f084042efa3264ba (PR AltBeacon/android-beacon-library#484) where the `RunningAverageRssiFilter` has it's value constantly reset after every cycle in [`RangedBeacon#commitMeasurements`](https://github.com/AltBeacon/android-beacon-library/commit/f084042efa3264ba673814eec88ce591f1ac66df#diff-65311818bc092d4192549ca6a7932a8aR50).

### Steps to reproduce this behavior

1. Set a custom sample expiration through `RunningAverageRssiFilter.setSampleExpirationMilliseconds`
1. Range for a beacon
1. Wait for the scan cycle to complete
1. Check the value of the `RunningAverageRssiFilter` sample expiration

### Android Beacon Library version

2.12.3

**Comment by davidgyoung** [comment]
Yes, it appears I undid the change from #523 got undone in a bad merge.

I think it is safe to remove the `sampleExpirationMilliseconds` field from `RangedBeacon` entirely, including its use in  `commitMeasurements()`.  This field is a holdover from the 0.x version of the library where `RangedBeacon` was where this setting was stored.   Only this method needs to be retained:

```
    //kept here for backward compatibility
    public static void setSampleExpirationMilliseconds(long milliseconds) {
        sampleExpirationMilliseconds = milliseconds;
        RunningAverageRssiFilter.setSampleExpirationMilliseconds(sampleExpirationMilliseconds);
    }
```

And it should probably be deprecated.
