### ISSUE TITLE
The result of this line is always false

### ISSUE THREAD

**Issue by dietert** [AltBeacon/android-beacon-library#628]
Hello

The following line:

https://github.com/AltBeacon/android-beacon-library/blob/8cd351f093bad282a03ef452c1baf4650aaff246/src/main/java/org/altbeacon/beacon/BeaconManager.java#L498

 return consumers.isEmpty() && (serviceMessenger != null);
 
=> is always false

Suggest to change the line to

 return !consumers.isEmpty() && (serviceMessenger != null);

**Comment by davidgyoung** [comment]
Thanks for the note -- I believe you are correct.  We already have this logged as issue #600, so I'm closing this, but feel free to comment there.
