### ISSUE TITLE
Is it possible to get rssi of each channel?

### ISSUE THREAD

**Issue by iampkuhz** [AltBeacon/android-beacon-library#635]
hi, is it possible to get each channel's rssi with this dependency while scanning?
namely channel 37\38\39.

thanks~~

**Comment by davidgyoung** [comment]
Unfortunately no.  Android had no APIs to determine which channel a particular advertisement packet was received upon.  This is too bad, because RSSI typically varies a bit between channels, and if possible, adjusting  RSSI for channel would be useful for more accurate distance estimates.

**Comment by iampkuhz** [comment]
what a pity! That's exactly why I want to get rssi of each channel...
thanks for your apply~
