### ISSUE TITLE
Exit and Enter Regions method    are fired simultaneously where the beacon is still in range and active.  

### ISSUE THREAD

**Issue by nofal-barefoot** [AltBeacon/android-beacon-library#639]
[### Expected behavior

That the lib should only fire exit when beacon has actually exited the region.

### Actual behavior

The lib fires exit and enter region methods where the beacon is still in range. And this happens 20 sec apart some time more frequent some times less frequent on all android versions from 5-7

### Steps to reproduce this behavior

I am running the beacon app continuously in the background as soon as the bluetooth gets turned 
ON to search the beacon ,the beacon is fixed inside a car and is broadcasting at 1000s interval i have to start a ride when ever a user gets in the range and stop the ride when ever it gets out of it but the issue is that itt reports beacon Entered and Exited continuously where the user never left the beacon zone. 

My code snippet

public class BackgroundBeaconScan extends Service implements BootstrapNotifier, BeaconConsumer {
 @Override
    public void onCreate() {
        super.onCreate();
        AppUtils.isBGServiceActive = true;
        //AppUtils.appTerminated = false;
        Log.e("Beacon", "Service Start");
        Log.e("Bfpk", " *** Beacon  Service is started *** ");
        LoggingOperations logger = new LoggingOperations();
        Thread.setDefaultUncaughtExceptionHandler(logger);
        mBeaconManager = org.altbeacon.beacon.BeaconManager.getInstanceForApplication(this);
        try {
            Log.e("BG", "iam in mBeaconManager to unbind it");
            mBeaconManager.unbind(this);
            mBeaconManager.removeAllRangeNotifiers();
            mBeaconManager.removeAllMonitorNotifiers();
            mBeaconManager.removeMonitoreNotifier(this);
        } catch (OutOfMemoryError e) {
            Log.e("BG", "iam in mBeaconManager to unbind it excep ");

        }
        mBeaconManager.getBeaconParsers().clear();
        //set Beacon Layout for Eddystone-UID packet

        mBeaconManager.getBeaconParsers().add(new BeaconParser().setBeaconLayout(BeaconParser.EDDYSTONE_UID_LAYOUT));
        //   rideBDD = new RideBDD(getApplicationContext());
        mBeaconManager.setForegroundScanPeriod(20001);

        mBeaconManager.setForegroundBetweenScanPeriod(50001);

        mBeaconManager.setBackgroundScanPeriod(20001);

        mBeaconManager.setBackgroundBetweenScanPeriod(50001);

        mBeaconManager.setBackgroundMode(true);

        mBeaconManager.setDebug(true);

        BeaconManager.setAndroidLScanningDisabled(true);

        notificationManager = (NotificationManager) this.getSystemService(Context.NOTIFICATION_SERVICE);

        namespace = DataHandler.getStringPreferences(AppConstants.UUID_NAME_SPACE);
        instanceID = DataHandler.getStringPreferences(AppConstants.UUID_INSTANCE_ID);
        Log.e("BG", "namespace :" + namespace);
        Log.e("BG", "instanceID :" + instanceID);
        Long currentTime = System.currentTimeMillis();
        String time = formateLongToOnlyDateForServer(currentTime);
        LoggingOperations.writeToFile(BackgroundBeaconScan.this,"UUID > " + time + " -- > " + namespace + " - " + instanceID);

  

        try {
            Log.e("BG", "iam in mBeaconManager.isBound");
            mBeaconManager.bind(this);
            Log.e("BG", "iam in mBeaconManager.bind");

        } catch (OutOfMemoryError e) {
            Log.e("BG", "iam in mBeaconManager.bindexce", e);

        }

    }

 @Override
    public void onBeaconServiceConnect() {
        // String preiBeaconUUID = DataHandler.getStringPreferences(AppConstants.UUID);
        // postiBeaconUUID=AppUtils.addDashes(preiBeaconUUID);
        Region region;
        try {
            Log.e("BG", "iam in onBeaconServiceConnect");
            namespace = DataHandler.getStringPreferences(AppConstants.UUID_NAME_SPACE);

            instanceID = DataHandler.getStringPreferences(AppConstants.UUID_INSTANCE_ID);

            Identifier myBeaconNamespaceId = Identifier.parse(namespace);

            Identifier myBeaconInstanceId = Identifier.parse(instanceID);

            region = new Region("EdstUIDAdvertising", myBeaconNamespaceId, myBeaconInstanceId, null);

            mBeaconManager.addMonitorNotifier(this);
            Log.e("BG", "iam in startMonitoringBeaconsInRegion");

        } catch (Exception e) {
            Log.e("BG", "iam in startMonitoringBeaconsInRegionExce" + e);
            e.printStackTrace();
            namespace = DataHandler.getStringPreferences(AppConstants.UUID_NAME_SPACE);

            instanceID = DataHandler.getStringPreferences(AppConstants.UUID_INSTANCE_ID);

            Identifier myBeaconNamespaceId = Identifier.parse(namespace);

            /* Identifier myBeaconInstanceId = Identifier.parse(instanceID);*/
            region = new Region("EdstUIDAdvertising", myBeaconNamespaceId, null, null);
            mBeaconManager.addMonitorNotifier(this);
            Log.e("BG", "iam in startMonitoringBeaconsInRegion");

        }
        AppUtils.isBGServiceActive = true;
        try {
            mBeaconManager.startMonitoringBeaconsInRegion(region);
        } catch (RemoteException e) {
            e.printStackTrace();
        }
        mBeaconManager.addMonitorNotifier(new MonitorNotifier() {
            @Override
            public void didEnterRegion(Region region) {
                Log.e("Monitored", "entered"); this fires at the same time
                enterCount++;

}

  @Override
            public void didExitRegion(Region region) {
                Log.e("Monitored", "exited"); // this fires at the same time

}

            @Override
            public void didDetermineStateForRegion(int i, Region region) {

            }
        });
}

The
### Mobile device model and OS version

Samsung note 5 (7.0) s6 (6.0) s5 (5.0) every device

### Android Beacon Library version
2.12.4 // please help i am facing this issue for quiet a long time now

**Comment by davidgyoung** [comment]
See answer here:  https://stackoverflow.com/questions/48243356/alt-beacon-lib-continuously-fires-enter-and-exit-region-method-where-the-user-ne/48243461#48243461
