### ISSUE TITLE
Beacon scanning when paired with Bluetooth headse

### ISSUE THREAD

**Issue by valob** [AltBeacon/android-beacon-library#667]
the scanning for beacons works just fine , but when pairing with a Bluetooth speaker while scanning for beacons the scanning sometimes stops or scans once every few minutes

**Comment by davidgyoung** [comment]
We have received reports like this before,  and the issue turned out to be inside the bluetooth hardware implementation in the phone, so it was not possible to fix it via software.

That said, it would be helpful if you could report your hardware model and OS version.

**Comment by davidgyoung** [comment]
closing due to insufficient information
