### ISSUE TITLE
Have any example code about aramfilter use method?

### ISSUE THREAD

**Issue by JasonChungLin** [AltBeacon/android-beacon-library#669]
I want to improve accuracy. I know the aramfilter but how to using aramfilter? I see Official documents but still do not know use to it. Should it add where?

**Comment by davidgyoung** [comment]
It should be as simple as `BeaconManager.setRssiFilterImplClass(ArmaRssiFilter.class);`  If you need further help, please open a new question on StackOverflow.com as that is the preferred forum for supporting this library.  This forum is reserved for bug reports and feature requests with the library.

There is a documentation page that describes this [here](https://altbeacon.github.io/android-beacon-library/distance_vs_time.html)
