### ISSUE TITLE
Advertize beacon one after another using for loop, couldn't stop the advertizing

### ISSUE THREAD

**Issue by jprashant610** [AltBeacon/android-beacon-library#682]
```
Here is my function from which i called the start advertising function.

```
public static boolean advertizingStatusGroup;
public void advertizeBeaconOneAfterAnother(){

 beaconTransmitter = new BeaconTransmitter(getApplicationContext(), beaconParser);
        
        for (int i=0;i<fireBaseGroupDeviceArrayList.size();i++){
            
            Log.e(TAG,"Group id :"+fireBaseGroupDeviceArrayList.get(i).getGroup_device_group_id());
            Log.e(TAG,"Brightness :"+fireBaseGroupDeviceArrayList.get(i).getBrightness());
            Log.e(TAG,"Bda :"+fireBaseGroupDeviceArrayList.get(i).getGroup_device_device_id());
            SplitBda splitBda = new SplitBda();
            String[] splitBDA = splitBda.splitTheBda(fireBaseGroupDeviceArrayList.get(i).getGroup_device_device_id());

            int hexBdaInt1=Integer.parseInt(splitBDA[3],16);
            int hexBdaInt2=Integer.parseInt(splitBDA[4],16);
            int hexBdaInt3=Integer.parseInt(splitBDA[5],16);

            leftShifted2=(hexBdaInt2<<8)|hexBdaInt3;
            Log.e(TAG,"Left shifted2 :"+leftShifted2);

            Log.e(TAG,"hexBdaInt1 :"+hexBdaInt1);
            Log.e(TAG,"hexBdaInt2 :"+hexBdaInt2);
            Log.e(TAG,"hexBdaInt3 :"+hexBdaInt3);

            hexBdaString1= String.valueOf(hexBdaInt1);
            hexBdaString2= String.valueOf(hexBdaInt2);
            hexBdaString3= String.valueOf(hexBdaInt3);

            if (hexBdaString1.length()==1){
                hexBdaString1="0"+hexBdaString1;
            }
            if(hexBdaString2.length()==1){
                hexBdaString2="0"+hexBdaString2;
            }
            if(hexBdaString3.length()==1){
                hexBdaString3="0"+hexBdaString3;
            }
            Log.e(TAG,"hexBdaString1 :"+hexBdaString1);
            Log.e(TAG,"hexBdaString2 :"+hexBdaString2);
            Log.e(TAG,"hexBdaString3 :"+hexBdaString3);
            
            intensity=Integer.parseInt(fireBaseGroupDeviceArrayList.get(i).getBrightness());
            startBeaconAdvertizing(hexBdaString1.toUpperCase(), String.valueOf(leftShifted2), intensity);
        }
}
```
```
Here is my start advertising function:
```
   public void startBeaconAdvertizing(String bdaPart1,String bda2,int intensity){

        if (advertizingStatusGroup==true){
            Log.e(TAG,"Advertizing Status in if:"+advertizingStatusGroup);
            beaconTransmitter.stopAdvertising();
        }

        beacon = new Beacon.Builder()
                .setId1("55555555-5555-5555-5555-555555555555")
                .setManufacturer(0x0008) // It is for AltBeacon.  Change this for other beacon layouts
//                .setTxPower(-76+beaconParser.getPowerCorrection())
                .setId2(bdaPart1)
                .setId3(bda2)
                .setTxPower(intensity)
                .setDataFields(Arrays.asList(new Long[]{6l, 7l})) // Remove this for beacon layouts without d: fields
                .build();


        beaconTransmitter.setAdvertiseMode(2);
        beaconTransmitter.startAdvertising(beacon, new AdvertiseCallback() {
            @Override
            public void onStartSuccess(AdvertiseSettings settingsInEffect) {
                super.onStartSuccess(settingsInEffect);
                advertizingStatusGroup=true;
//                beaconTransmitter.isStarted();
                Log.e(TAG,"ADVERTIZING START");
                Log.e(TAG,"Advertizing Status t on suc:"+advertizingStatusGroup);
//                SystemClock.sleep(2500);

            }

            @Override
            public void onStartFailure(int errorCode) {
                super.onStartFailure(errorCode);
//                advertizingStatusGroup=false;
                Log.e(TAG,"ADVERTIZING NOT STARTED");
            }
        });
    }
```

Here is my log when my array list size is 2

```
05-05 09:54:17.912 31687-31687/com.shalaka.bledimmer D/BeaconParser: Identifier size is just right: 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55
05-05 09:54:17.913 31687-31687/com.shalaka.bledimmer D/BeaconParser: Identifier size is just right: 00 11
05-05 09:54:17.913 31687-31687/com.shalaka.bledimmer D/BeaconParser: Identifier size is just right: 11 03
05-05 09:54:17.915 31687-31687/com.shalaka.bledimmer D/BeaconTransmitter: Starting advertising with ID1: 55555555-5555-5555-5555-555555555555 ID2: 17 ID3: 4355 and data: 02 15 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 00 11 11 03 00  of size 23
05-05 09:54:17.916 31687-31687/com.shalaka.bledimmer D/BluetoothAdapter: STATE_ON
05-05 09:54:17.920 31687-31706/com.shalaka.bledimmer D/BluetoothLeAdvertiser: onClientRegistered() - status=0 clientIf=13
05-05 09:54:17.933 31687-31687/com.shalaka.bledimmer D/BeaconTransmitter: Started advertisement with callback: org.altbeacon.beacon.BeaconTransmitter$1@32f94f5

05-05 09:54:17.935 31687-31687/com.shalaka.bledimmer D/BeaconParser: Identifier size is just right: 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55
05-05 09:54:17.935 31687-31687/com.shalaka.bledimmer D/BeaconParser: Identifier size is just right: 00 12
05-05 09:54:17.935 31687-31687/com.shalaka.bledimmer D/BeaconParser: Identifier size is just right: 12 03
05-05 09:54:17.936 31687-31687/com.shalaka.bledimmer D/BeaconTransmitter: Starting advertising with ID1: 55555555-5555-5555-5555-555555555555 ID2: 18 ID3: 4611 and data: 02 15 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 00 12 12 03 00  of size 23
05-05 09:54:17.937 31687-31687/com.shalaka.bledimmer D/BluetoothAdapter: STATE_ON
05-05 09:54:17.939 31687-31687/com.shalaka.bledimmer D/BeaconTransmitter: Started advertisement with callback: org.altbeacon.beacon.BeaconTransmitter$1@32f94f5
05-05 09:54:17.986 31687-31687/com.shalaka.bledimmer I/BeaconTransmitter: Advertisement start succeeded.
```

what should i do to resolve this issue ?

**Comment by davidgyoung** [comment]
@jprashant610, can you please ask this as a question on StackOverflow.com?  That is the preferred forum for asking project-specific how-to and debugging questions for projects that use the library.  This forum is reserved only for feature requests and library bug reports.

If you open a new question on StackOverflow.com, I am glad to answer there.   Please include in that question what you have done to try to stop transmitting as the title suggests, and what about it does not work.
