### ISSUE TITLE
Download link for android-beacon-library-2.14.aar returns 404 Not Found error

### ISSUE THREAD

**Issue by L3xer** [AltBeacon/android-beacon-library#705]
I was trying to download android-beacon-library-2.14.aar from https://altbeacon.github.io/android-beacon-library/download.html, it redirects to the link https://github.com/AltBeacon/android-beacon-library/releases/download/2.13/android-beacon-library-2.14.aar that returns 404 Not Found error.

I believe it should be changed to https://github.com/AltBeacon/android-beacon-library/releases/download/2.14/android-beacon-library-2.14.aar

**Comment by davidgyoung** [comment]
Thanks for this report.  I have fixed the download link.
