### ISSUE TITLE
beaconManager Not Binded

### ISSUE THREAD

**Issue by MahendranValueStream** [AltBeacon/android-beacon-library#732]
`public class SampleBroadcastReceiver implements BeaconConsumer {
    Activity mActivity;
    Context mContext;
    private BeaconManager beaconManager;

    public SampleBroadcastReceiver(Activity mActivity, Context context) {
        this.mActivity = mActivity;
        mContext = context;
        checkForLocationPermission();
    }

    public void startBeaconService() {
        Log.w("success", "Comes startBeaconService");
        beaconManager = BeaconManager.getInstanceForApplication(mContext);
        beaconManager.getBeaconParsers().clear();
        beaconManager.getBeaconParsers().add(new BeaconParser()
                //.setBeaconLayout(("s:0-1=feaa,m:2-2=00,p:3-3:-41,i:4-13,i:14-19")));
                .setBeaconLayout(BeaconParser.EDDYSTONE_UID_LAYOUT));
        beaconManager.setDebug(true);

        beaconManager.bind(this);
        Log.w("Success","Is Bounded::::;"+beaconManager.isBound(this));
    }`

BeaconManger did not binded..

**Comment by davidgyoung** [comment]
The call to `beaconManager.bind(this);` is not synchronous.  You must wait for an asynchronous callback to `onBeaconServiceConnect() `.
