### ISSUE TITLE
Not scanning in background for android 8.1

### ISSUE THREAD

**Issue by mspapant** [AltBeacon/android-beacon-library#733]
I am trying to use the service to scan beacons in background but my code is never called.

this is my code:

`LogManager.setVerboseLoggingEnabled(true);
        BeaconManager beaconManager = BeaconManager.getInstanceForApplication(this);
        beaconManager.setDebug(true);
        BeaconParser kontaktBeaconParser = new BeaconParser().setBeaconLayout("m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24,d:25-25");
        beaconManager.getBeaconParsers().add(kontaktBeaconParser);
        Region region = new Region("myApplicationId", null, null, null);
        regionBootstrap = new RegionBootstrap(this, region);

        beaconManager.addRangeNotifier(new RangeNotifier() {
            @Override
            public void didRangeBeaconsInRegion(Collection<Beacon> collection, Region region) {
                BeaconActivity_.intent(MainActivity.this).value(collection.iterator().next().toString()).start();
            }
        });`

But the code in didRangeBeaconsInRegion is never called.
The logs from logcat are:

> 09-02 02:12:38.930 19142-19142/applicationId I/BeaconManager: BeaconManager started up on pid 19142 named 'applicationId' for application package 'applicationId'.  isMainProcess=true
09-02 02:12:38.937 19142-19142/applicationId D/BeaconParser: Parsing beacon layout: m:2-3=beac,i:4-19,i:20-21,i:22-23,p:24-24,d:25-25
09-02 02:12:38.941 19142-19142/applicationId D/BeaconParser: Parsing beacon layout: m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24,d:25-25
09-02 02:12:42.762 19142-19142/applicationId D/BeaconManager: This consumer is not bound.  Binding now: org.altbeacon.beacon.startup.RegionBootstrap$InternalBeaconConsumer@c8aff5a
09-02 02:12:42.763 19142-19142/applicationId D/BeaconManager: Not starting beacon scanning service. Using scheduled jobs
09-02 02:12:42.780 19142-19142/applicationId D/BeaconManager: callback packageName: applicationId
09-02 02:12:42.847 19142-19142/applicationId D/MonitoringStatus: Region  id1: null id2: null id3: null uniqueId: com.example.myapp.boostrapRegion state: org.altbeacon.beacon.service.RegionMonitoringState@9d255f1
09-02 02:12:43.009 19142-19142/applicationId D/ScanState: Temp file is /data/user/0/applicationId/files/android-beacon-library-scan-state-temp
    Perm file is /data/user/0/applicationId/files/android-beacon-library-scan-state
09-02 02:12:43.015 19142-19142/applicationId D/BeaconLocalBroadcastProcessor: Register calls: global=1 instance=1
09-02 02:12:43.032 19142-19142/applicationId D/ScanJobScheduler: Scheduling ScanJob (job:208352940/applicationId/org.altbeacon.beacon.service.ScanJob) to run every 300000 millis
09-02 02:12:43.037 19142-19142/applicationId D/BeaconManager: updating background flag to true
09-02 02:12:43.038 19142-19142/applicationId D/BeaconManager: updating scan period to 10000, 300000
09-02 02:12:43.079 1010-1010/? D/JobServiceContext: Scheduling time out for 'org.altbeacon.beacon.service.ScanJob' jId: 208352939, in 18 s
09-02 02:12:43.083 19142-19142/applicationId D/ScanState: Temp file is /data/user/0/applicationId/files/android-beacon-library-scan-state-temp
    Perm file is /data/user/0/applicationId/files/android-beacon-library-scan-state
09-02 02:12:43.096 19142-19142/applicationId D/ScanJobScheduler: Scheduling ScanJob (job:208352940/applicationId/org.altbeacon.beacon.service.ScanJob) to run every 310000 millis
09-02 02:12:43.098 19142-19142/applicationId D/BeaconManager: consumer count is now: 1
09-02 02:12:43.098 19142-19142/applicationId D/AppStarter: Waiting for BeaconService connection
09-02 02:12:45.660 1010-1010/? D/JobServiceContext: handleServiceBound for 7966c9f #u0a309/208352939 applicationId/org.altbeacon.beacon.service.ScanJob
    Job cancelled while waiting for bind to complete. JobStatus{7966c9f #u0a309/208352939 applicationId/org.altbeacon.beacon.service.ScanJob u=0 s=10309 TIME=-2s586ms:-2s586ms PERSISTED READY}
09-02 02:12:46.281 2934-2934/? I/BeaconBle: ZERO_POWER is disabled.
    'L' hardware scan: scan stopped, no powered clients
    Places requested to stop scan
    Scan canceled successfully.
09-02 02:14:52.059 2934-2934/? I/BeaconBle: Client requested scan, settings=BleSettings [scanMode=ZERO_POWER, callbackType=ALL_MATCHES, reportDelayMillis=0, 1 filters, 0 clients, callingClientName=Places]
09-02 02:14:52.069 2934-2934/? I/BeaconBle: ZERO_POWER is disabled.
    'L' hardware scan: scan stopped, no powered clients
09-02 02:14:52.161 2934-18956/? I/PlaceInferenceEngine: No beacon scan available - ignoring candidates.
09-02 02:14:52.291 2934-18956/? I/PlaceInferenceEngine: No beacon scan available - ignoring candidates.
09-02 02:16:16.292 2934-2934/? I/BeaconBle: Client requested scan, settings=BleSettings [scanMode=LOW_LATENCY, callbackType=ALL_MATCHES, reportDelayMillis=0, 2 filters, 0 clients, callingClientName=ULR]
09-02 02:16:16.304 2934-2934/? I/BeaconBle: 'L' hardware scan: 6 filters, scanMode=2, reportdelay=0, callback type=1, #clients=3, workSource=WorkSource{}
09-02 02:16:16.306 2934-2934/? I/BeaconBle: Starting scan on OS scanner. BT state: 12
09-02 02:16:18.292 2934-2934/? I/BeaconBle: Client requested scan, settings=BleSettings [scanMode=ZERO_POWER, callbackType=ALL_MATCHES, reportDelayMillis=0, 2 filters, 0 clients, callingClientName=ULR]
09-02 02:16:18.303 2934-2934/? I/BeaconBle: Stopping scan on delegate scanner. BT state: 12
09-02 02:16:18.308 2934-2934/? I/BeaconBle: Resetting - new scanner available: true
    ZERO_POWER is disabled.
    'L' hardware scan: scan stopped, no powered clients

**Comment by garyburch** [comment]
How did you resolve the issue? I am getting same issue with Android 8.1. Please help. 
Below are the  logs : 
01-28 12:59:32.279  4106 26329 I PlaceInferenceEngine: No beacon scan available - ignoring candidates.
01-28 12:59:32.299  4106 26329 I PlaceInferenceEngine: No beacon scan available - ignoring candidates.
01-28 12:59:47.308  4106 22923 I PlaceInferenceEngine: No beacon scan available - ignoring candidates.
01-28 12:59:47.317  4106 22923 I PlaceInferenceEngine: No beacon scan available - ignoring candidates.
