### ISSUE TITLE
Update readme or documentation

### ISSUE THREAD

**Issue by iamdeveloper-lopez** [AltBeacon/android-beacon-library#737]
Please update readme/documentations based on the latest library versions.
Currently im using `2.15.1` version but the docs is quitely outdated.

**Comment by davidgyoung** [comment]
The latest docs from 2.15.1 are visbile here:
https://altbeacon.github.io/android-beacon-library/javadoc/reference/packages.html

If you tell me where you see the outdated docs, I'll delete them.
