### ISSUE TITLE
Update "Device Support For Beacon Transmission" page

### ISSUE THREAD

**Issue by breon** [AltBeacon/android-beacon-library#740]
Hi there!
It's been awhile since this page has been updated. We support broadcasting in our app and reference this page a bit for customer support.

https://altbeacon.github.io/android-beacon-library/beacon-transmitter-devices.html

Thanks
Breon

**Comment by davidgyoung** [comment]
Thanks for the reminder.  I just updated the page with the latest stats.

**Comment by wahram** [comment]
Hello,

is there a way to suggest new updates on the page?

**Comment by davidgyoung** [comment]
@wahram, as of this date, I think that this page is largely obsolete.  Nearly every Android phone and tablet released in the last couple of years has support for this feature.  Any device that does not have such support is more likely due to an accidental engineering flaw rather than intent.

**Comment by wahram** [comment]
Thank you for the answer!
