### ISSUE TITLE
When my application is in the background or even  it was terminated,is it possible to continue scanning?

### ISSUE THREAD

**Issue by TracyEminem** [AltBeacon/android-beacon-library#761]
When my application is in the background or even  it was terminated,is it possible to continue scanning?

**Comment by davidgyoung** [comment]
Yes, this is a core feature of the library.  Please read the docs [here](https://altbeacon.github.io/android-beacon-library/resume-after-terminate.html).

If you have other questions or need assistance using the library, please open a question on StackOverflow.com so we can keep this forum reserved for bug reports and library feature requests.
