### ISSUE TITLE
iOS devices distances parameters list

### ISSUE THREAD

**Issue by hadiidbouk** [AltBeacon/android-beacon-library#762]
Is there any list available for iOS devices like [this](https://github.com/AltBeacon/android-beacon-library/blob/master/src/main/resources/model-distance-calculations.json) list ?

I want to calculate the distance to a specific beacon using `CoreBluetooth` and `Eddystone`

**Comment by davidgyoung** [comment]
Sorry, there are no such coeficients available as this library targets Android.  You can calculate then yourself if you collect rssi/distance measurements for various iOS devices.

**Comment by hadiidbouk** [comment]
By following [this](https://altbeacon.github.io/android-beacon-library/distance-calculations2.html) right?

**Comment by davidgyoung** [comment]
Exactly.  I did do measurements and calcs for the iPhone 4s a long time
ago, and they were almost identical to the Nexus 4.

**Comment by davidgyoung** [comment]
You are right -- I trust the spreadsheet better than my memory!

**Comment by sipandswap1234** [comment]
Is there anyway we can advertise and scan in CoreBluetooth format using the AltBeacon library through Android devices? IF not can you suggest an approach to achieve the same?

**Comment by deeplathia** [comment]
Is there anyway we can advertise and scan in CoreBluetooth format using the AltBeacon library through Android devices? IF not can you suggest an approach to achieve the same?

@davidgyoung

**Comment by davidgyoung** [comment]
@deeplathia please help us keep this issue on topic.  Please post your question on StackOverflow.com as that is the appropriate forum for questions on how to use the library.
