### ISSUE TITLE
Beacon is not always detected on Android 7.0 and 8.0

### ISSUE THREAD

**Issue by antoncher93** [AltBeacon/android-beacon-library#763]
I have some beacons near (no more 1 m) the Samsung Galaxy S6 Android 7.0.
When I try to detect beacons with my App on AltBeacon Library I set the next settings for BeaconManager:

beaconManager.BeaconParsers
.Add(new BeaconParser().SetBeaconLayout("m:2-3=0215,i:4-19,i:20-21,i:22-23,p:25-25"));

 beaconManager.SetForegroundScanPeriod(500);
 beaconManager.SetForegroundBetweenScanPeriod(2000);
 beaconManager.SetBackgroundScanPeriod(2000);
 beaconManager.SetForegroundBetweenScanPeriod(0);

After StartRangingBeaconsInRegion(region) I detect all beacons but after 5 sec I get empty collection on didRangeBeaconsInRerion(collection, region).

After another 10-15 sec I detect all beacons again. And after 3-5 sec I get empty collection again...

I tried to detect beacons with another app on this library and its worked success.

### Expected behavior
I need always to detect beacons no less the 1-2 times per sec.

### Actual behavior
But I detect beacons during 3-4 sec and then cannot to detect during 10-15 sec.
### Mobile device model and OS version
Samsung Galaxy S6 Android 7.0

**Comment by davidgyoung** [comment]
This is a common problem when you customize scan periods.  

Understand that not 100% of packets can be detected even if scanning is always on.  The shorter you make scan periods, the less likely it is you will detect.  A good rule of thumb is that scan periods should be 10x the beacon's advertising rate for solid detections.  So if your beacon advertises at 10 Hz, the scan periods should be 1 sec or more (the default).  If your beacon advertises at 1 Hz, then the scan periods must be 10 sec or more for solid detections.

If you need more help customizing library settings for your specific use case, please open a question on StackOverflow.com.
