### ISSUE TITLE
Download link for android-beacon-library-2.15.2.aar returns 404 Not Found error

### ISSUE THREAD

**Issue by joew46167** [AltBeacon/android-beacon-library#774]
### Expected behavior
Download file

### Actual behavior
404 Error

### Steps to reproduce this behavior
Go to https://altbeacon.github.io/android-beacon-library/download.html and click the link for 2.15.2

The link says: https://github.com/AltBeacon/android-beacon-library/releases/download/2.14/android-beacon-library-2.15.1.aar

It should say https://github.com/AltBeacon/android-beacon-library/releases/download/2.15.2/android-beacon-library-2.15.2.aar

### Android Beacon Library version

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment]
Thanks for letting us know.  Fixed in #776
