### ISSUE TITLE
didExitRegion() is taking 10 seconds to detect 

### ISSUE THREAD

**Issue by secret-95** [AltBeacon/android-beacon-library#783]
### Android Beacon Library version

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment]
@dinakarms, you really cannot have an "immediate" exit region. Understand that the whole concept of exiting a region is amounts to not seeing the beacon in a certain time frame. You can reduce the intervals from 10 seconds, but it will increase false exits.

You can customize this interval with:

BeconManager.setRegionExitPeriod(5000l);, 

The bove reduces the time to 5s.
