### ISSUE TITLE
Device freezes when it enters beacon range after being in the background.

### ISSUE THREAD

**Issue by Briak** [AltBeacon/android-beacon-library#793]
Hey!
I had the same issue as #781. Then I tried a new experimental release 2.15.3-beta1. 
Now issue doesn't reproduce during background working when device is outside of the beacon range.
But when you enter beacon range the same issue start reproducing - device freezes and then crashes. 

### Expected behavior
Device shouldn't freeze and crash after entering beacon range.

### Actual behavior
When device is out of beacon range and if then it enters beacon range, device freezes and crashes after a few seconds.

### Steps to reproduce this behavior
Device is outside of the beacon range. 
Enter beacon range.
Device will freeze in few seconds and then crash.

### Mobile device model and OS version
Devices: Nokia 6 and Mi A1, OS version 8.1

### Android Beacon Library version
Experimental release 2.15.3-beta1

**Comment by davidgyoung** [comment]
Thanks for this report.  Can you please capture a LogCat excerpt of the crash?

**Comment by Briak** [comment]
Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 5.  Wait queue head age: 5598.4ms.)
    Load: 6.96 / 6.16 / 5.85
    CPU usage from 0ms to 20410ms later (2018-12-05 18:22:28.804 to 2018-12-05 18:22:49.215):
      138% 9070/nl.nieuwehelden.thevillage: 120% user + 17% kernel / faults: 589480 minor 36 major
      11% 1544/system_server: 4.1% user + 7.1% kernel / faults: 4010 minor 675 major
      7.2% 2707/com.google.android.gms: 4.8% user + 2.4% kernel / faults: 1723 minor 442 major
      4.3% 554/surfaceflinger: 1.8% user + 2.5% kernel / faults: 236 minor 10 major
      4% 20794/com.google.android.googlequicksearchbox:interactor: 3.1% user + 0.8% kernel / faults: 1816 minor 287 major
      3.9% 12037/com.android.chrome:sandboxed: 2.4% user + 1.5% kernel / faults: 1361 minor 309 major
      1.6% 1902/com.google.android.inputmethod.latin: 0.5% user + 1% kernel / faults: 1542 minor 384 major
      2% 522/android.hardware.graphics.composer@2.1-service: 0.7% user + 1.2% kernel / faults: 1 major
      1.9% 6607/kworker/u16:2: 0% user + 1.9% kernel
      1.6% 24809/com.android.bluetooth: 0.8% user + 0.7% kernel / faults: 2473 minor 101 major
      1.6% 2218/com.android.phone: 0.8% user + 0.7% kernel / faults: 1828 minor 402 major
      1.5% 28405/kworker/u16:3: 0% user + 1.5% kernel
      1.4% 1923/com.android.systemui: 0.8% user + 0.6% kernel / faults: 1288 minor 396 major
      1.2% 18384/kworker/u16:10: 0% user + 1.2% kernel
      1% 513/android.hardware.audio@2.0-service: 0.2% user + 0.8% kernel
      0.1% 730/media.codec: 0% user + 0.1% kernel / faults: 1500 minor 122 major
      0.7% 309/mmc-cmdqd/0: 0% user + 0.7% kernel
      0.7% 715/audioserver: 0.3% user + 0.3% kernel / faults: 89 minor 18 major
      0.3% 2460/com.evenwell.powersaving.g3: 0.1% user + 0.2% kernel / faults: 1657 minor 311 major
      0.7% 2560/com.evenwell.PowerMonitor: 0.4% user + 0.2% kernel / faults: 1582 minor 260 major
      0.6% 153/kswapd0: 0% user + 0.6% kernel
      0.6% 304/cfinteractive: 0% user + 0.6% kernel
      0.6% 10420/kworker/u17:4: 0% user + 0.6% kernel
      0.6% 420/logd: 0% user + 0.5% kernel / faults: 121 minor 9 major
      0.6% 2427/adbd: 0.1% user + 0.4% kernel / faults: 498 minor
      0.3% 2546/com.android.nfc: 0.1% user + 0.1% kernel / faults: 1658 minor 403 major
      0.5% 742/rild: 0.3% user + 0.2% kernel / faults: 60 minor
      0.5% 2499/com.google.android.gms.persistent: 0.4% user + 0% kernel / faults: 255 minor 1 major
      0.2% 2187/.dataservices: 0.1% user + 0.1% kernel / faults: 1680 minor 365 major
      0.2% 2577/com.evenwell.pushagent: 0.2% user + 0% kernel / faults: 1420 minor 316 major
      0.2% 2204/com.qualcomm.qti.telephonyservice: 0.1% user + 0.1% kernel / faults: 1642 minor 341 major
      0.2% 2595/com.evenwell.OTAUpdate: 0% user + 0.1% kernel / faults: 1731 minor 246 major
      0.3% 7/rcu_preempt: 0% user + 0.3% kernel
      0.3% 7394/mdss_fb0: 0% user + 0.3% kernel
      0% 723/media.extractor: 0% user + 0% kernel / faults: 1323 minor 78 major
      0.1% 10798/kworker/u17:8: 0% user + 0.1% kernel
      0.2% 526/android.hardware.power@1.0-service: 0% user + 0.1% kernel
      0.1% 10419/kworker/u17:3: 0% user + 0.1% kernel
      0.2% 514/android.hardware.bluetooth@1.0-service-qti: 0% user + 0.1% kernel
      0.2% 7620/com.android.vending: 0% user + 0.1% kernel / faults: 718 minor 108 major
      0.1% 10797/kworker/u17:5: 0% user + 0.1% kernel
      0% 370/kworker/5:1H: 0% user + 0% kernel
      0% 826/tombstoned: 0% user + 0% kernel / faults: 88 minor 46 major
      0.1% 6927/kworker/5:0: 0% user + 0.1% kernel
      0.1% 7809/VosMCThread: 0% user + 0.1% kernel
      0.1% 9056/logcat: 0% user + 0% kernel
      0% 10793/kworker/u17:0: 0% user + 0% kernel
      0% 10796/kworker/u17:2: 0% user + 0% kernel
      0.1% 28185/com.tripadvisor.tripadvisor: 0% user + 0% kernel / faults: 280 minor 166 major
      0% 45/rcuop/4: 0% user + 0% kernel
      0% 61/rcuop/6: 0% user + 0% kernel
      0%

**Comment by Briak** [comment]
Probably this part is related to the issue, but I'm not sure..

E/bt_btif: split_a2dp_status = false
E/bt_btif: split_a2dp_status = 0
E/bt_btif: btif_sm_get_state : Invalid handle
E/a2dp_vendor_aptx_encoder: A2DP_VendorLoadEncoderAptx: cannot open aptX encoder library libaptX_encoder.so: dlopen failed: library "libaptX_encoder.so" not found
E/a2dp_vendor_aptx: init: cannot load the encoder
E/a2dp_vendor_aptx_hd_encoder: A2DP_VendorLoadEncoderAptxHd: cannot open aptX-HD encoder library libaptXHD_encoder.so: dlopen failed: library "libaptXHD_encoder.so" not found
E/a2dp_vendor_aptx_hd: init: cannot load the encoder
E/bt_btif: Invalid cmd pending for ack
E/bt_btif: btif_sm_dispatch : Invalid handle
E/bt_btif: btif_a2dp_source_startup: A2DP Source media task already running
E/BluetoothDun: Could not bind to Bluetooth Dun Service with Intent { act=android.bluetooth.IBluetoothDun }
E/BluetoothHeadsetServiceJni: Failed report phone state change, status: 2

And after that I receive previously described ANR.

**Comment by Briak** [comment]
Just this part in addition to previous lines, nothing else. Unfortunately, nothing that could be directly related to the libs logs.

E/libc: failed to connect to tombstoned: Operation not permitted
E/zygote64: libdebuggerd_client: failed to read response from tombstoned: timeout reached?
E/libc: failed to connect to tombstoned: Operation not permitted
E/zygote64: libdebuggerd_client: received packet of unexpected length from tombstoned: expected 128, received -1

**Comment by davidgyoung** [comment]
everything looks normal until these two lines:

2018-12-06 12:01:59.573 1288-1288/nl.nieuwehelden.thevillage D/Callback: attempting callback via local broadcast intent: org.altbeacon.beacon.range_notification
2018-12-06 12:02:23.125 2026-2055/? E/STBMonitorQueue: restore data:/data/system/dropbox/data_app_crash@1544085473850.txt;1;1.0;org.altbeacon.beaconreference into shortQue queue...

The first line indicates that the library is about to send a didRangeBeaconsInRegion callback.  Then 24 seconds later there are lines indicating that the app crashes.  What happens in between?

Can you please add debug logging to the top of your didRangeBeaconsInRegion callback and verify it gets called and that debug line gets logged?  Showing your code for that method might be helpful, too.
