### ISSUE TITLE
Crash: java.lang.IllegalStateException: Bad magic number for Bundle: 0x45

### ISSUE THREAD

**Issue by tomacco** [AltBeacon/android-beacon-library#808]
This is a report that has come through Crashlytics. It has affected 4 users (out of about 5K active users this last month for that app) so it is not easy to reproduce.

Please find the stack trace attached
[altbeacon_crash.txt](https://github.com/AltBeacon/android-beacon-library/files/2720273/altbeacon_crash.txt)

Library version: 2.15.1

**Comment by davidgyoung** [comment]
This crash comes from the Android operating system itself.  It is trying to parse serialized data when trying to start up a scheduled job.  

Unfortunately that means there is nothing that can be done by this project to prevent such crashes from happening.
