### ISSUE TITLE
Beacon detection after doze mode

### ISSUE THREAD

**Issue by klimoma** [AltBeacon/android-beacon-library#831]
hello,
am trying to wake up my foreground service with http://www.davidgyoungtech.com/2017/08/07/beacon-detection-with-android-8#the-new-way-fast-detections

### Expected behavior
See first beacon and send PendingIntent to BroadcastReceiver which is starting my foreground service with BeaconConsumer.

### Actual behavior
After doze mode nothing is called.

### Steps to reproduce this behavior
Using same code which is here: http://www.davidgyoungtech.com/2017/08/07/beacon-detection-with-android-8#the-new-way-fast-detections
than put phone to doze mode and back
terminal:
> adb shell dumpsys deviceidle force-idle
> adb shell dumpsys deviceidle unforce

### Mobile device model and OS version
Nokia 5 - Android 8.1 

What should i do to start my foreground service when i see first beacon even if my app is killed/in doze mode/after doze mode?

Thank you

**Comment by davidgyoung** [comment]
It is correct that in Doze mode you will not get any library callbacks.   Once the phone exits doze callbacks will resume.  This is an OS restriction, sorry.
