### ISSUE TITLE
setBluetoothAddress not really set the MAC Address

### ISSUE THREAD

**Issue by TayfunCesur** [AltBeacon/android-beacon-library#832]
Hi.

I'm transmitting as Beacon like below;
```
beacon = Beacon.Builder()
                            .setBluetoothAddress("11:22:33:44:55:66")
                            .setManufacturer(0x0000)
                            .setId1("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee")
                            .setId2("1")
                            .setId3("2")
                            .setTxPower(-59)
                            .build()

beaconTransmitter.startAdvertising(beacon)

```

But when I scan it some other BLE Scanner application, I saw the beacon's MAC address is different from that I set ("11:22:33:44:55:66"). The output is below
[Output](https://i.hizliresim.com/P1G5m5.png)

How can I get this beacons mac address?

[According to your answer on stackoverflow](https://stackoverflow.com/questions/36673130/altbeacon-setbluetoothaddress-and-setbluetoothname), the mac address is changing every when I create a new beacon? 

Thanks

**Comment by davidgyoung** [comment]
Not all of the setters on the Beacon.Builder actually affect advertisements.  The setBluetoothAddress(...) is one of them -- it exists for mocking and internal library use, but has no effect on transmission.

Sorry, Android does not let you set the advertised MAC address.
