### ISSUE TITLE
Get Bluetooth Address

### ISSUE THREAD

**Issue by macirtr** [AltBeacon/android-beacon-library#834]
Hello;

mBeaconTransmitter1.startAdvertising(beacon1) 
after this command random mac address is generated. 

How i can get this address after startAdvertising?

PS : beacon1.getBluetoothAddress() it does not give the actual mac address.

**Comment by davidgyoung** [comment]
Sorry, this is an Android platform limitation.  There is no way to access the randomized transmission MAC.  The getBluetoothAddress() method is only populated for scanned beacons not transmitted ones.
