### ISSUE TITLE
Android Scanning working Fine with simulator ,not working with real beacon hardware

### ISSUE THREAD

**Issue by hafizazeem55** [AltBeacon/android-beacon-library#859]
### Expected behavior
I created a beacon scanning app in Android . The goal of the app is to identify whether the beacon is scanned or not

### Actual behavior
The app i have tested with beacon simulator app on android . One of my mobile acting as beacon beacon transmitter . The app works fine and detects beacon signals transmitted by mobile but when my client tested it with real beacons then the app didn't detect the beacon . The app is working fine with the simulator beacon app but not working with real beacons . 

### Mobile device model and OS version
Android 8.0 and Android 7.0

### Android Beacon Library version
2+ in Gradle Dependency

**Comment by davidgyoung** [comment]
This is most certainly a custom app and testing-specific issue and not an issue with the library itself, so this is not the proper forum for resolving this.  I see there is also a question on this [here](https://stackoverflow.com/questions/55724477/android-scanning-working-fine-with-simulator-not-working-with-real-beacon-hardw).  Let's continue troubleshooting there.
