### ISSUE TITLE
how to make stable scanner ibeacon? my scanner is not stable, and always gone

### ISSUE THREAD

**Issue by dimasoktanugraha** [AltBeacon/android-beacon-library#867]
### Android Beacon Library version

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment]
@dimasoktanugraha, if you want help building a custom app with the library, please open a question on Stackoverflow.com.  If you have a bug report to file, please fill out a proper request including precise steps to reproduce a specific problem.
