### ISSUE TITLE
unable to find which ibeacon is detected if i have registered 2 or 3. 

### ISSUE THREAD

**Issue by Eliaaana** [AltBeacon/android-beacon-library#875]
### Expected behavior
didenterregion should be called only for that beacon which is activated.
### Actual behavior
but didenterregion is called for that ibeacon too which is not activated.

### Steps to reproduce this behavior

Region region1 = new Region("8c52d286-fa22-42f2-8aef-b30a48279cab",
                null, null, null);
        Region region2 = new Region("fd77352b-1651-4ada-83ec-263fd6975722",
                null, null, null);

        ArrayList<Region> regions = new ArrayList<Region>();
        regions.add(region1);
        regions.add(region2);
        regionBootstrap = new RegionBootstrap(this, regions);
activated ibeacon is region1 with uuid 8c52d286-fa22-42f2-8aef-b30a48279cab but didenterregion and determinestate are returning other uuid in it, its strange. can you please help me to resolve this issue.

### Mobile device model and OS version
android device samsung s7 edge

### Android Beacon Library version
2.16.1

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment]
When defining a Region, the first parameter in the constructor is unique string key used to identify the region for start/stop purposes.  It is NOT a beacon identifier.  So instead of this:

```
Region region1 = new Region("8c52d286-fa22-42f2-8aef-b30a48279cab",
null, null, null);
```

Use something like this:

```
Region region1 = new Region("my-region-1", "8c52d286-fa22-42f2-8aef-b30a48279cab",
null, null);
```
