### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by qflbai** [AltBeacon/android-beacon-library#892]
### Android Beacon 2.16.2

![image](https://user-images.githubusercontent.com/23705172/58928625-d8d8d580-8785-11e9-8a71-1642c4c7011e.png)

**Comment by davidgyoung** [comment]
Same basic root cause as #887.  Attempted fix in #890

**Comment by davidgyoung** [comment]
@qflbai, can you please try this beta release that includes the fix for this issue and let me know if it makes the crash go away?

https://github.com/AltBeacon/android-beacon-library/releases/tag/2.16.3-beta1
