### ISSUE TITLE
I can't download .aar

### ISSUE THREAD

**Issue by acaliaro** [AltBeacon/android-beacon-library#899]
### Expected behavior

When I go to Download page and I try to download an .aar, I would like to download the file
https://github.com/AltBeacon/android-beacon-library/releases/download/2.14/android-beacon-library-2.16.2.aar

### Actual behavior

404

### Steps to reproduce this behavior

click on the link

### Android Beacon Library version

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment]
Fixed here: https://github.com/AltBeacon/android-beacon-library/commit/2dbbd09b1236c6e4f79624a94ded80dfa6bf781d
