### ISSUE TITLE
Can this module scan period in 100ms?

### ISSUE THREAD

**Issue by Sunnystaste** [AltBeacon/android-beacon-library#901]
From the README.md, I know that your recommended frequency range is 1 Hz. Can I set the scanning time to 100 milliseconds? I want to get RSSI data as soon as possible and they have to be real-time data.

By the way, I have set the Emission frequency of iBeacon in 10 HZ.

//the code I used
beaconManager.setBackgroundBetweenScanPeriod(0);
beaconManager.setBackgroundScanPeriod(100);

**Comment by davidgyoung** [comment]
@Sunnystaste, the library supports setting the scanning rate to 100ms, but there is a high chance of missing  individual detections from a beacon transmitting at 10Hz.  I would set the interval to the longest period your use case allows.

This question is about how to use the library so it is best asked at StackOverflow.com so we can keep this forum reserved for bug reports and feature requests.  If you have followup questions, please post a question there.
