### ISSUE TITLE
Why rssi looks like period?

### ISSUE THREAD

**Issue by Sunnystaste** [AltBeacon/android-beacon-library#903]
![image](https://user-images.githubusercontent.com/37181135/60491344-24c26000-9cdb-11e9-8e4e-50a78e2e67d7.png)

This picture is a rssi picture of an iBeacon. iBeacon broadcast frequency is 10 Hz. The receiving period of phone is 110ms. The picture looks like period and the fluctuation of the signal is about 15db. It is a disaster to indoor location. Why the rssi signal is period? It is the problem of program or the problem of iBeacon?

**Comment by fkruta** [comment]
welcome to the joys of BLE indoor location. The fluctuation are normal due to most likely to MultiPath, now in your case they are significantly big. You might have a damage circuit either on the phone or the beacon.

**Comment by davidgyoung** [comment]
IMO that pattern looks like the delta RSSI from scanning on different BLE advertising channels.  See my answer here:  https://stackoverflow.com/questions/49634513/is-there-an-explanation-for-the-regular-oscillation-experienced-in-bluetooth-rss

Please post followup questions on StackOverflow.com as that is the appropriate forum for questions like this.  This forum is reserved for bug reports and feature requests.
