### ISSUE TITLE
Cannot Scan in Foreground

### ISSUE THREAD

**Issue by mspapant** [AltBeacon/android-beacon-library#906]
### Expected behavior
Since i use a foreground service, i suppose that library should discover a beacon instantly.

### Actual behavior
Not any beacon discovered

### Steps to reproduce this behavior
I use the following code:
` 
   @Override
    public void onCreate() {
        super.onCreate();
        
        beaconManager = org.altbeacon.beacon.BeaconManager.getInstanceForApplication(this);
        beaconManager.getBeaconParsers().clear();
        beaconManager.getBeaconParsers().add(new BeaconParser().setBeaconLayout("m:2-3=beac,i:4-19,i:20-21,i:22-23,p:24-24,d:25-25"));
        beaconManager.getBeaconParsers().add(new BeaconParser().setBeaconLayout("s:0-1=feaa,m:2-2=00,p:3-3:-41,i:4-13,i:14-19"));
        beaconManager.getBeaconParsers().add(new BeaconParser().setBeaconLayout("m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24,d:25-25"));
        beaconManager.getBeaconParsers().add(new BeaconParser().setBeaconLayout("m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24"));
    }

	public void startListening() {
        beaconManager.unbind(this);
        Notification.Builder builder = new Notification.Builder(this);
        builder.setSmallIcon(R.drawable.ic_logo);
        builder.setContentTitle("Scanning for Beacons");
        builder.setContentText("Press here to stop scanning");
        Intent intent = new Intent(this, POIActivity.class);
        PendingIntent pendingIntent = PendingIntent.getActivity(
                this, 0, intent, PendingIntent.FLAG_UPDATE_CURRENT
        );
        builder.setContentIntent(pendingIntent);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            NotificationChannel channel = new NotificationChannel("My Notification Channel ID",
                    "My Notification Name", NotificationManager.IMPORTANCE_DEFAULT);
            channel.setDescription("My Notification Channel Description");
            NotificationManager notificationManager = (NotificationManager) getSystemService(
                    Context.NOTIFICATION_SERVICE);
            notificationManager.createNotificationChannel(channel);
            builder.setChannelId(channel.getId());
        }
        beaconManager.enableForegroundServiceScanning(builder.build(), 456);
        beaconManager.setEnableScheduledScanJobs(false);
        beaconManager.setBackgroundBetweenScanPeriod(0);
        beaconManager.setBackgroundScanPeriod(0);
        beaconManager.setBackgroundMode(false);

        BeaconManager.setDebug(true);

        beaconManager.bind(this);
    }

	@Override
    public void onBeaconServiceConnect() {
        beaconManager.addRangeNotifier(this);
    }

	@Override
    public void didEnterRegion(Region region) {
        // In this example, this class sends a notification to the user whenever a Beacon
        // matching a Region (defined above) are first seen.
        Log.d("App", "did enter region.");
        Intent intent = new Intent(this, FAQActivity.class);
        intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        startActivity(intent);
    }

    @Override
    public void didExitRegion(Region region) {
        Log.d("App", "didExitRegion");
    }

    @Override
    public void didDetermineStateForRegion(int i, Region region) {
        Log.d("App", "didDetermineStateForRegion");
    }

    @Override
    public void didRangeBeaconsInRegion(Collection<Beacon> collection, Region region) {
        Log.d("App", "didRangeBeaconsInRegion");
    }`

### Mobile device model and OS version
Huwai p20, android 8.0

### Android Beacon Library version
2.15.1

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment]
In the code shown, I do not see any calls to `startRangingBeaconsInRegion(...)`.  You will need to add this to get ranging callbacks.

@mspapant, if you need additional help getting your program to work, please open a new question on StackOverflow.com.  That is the proper forum for this kind of assistance.  This forum is reserved for feature requests and bug reports that are reproducible with the library reference app.
