### ISSUE TITLE
Saving logs into a file

### ISSUE THREAD

**Issue by TayfunCesur** [AltBeacon/android-beacon-library#907]
Hi David,

I have made some researches at altbeacon.github.io and also github issues but unfortunately I couldn't find any api info about saving logs. 

I already use BeaconManager.setDebug(true)
But how can I save that logs into a file ?
Is there any api to do this easily or should I have to do myself?

Thanks

**Comment by davidgyoung** [comment]
Yes, I typically use adb logcat > someFile.txt.
You can also tail that file in another console window to monitor it while
the log is writing.

**Comment by TayfunCesur** [comment]
Thank you David. I also searched the Android Central Log System. I can share what I learned for those who are curious about this.

Android Central Log System keeps the logs until buffer size reaches. The buffer size can be change under developer options up to 16 MB. Mine is 256kb and I can get about last 5 hours log.

Thank you.

**Comment by prasad456** [comment]
how to stop logging i want to aviod scanState.save()
