### ISSUE TITLE
Scan is failing on app in background (Xiaomi Redmi 4X)

### ISSUE THREAD

**Issue by KeyStarr** [AltBeacon/android-beacon-library#909]
### Expected behavior
Library scanning should continue after an app is gone to the background.

### Actual behavior
1. On entering the background the next scan is registered to be after 300 000 ms. 
2. On first scan the following log appears:

Only library log
[xiaomi_redmi_4x_scan_error_log.txt](https://github.com/AltBeacon/android-beacon-library/files/3381760/xiaomi_redmi_4x_scan_error_log.txt)

Whole system log in adjacent 5 seconds to the crash:
[whole_error_log.txt](https://github.com/AltBeacon/android-beacon-library/files/3381829/whole_error_log.txt)

The key line there is: `E/CycledLeScannerForLollipop: Scan failed: app cannot be registered`

### Steps to reproduce this behavior
1. Get a xiaomi redmi 4x phone (Android 7.1.2)
2. Install reference app
3. Grant location, enable bluetooth
4. Send app in background

### Mobile device model and OS version
Tested on TWO Redmi 4x devices. Doesn't seem to appear on any other device that we've tested on (Samsung etc.)

### Android Beacon Library version
2.16.2
Tested on the appication reference (master branch).

I have read all posts/issues that i found matching the description including this:
https://stackoverflow.com/questions/46376251/cycledlescannerforlollipop-scan-failed-app-cannot-be-registered-alt-beacon-li/46386224#46386224
But found no proper explanation / solution.
Toggling bluetooth doesn't work, BluetoothMedic doesn't help.

**Comment by davidgyoung** [comment]
This is the same core issue as #643.  We need assistance characterizing what appears to be a custom Xiaomi/Redmi behavior blocking some BLE scans in the background.  Please comment on the linked issue.
