### ISSUE TITLE
Unable to detect beacon when target is sdk 29

### ISSUE THREAD

**Issue by filippodelfra** [AltBeacon/android-beacon-library#920]
### Expected behavior
Once called startMonitoringBeaconsInRegion() I expect to get a callback my MonitorNotifier object.

### Actual behavior
If the target is SDK 29, I'm not receiving any callback on my MonitorNotifier regardless of the permission type (background scan allowed or foreground only)

### Mobile device model and OS version
Google Pixel, Google Pixel XL, Android 10

### Android Beacon Library version
2.16.2

**Comment by davidgyoung** [comment]
Version 2.16.2 of the library does support Android Q with a target SDK of 29.  The latest version of the [reference app](https://github.com/AltBeacon/android-beacon-library-reference/) will detect beacons in the foreground and background and get callbacks on a MonitorNotifier.  

However, you will need to make sure you update your app targeting ASK 29 in a number of ways.  A diff of the changes needed to make the reference app support this may be helpful [here](https://github.com/AltBeacon/android-beacon-library-reference/commit/04303b4ff95e00d79f50c73c0824017087aa6b41#diff-d2a57dc1d883fd21fb9951699df71cc7)

A quick summary of the changes are:

1. Add ACCESS_FINE_LOCATION permission to the AndroidManifest.xml (Before Android Q, only ACCESS_COARSE_LOCATION was needed.)
2. Add ACCESS_BACKGROUND_LOCATION permission to the AndroidManifest.xml if you want to detect in the background
3. Change the dynamic permission requesting logic to request both of the above.

The library documentation still needs some updates here to communicate all this.  I'll be updating that in coming days.
