### ISSUE TITLE
how to set beacon mac address for android as i am advertising the changes every 2 seconds and the mac id seems to be changing and every 2 seconds i am stopping the old beacons but it is still there at the time of scanning

### ISSUE THREAD

**Issue by sonychoudhary** [AltBeacon/android-beacon-library#922]
### Android Beacon Library version

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment]
Android periodically rotates the BLE MAC address during advertising.  This feature is built-in to the operating system and there are no public APIs to change that.  See here: https://stackoverflow.com/questions/42136261/does-mac-id-broadcasted-in-eddystone-beacon-change/42139586#42139586

If you have more questions please post them on StackOverflow.com, as that is the proper forum for library support.  This forum is reserved for reproducible bug reports and feature requests.
