### ISSUE TITLE
remove manufacturer id from altbeacon

### ISSUE THREAD

**Issue by sonychoudhary** [AltBeacon/android-beacon-library#923]
is it possible to remove manufacture id as i dont want it in my app the first 2 bytes are taken as 0000 if i m not providing any value can it be removed i am using flutter

**Comment by davidgyoung** [comment]
The manufacturer Id field is part of the Bluetooth LE spec, and must be present for Bluetooth chips to detect manufacturer advertisement frames.  You can set the value to zero, but you cannot remove the field.  

If you have follow-up questions please ask in StackOverfliw.com.
