### ISSUE TITLE
Region Constructor with List of Identifiers not working

### ISSUE THREAD

**Issue by Wilson13** [AltBeacon/android-beacon-library#927]
### Expected behavior
startRangingBeaconsInRegion to detect beacons with Region provided.

### Actual behavior
No beacons were detected at all.

### Steps to reproduce this behavior
Instantiate Region object by calling one of the two constructors which accepts List<Identifier> as parameter.

i.e. public Region(String uniqueId, List<Identifier> identifiers) 

OR

public Region(String uniqueId, List<Identifier> identifiers, String bluetoothAddress) 

### Mobile device model and OS version
Google Pixel 2 XL, Android 10.

### Android Beacon Library version
2.16.3

**Comment by davidgyoung** [comment]
I cannot reproduce this behavior using the [reference app](https://github.com/altBeacon/android-beacon-library-reference) modified as so:

```
        Log.d(TAG, "setting up background monitoring for beacons and power saving");
        // wake up the app when a beacon is seen
        ArrayList<Identifier> identifiers = new ArrayList<Identifier>();
        identifiers.add(Identifier.parse("2F234454-CF6D-4A0F-ADF2-F4911BA9FFA6"));
        identifiers.add(Identifier.parse("1"));
        identifiers.add(Identifier.parse("1"));
        Region region = new Region("backgroundRegion", identifiers);
        //Region region = new Region("backgroundRegion",
        //        null, null, null);
        regionBootstrap = new RegionBootstrap(this, region);
```

When I run the above code, and transmit a beacon with identifiers 2F234454-CF6D-4A0F-ADF2-F4911BA9FFA6 1 1, I immediately get a didDetermineStateForRegion event with a state of inside.

Please check your code, and if you can provide a test case to reproduce with the reference app, reopen this issue.
