### ISSUE TITLE
Crash when in background

### ISSUE THREAD

**Issue by Nicolo-sudo** [AltBeacon/android-beacon-library#932]
Hi there!

I'm developing an app with the AltBeacon Library but unfortunately I'm having a big problem.
My app now is fully working only in foreground. The code wich I'm using is the same of the reference application but with some modifications:

> beaconManager.setBackgroundScanPeriod(1100l);
> beaconManager.setBackgroundBetweenScanPeriod(30000l);

My problem is that when the app enters in background and the library found a beacon in a region, the app crashes. In particular, the os shows "The app is not responding" popup.
I suppose the problem is during the "didEnteredInRegion" and "didExitRegion" while the app is in background mode but I'm not sure.

Else if I open the app the "didEnteredInRegion" and "didExitRegion" are working properly without any problems. If I start ranging and then i close the app (without killing it) everything works fine.
The problem is only when I'm not ranging and I'm in background with the app closed (monitoring). 

I'm using two devices to test this app.
- Samsung Galaxy S9 (9.0)
- Huawei p8 (6.0)

I heard that the behavior Huawei devices is strange so that's why I'm using a samsung device.

Can someone help me to resolve this issue? Thanks in advance!

**Comment by davidgyoung** [comment]
I suspect this is an issue with the specific code inside the didEnterRegion/didExitRegion callbacks.   I'd suggest you post that code on StackOverflow.com where I would be glad to help you troubleshoot

**Comment by Nicolo-sudo** [comment]
Hi, I have posted a question here:

https://stackoverflow.com/questions/58934627/altbeacon-application-crashes-while-in-background

If you have time, please check it out

Thanks.
