### ISSUE TITLE
didRangeBeaconsInRegion gets 0 beacons when phone is locked on Xiaomi Redmi Note 8 pro

### ISSUE THREAD

**Issue by surajWebclues** [AltBeacon/android-beacon-library#951]
### Expected behavior

I have foreground service that implements BeaconConsumer. The service is running when phone is locked. If it finds beacon in vicinity it should in didRangeBeaconsInRegion. 

### Actual behavior

When phone is locked list is always returned 0. I have 3 beacons around. When the and no usb be cable connected it get 0 beacons always. When app is locked and usb cable is connected it gets all the beacons. 

### Mobile device model and OS version

Device Model Redmi Note 8 pro (M1906G7I)
os Android 9

### Android Beacon Library version
2.16.4

**Comment by davidgyoung** [comment]
This is the same core issue as #643.  We need assistance characterizing what appears to be a custom Xiaomi/Redmi behavior blocking some BLE scans in the background.  Please comment on the linked issue.
