### ISSUE TITLE
I can't detect beacons in the  kindelf device is not pair No beacons detected

### ISSUE THREAD

**Issue by PongPloy2016** [AltBeacon/android-beacon-library#955]
kindelf  is mean device id for Intelligent anti-lost: When the connection is disconnected, the phone and device will alarm at the same time to ensure that the belongings will not be lost. 

kindelf is play store : https://play.google.com/store/apps/details?id=com.lenzetech.kindelf&hl=th 

and when used connected beacon other but  can be used normally 
<img width="1109" alt="Screen Shot 2563-03-17 at 14 00 31" src="https://user-images.githubusercontent.com/8625469/76830367-b23ce480-6857-11ea-8463-1168158da6c1.png">

but when entering this library to use And noticed that. this No beacons detected 

<img width="1312" alt="Screen Shot 2563-03-17 at 13 58 21" src="https://user-images.githubusercontent.com/8625469/76830248-7275fd00-6857-11ea-8ff7-f4bc3087001e.png">

i set up code this : 

//setUpBeacon 

`    open fun setUpBeacon(applicationContext: Application) {
        setUpbindServise()
        backgroundPowerSaver = BackgroundPowerSaver(applicationContext);
        mBeaconManager?.getBeaconParsers()
            ?.add(BeaconParser().setBeaconLayout("m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24"))
        val identifiers = ArrayList<Identifier>()
        mRegion = Region(ALL_BEACONS_REGION, identifiers)
        mBeaconManager?.setForegroundScanPeriod(DEFAULT_SCAN_PERIOD_MS)
        mBeaconManager?.backgroundScanPeriod = 1100L
        mBeaconManager?.foregroundScanPeriod = 1100L
        mBeaconManager?.backgroundBetweenScanPeriod = 0
        mBeaconManager?.foregroundBetweenScanPeriod = 1100L
        mBeaconManager?.bind(this)
    }

    override fun onBeaconServiceConnect() {
        Log.e(TAG, "onBeaconServiceConnect")

        if (Build.VERSION.SDK_INT == Build.VERSION_CODES.P) {
            try {
                // mBeaconManager = BeaconManager.getInstanceForApplication(context!!);
                checkNotiSound = true
                mBeaconManager!!.startRangingBeaconsInRegion(mRegion!!)

                //  mContext!!.toast(getString(R.string.start_looking_for_beacons))

            } catch (e: RemoteException) {
                //  context!!.toast(e.message!!)
            }

            mBeaconManager!!.addRangeNotifier(this)

            //TODO :: check toast anorid p
            //  Toast.makeText(applicationContext, "android P" + "\t" , Toast.LENGTH_LONG).show()

        } else {

            //android  7 , 7.1  to Test device

            mBeaconManager!!.startRangingBeaconsInRegion(mRegion!!)

            mBeaconManager?.addRangeNotifier(RangeNotifier { beacons, region ->
                Log.d("beaconManager", "didRangeBeaconsInRegion service" + beacons.size)
                Log.e("beaconManager prompt", "didRangeBeaconsInRegion $beacons")

                //TODO :: check toast anorid 7

                // Toast.makeText(applicationContext, "android 7" + "\t" + beacons.toString(), Toast.LENGTH_LONG).show()
                getBeaconMutableCollection(beacons)

            })

            checkNotiSound = true

            startRegionSet()

        }

    }`
this is. detail doc : 

![kindelf](https://user-images.githubusercontent.com/8625469/76832575-26798700-685c-11ea-9be5-b27e8cab38f6.jpg)

Thank you

**Comment by davidgyoung** [comment]
Assisting in setting up a project to use a specific manufacturer's beacon is beyond the scope of this form.   (This forum is reserved for bug reports and feature requests.)

I suggest you re-format this question to meet the standards of StackOverflow.com and post the question there.  I will be glad to assist in that forum.  Please include in your question:

* Have you tried an off-the-shelf beacon locator app for Android like BeaconScope?  Does that app detect this device?
* Have you tried to use a beacon simulator app on a different phone (e.g. BeaconScope for Android or Locate Beacon for iOS) to see if your program can detect that beacon?

**Comment by PongPloy2016** [comment]
OK  bro Thank you to Answer  suggest  ^__^

I copy source code and try use  ' '  insert code but it can not reformate as standard code and I think used  kindelf device, not beacons because it is  Bluetooth on deviceV.4.0. As announced in the document sheet I research used app other together with found  kindelf device (in photo)

![90141256_240350683807546_2808887342905950208_n](https://user-images.githubusercontent.com/8625469/76922260-beca4700-6902-11ea-879d-8b328b933450.jpg)

this name is "iTag" is Protocal : Low Energy
