### ISSUE TITLE
Still not solved in 2020 despite previous patches : Null Pointer Exception when splitting beacon commands into two files

### ISSUE THREAD

**Issue by FalconBFR** [AltBeacon/android-beacon-library#958]
### Expected behavior
Expected Behavior: Main activity, onClick listeners calls service onstartcommand function, Service onstartcommand function calls MainActivity.startBeaconMonitorring (Dynamic, not static, returns void) without any errors
### Actual behavior

Produces the error: Null pointer exception :

Even tried declaring Region beaconRegion as : 
`beaconRegion = new Region("MyBeacons", Identifier.parse("0AC59CA4-DFA6-442C-8C65-22247851344C"),
                    Identifier.parse("4"),Identifier.parse("200"));`

java.lang.NullPointerException: Attempt to invoke virtual method 'void org.altbeacon.beacon.BeaconManager.startMonitoringBeaconsInRegion(org.altbeacon.beacon.Region)' on a null object reference

### Steps to reproduce this behavior
Dear all, this issue is still not solved in 2020, using the latest library. 
Specifically, when I call the function from anther file in the same directory (it is specifically a service class, but I tried a normal class and it didn't work either), it still creates this 'Null Pointer Error'. There is no problem when calling it within the file. Here is the method I called it:

**Before splitting it into two files, the function was (in main activity):**

startButton.setOnClickListener((v) -> { startBeaconMonitoring(); });

**No change to the function below:, for refeerence**

public void startBeaconMonitoring() {
        Log.d(TAG, "startBeaconMonitoring called");
        System.out.println("START BEACON MONITORING FUNCTION");
        try {
            //beaconRegion = new Region("MyBeaconStuff", null, null, null);
            //beaconRegion = new Region(null);
            beaconManager.startMonitoringBeaconsInRegion(beaconRegion);
            beaconManager.startRangingBeaconsInRegion(beaconRegion);
            transmitbeacon();
        } catch (RemoteException e) {
            e.printStackTrace();
        }
    }

**New Code:

Main Activity:** 
...
        startButton.setOnClickListener((v) -> {
            startService(new Intent (this, beaconcontrolservice.class));
        });
...

**In the file : beaconcontrolservice.java (same directory):**

package com.example.beaconwithoracletrainingvideo;

import android.app.Service;
import android.content.Intent;
import android.os.IBinder;

import androidx.annotation.Nullable;

public class beaconcontrolservice extends Service {
    @Nullable
    @Override
    public IBinder onBind(Intent intent) {
        return null;
    }

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        MainActivity MainActivity = new MainActivity();
        //return super.onStartCommand(intent, flags, startId);
        MainActivity.startBeaconMonitoring();
        return START_STICKY;
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
    }
}

**Back to Main activity**

    public void startBeaconMonitoring() {
        Log.d(TAG, "startBeaconMonitoring called");
        System.out.println("START BEACON MONITORING FUNCTION");
        try {
            //beaconRegion = new Region("MyBeacons", Identifier.parse("0AC59CA4-DFA6-442C-8C65-22247851344C"),
              //      Identifier.parse("4"),Identifier.parse("200"));
            //beaconRegion = new Region("MyBeaconStuff", null, null, null);
            //beaconRegion = new Region(null);
            beaconManager.startMonitoringBeaconsInRegion(beaconRegion);
            beaconManager.startRangingBeaconsInRegion(beaconRegion);
            transmitbeacon();
        } catch (RemoteException e) {
            e.printStackTrace();
        }
    }

### Mobile device model and OS version
Xiaomi 8, Android 10
The device does not exactly matter in this case
It is a previous issue that was claimed to be solved. However, as a beginner, I do require some assistance if I did make a mistake. I will then remove this issue to comply with your guidelines if it is my operation mistake. Many thanks in advance.

Clement,
14 y/o from HKSAR, China

### Android Beacon Library version
2.16.x (Latest, auto download from your website from Gradle)

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com. **Noted**

**Comment by davidgyoung** [comment]
@FalconBFR, please include a stack trace of your NullPointerException.
