### ISSUE TITLE
Background execution not allowed

### ISSUE THREAD

**Issue by wld91** [AltBeacon/android-beacon-library#968]
After the application is manually killed (by swipe, not force stop).
### Expected behavior
"Connect/disconnect the device to a charger to immediately be able to resume detections"
### Actual behavior
The application doesn't start immediately (only after 10 minutes as usual).

The following logs are printed in logcat:
`W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.ACTION_POWER_CONNECTED flg=0x4000010 (has extras) } to com.blesm/org.altbeacon.beacon.startup.StartupBroadcastReceiver
W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.ACTION_POWER_CONNECTED flg=0x4000010 (has extras) } to com.bridou_n.beaconscanner/org.altbeacon.beacon.startup.StartupBroadcastReceiver
W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.ACTION_POWER_CONNECTED flg=0x4000010 (has extras) } to com.radiusnetworks.locate/org.altbeacon.beacon.startup.StartupBroadcastReceiver
W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.ACTION_POWER_DISCONNECTED flg=0x4000010 (has extras) } to com.blesm/org.altbeacon.beacon.startup.StartupBroadcastReceiver
W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.ACTION_POWER_DISCONNECTED flg=0x4000010 (has extras) } to com.bridou_n.beaconscanner/org.altbeacon.beacon.startup.StartupBroadcastReceiver
W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.ACTION_POWER_DISCONNECTED flg=0x4000010 (has extras) } to com.radiusnetworks.locate/org.altbeacon.beacon.startup.StartupBroadcastReceiver`
### Steps to reproduce this behavior
I use the reference application example without foreground scanning.
Start the application, kill it using swipe action, connect and disconnect the charger.
### Mobile device model and OS version
Huawei Mate 20 Pro, Android 10
### Android Beacon Library version
2.16.4
IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment]
The POWER_CONNECTED launch of the library only works on Android 7.x and earlier.  After Android 8 you have two choices:

(1) Accept the default background scanning every ~15 minutes using the Android Job Scheduler
(2) Use a Foreground Service as described in the documentation (reference app has commented out code for starting this up.)

If you use a foreground service, swiping the app off the system tray will leave the foreground service running.
