### ISSUE TITLE
Distance estimate: model-distance-calculations.json Not found 

### ISSUE THREAD

**Issue by shanmugpriyan306** [AltBeacon/android-beacon-library#977]
Un able to access  list of models with specific calculations available in the config file,

Getting 404 not found error.
![404_not_found](https://user-images.githubusercontent.com/1314621/83508943-4712be00-a4e8-11ea-853e-fed52650f5ee.PNG)

**Comment by davidgyoung** [comment]
That is an old link.  Can you please tell me where you found it and I will fix. 

https://github.com/AltBeacon/android-beacon-library/blob/master/lib/src/main/resources/model-distance-calculations.json

**Comment by shanmugpriyan306** [comment]
Thanks Works fine.
