### ISSUE TITLE
Newer models are not available

### ISSUE THREAD

**Issue by shanmugpriyan306** [AltBeacon/android-beacon-library#979]
Why newer model configuration are not available on model-distance-calculations.json?. It looks like library is not maintained well.

https://github.com/AltBeacon/android-beacon-library/blob/master/lib/src/main/resources/model-distance-calculations.json

**Comment by davidgyoung** [comment]
@shanmugpriyan306 please volunteer to do measurements with newer models.  Instructions are [here](https://altbeacon.github.io/android-beacon-library/distance-calculations.html).  Understand that this is a volunteer effort -- there is no big corporation buying devices and paying people to take measurements.
