### ISSUE TITLE
Distance Calculation in AltBeacon is really disastrous

### ISSUE THREAD

**Issue by Codejacks** [AltBeacon/android-beacon-library#986]
### Expected behavior
Show approximate values in +- 10% or 20% in range for distance of 2 M

### Actual behavior
For 2 meter  , the distance returned is around 4.6 and for 1 Mtr its around 6.8 mtr.
The distance keeps on decreasing for increasing delta between beacons.
### Mobile device model and OS version
Xiomi Redmi 5 and Realme 5

### Android Beacon Library version
2.16

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment]
Please read the library documentation on the limits of this technology: https://altbeacon.github.io/android-beacon-library/distance-calculations.html. In general, budget phones have weak receivers and overestimate distance unless custom coefficients have been added to the library for the specifics models.

To get decent results with that phone model you will have to do measurements to get model-specific distance coefficients added to the library database for your phone models.  That link describes the procedure how you can volunteer to do that.
