### ISSUE TITLE
Beacon doesn't transmit BluetoothName, ParserIdentifier and DataFields

### ISSUE THREAD

**Issue by skullwing521** [AltBeacon/android-beacon-library#987]
The beacon advertised doesn't transmit BluetoothName, ParserIdentifier and DataFields
I have tried this with altbeacon and iBeacon format

I am advertising following Beacon:

```
val beacon = Beacon.Builder()
            .setId1("2e028be2-f449-4ad7-a651-04083f9d5225")
            .setId2("0")
            .setId3("0")
            .setBluetoothName("name")
            .setParserIdentifier("ident")
            .setDataFields(listOf(1,2,3))
            .setTxPower(-59)
            .build()

beaconTransmitter?.startAdvertising(beacon, object : AdvertiseCallback() {...}
```

### Expected behavior

I would expect that the data I send is also transmitted

```
beaconManager.addRangeNotifier { beacons, _ ->
            beacons.forEach { beacon: Beacon ->
                val bluetoothName = beacon.bluetoothName
                val parserIdentifier = beacon.parserIdentifier
                val dataFields = beacon.dataFields

                bluetoothName == "name" //true
                parserIdentifier == "ident" // true
                dataFields == [1, 2, 3] //true
            }
        }

```

### Actual behavior

But actual these fields are null:

```
 bluetoothName == null //true
parserIdentifier == null // true
dataFields == null //true
```

### Steps to reproduce this behavior

Run code above with two devices, one advertising, the other ranging 

### Mobile device model and OS version

Google Pixel 3
Samsung Galaxy A20e
Huawei P30 lite

### Android Beacon Library version

2.18-beta1

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment]
Not every field in the Beacon class gets advertised.  In general only the identifiers, txPower and data fields get advertised.  As far as the rest go:

- bluetoothName is only populated (sometimes) after scanning, and only if the BLE device detected with that beacon has also recently advertised its name in a separate packet.  Android does not let you change the bluetooth name in an advertisement -- this is a global setting on the phone.  See here: https://www.droidviews.com/how-change-phone-name-in-wifi-and-bluetooth-connection-on-samsung-galaxy-devices/#:~:text=Changing%20Bluetooth%20Name,-To%20be%20able&text=Open%20Settings%20on%20your%20Android,or%20tablet%20and%20tap%20OK.

- parserIdentifier is populated after scanning to tell you which beacon parser matched.  It is only populated if you set a parserIdentifier on the BeaconParser you set up.  This is useful if you have multiple parsers active.  But this is certainly not information that is transmitted over the air in any way.

- dataFields is transmitted, but the number of data fields transmitted depends on the format.  iBeacon has no data fields.  AltBeacon has one data field.  Eddystone-TLM has several data fields.  If you try to transmit a beacon with more data fields set than the format allows then fewer will be transmitted.
