### ISSUE TITLE
Fatal Exception: java.lang.IndexOutOfBoundsException when trying to wake up screen on beacon found

### ISSUE THREAD

**Issue by kashiftasneempro** [AltBeacon/android-beacon-library#989]
### Expected behavior
App should not crash
### Actual behavior
App crashes with the above mentioned exception
### Steps to reproduce this behavior
Setup project and register for RangeNotifier. Inside it, I check whether screen is off. If it's off, I wake it up using:

```
val wakeLock = powerManager.newWakeLock(PowerManager.FULL_WAKE_LOCK or PowerManager.ACQUIRE_CAUSES_WAKEUP or PowerManager.ON_AFTER_RELEASE, "appname::WakeLock")

wakeLock.acquire()
wakeLock.release()
```

But the following exception is thrown:

> Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
>    at java.util.ArrayList.get(ArrayList.java:437)
>      at org.altbeacon.beacon.c.i(:3)
>      at com.armsapp.checkin.MainActivity.a(:93)
>       at com.armsapp.checkin.MainActivity.a()
>      at com.armsapp.checkin.MainActivity$d.a(:11)
>       at org.altbeacon.beacon.i.a(:122)
>       at org.altbeacon.beacon.e$a.onReceive(:5)
>       at g.f.a.a.a(:59)
>       at g.f.a.a$a.handleMessage(:11)
>       at android.os.Handler.dispatchMessage(Handler.java:106)
>       at android.os.Looper.loop(Looper.java:193)
>      at android.app.ActivityThread.main(ActivityThread.java:6702)
>       at java.lang.reflect.Method.invoke(Method.java)
>       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
>       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)

### Mobile device model and OS version
Armor_X3 and OS 9.0
### Android Beacon Library version
2.17.1

**Comment by davidgyoung** [comment]
This exception is most certainly caused by the application and not the library itself.  The crash is triggered on this line:

com.armsapp.checkin.MainActivity.a(:93)

Helping debug third party apps’ use of this library is out of scope for this forum.  I’d suggest you post to StackOverflow.com including your code shown on the line above.
