### ISSUE TITLE
Is it possible to get the beacons list through Monitor notifier callback??

### ISSUE THREAD

**Issue by Ramachandran322** [AltBeacon/android-beacon-library#992]
I need the application to detect beacons within 5 meter distance. This I could achieve through RangeNotifier's **didRangeBeaconsInRegion(Collection<Beacon> beacons, Region region)** method.

However, I have configured the application to send push notification through MonitorNotifier which I could not configure the distance. 

Is there any way to reduce the distance at which the MonitorNotifier callback method's called(didEnterRegion, didExitRegion). Or else anywhere I could globally set the distance at which the beacons could be identified.

**Comment by davidgyoung** [comment]
For help on how to use this library, please open a question on StackOverflow.com.  This forum is reserved for bug reports and feature requests with the library.

The library's online documentation already has a section that covers this:  https://altbeacon.github.io/android-beacon-library/distance-triggering.html   If you have further questions, please open one on StackOverflow.com

**Comment by Ramachandran322** [comment]
Thank you
