### ISSUE TITLE
Reference app not restarting itself with RegionBootstrap in background

### ISSUE THREAD

**Issue by malibu1966** [AltBeacon/android-beacon-library#999]
I was attempting to use the demo code for "Starting an App in the Background" to my app and it wasn't working.  Now I have tried the code in the reference app and getting the same result.

### Expected behavior

App launches itself

### Actual behavior

App does not launch.  Log seems to indicate that the intent is being created and submitted but it does not start the app, nor can I find any sign of code execution within the MonitoringActivity, which is what the intent targets in the reference app.

### Steps to reproduce this behavior

- Install reference app
- Add ibeacon monitoring at line 45:
```
        beaconManager.getBeaconParsers().add(new BeaconParser().
                setBeaconLayout("m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24"));
```
- Start app, start ranging
- Kill app through sliding off app switcher or put it in the background; both will produce error
- Use beacon simulator to start beacon (I am using an iBeacon in Beacon Simulator on Android)
- Witness nothing happening.  My understanding is that the app screen should launch at this point.

### Mobile device model and OS version
Samsung Note 9
Android 10, kernel 4.9.186-18803994

### Android Beacon Library version

2.17.1

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment]
OK, I understand the issue. As of Android O it is no longer possible to auto-launch an activity on beacon detection.  The most you can do is send a notification, and then let the user tap the notification to bring up the activity.  The reference app was just never updated with that change.  I have corrected that here:  https://github.com/AltBeacon/android-beacon-library-reference/pull/62
